### ISSUE TITLE
activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference

### ISSUE THREAD

**Issue by yueqistar** [YoKeyword/Fragmentation#1004]
全部信息:
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xhky.gwcs/com.xhky.gwcs.function.main.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2483)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543)
        at android.app.ActivityThread.access$1000(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
        at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
        at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
        at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
        at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:120)
        at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)
        at com.xhky.gwcs.base.BaseMainFragment.onCreate(BaseMainFragment.java:40)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2417)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3223)
        at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1523)
        at android.support.v4.app.Fragment.onCreate(Fragment.java:1494)
        at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:47)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2417)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3223)
        at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:369)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
        at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
        at com.xhky.gwcs.function.main.activity.MainActivity.onCreate(MainActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:6357)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)

**Comment by YoKeyword** [comment]
v1.3.7
