### ISSUE TITLE
Maictivity extends SupportActivity 横竖屏切换 NullPointerException

### ISSUE THREAD

**Issue by lovskay** [YoKeyword/Fragmentation#1014]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.3.6
* Support-v4 version 27.1.1
* Logs
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
        at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
        at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
        at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
        at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:120)
        at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3194)
        at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:184)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:355)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
        at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
        at com.shiyebaidu.ceo.activity.MainActivity.onCreate(MainActivity.java:82)
        at android.app.Activity.performCreate(Activity.java:6964)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by beilo** [comment]
https://github.com/YoKeyword/Fragmentation/issues/907

**Comment by YoKeyword** [comment]
v1.3.7
