### ISSUE TITLE
啊，将项目改造完发现不支持DialogFragment

### ISSUE THREAD

**Issue by VipMinF** [YoKeyword/Fragmentation#1017]
啊，花了一整天将项目改造完发现不支持DialogFragment，要吐血。。。。。。。。。
好吧，那就自己写一个SupportDialogFragment，将SupportFragment的代码拷贝过去，成功的展示了Dialog，然后dialog底部居然有个白色背景（我的dialog大小只有半屏）。有白色背景也就算了，居然列表滚动不了，滚动不了算了，居然一点击就崩溃。

    public void show() {
        final Activity activity = ActivityStack.geTaskTopActivity();
        if (activity instanceof FragmentActivity) {
            activity.runOnUiThread(
                    new Runnable() {
                        @Override
                        public void run() {
                            if(activity instanceof SupportActivity){
                                ((SupportActivity) activity).extraTransaction().startDontHideSelf(BaseDialog.this);
                            }else
                            show(((FragmentActivity) activity).getSupportFragmentManager());
                        }
                    }
            );
        }
    }

  java.lang.IllegalStateException: Can't find container, please call loadRootFragment() first!
        at me.yokeyword.fragmentation.TransactionDelegate.getTopFragmentForStart(TransactionDelegate.java:395)
        at me.yokeyword.fragmentation.TransactionDelegate.doDispatchStartTransaction(TransactionDelegate.java:353)
        at me.yokeyword.fragmentation.TransactionDelegate.access$400(TransactionDelegate.java:32)
        at me.yokeyword.fragmentation.TransactionDelegate$4.run(TransactionDelegate.java:132)
        at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
        at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
        at me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:17)
        at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6281)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)

不知如何形容今天的心情

**Comment by beilo** [comment]
错误提示的很明显了
```
Can't find container, please call loadRootFragment() first!
```
你要在有个root fragment的前提下才能start

**Comment by VipMinF** [comment]
> 错误提示的很明显了
> 
> ```
> Can't find container, please call loadRootFragment() first!
> ```
> 你要在有个root fragment的前提下才能start

dismiss 之后 再show 就会把这个报这个错

**Comment by beilo** [comment]
你打开栈视图看看呗.  这种情况看看栈视图就大概清楚了

**Comment by VipMinF** [comment]
> 你打开栈视图看看呗. 这种情况看看栈视图就大概清楚了
看到了，就是把我的RootFragment给移除了，dismiss 之后 变成空白，不知道他在那一步移除的。没有空研究，赶着上线，就回退版本了

**Comment by ruanbaojun1105** [comment]
为什么用dialog fragment ，fradment 一样使用啊

**Comment by iostyle** [comment]
我这边列表可以滑动，唯独背景变白了。 看了栈视图没有问题 @beilo @VipMinF

**Comment by iostyle** [comment]
哦 根布局设置背景透明可解决

**Comment by JohnsonJLi** [comment]
我遇到的问题是  DialogFragment  一直显示在最上层 无论怎么start
前一个页面的DialogFragment 只要不关闭 start下一个页面 还会显示

**Comment by YoKeyword** [comment]
@JohnsonJLi 
DialogFragment中的Dialog是window，和Activity同级别， 所以DialogFragment会一直显示在最上层 

建议自己封装模拟一个半透明类似Dialog的`SupportFragment`（View级别的“Dialog”）

**Comment by JohnsonJLi** [comment]
@YoKeyword 
大神 我封装了一个半透明的SupportFragment 出现了一个问题 当软键盘弹起时整个fragment(从dialog背景中看到)都被挤压 如图:
![image](https://user-images.githubusercontent.com/18025692/60233479-0ae7de00-98d3-11e9-9e4a-55aec2a6d53b.png)
请问有没有什么解决方案 求指点;
