### ISSUE TITLE
Fragment already added

### ISSUE THREAD

**Issue by a12115678** [YoKeyword/Fragmentation#1020]
java.lang.IllegalStateException: Fragment already added: AboutDelegate{1df94a8 #4 id=0x7f08003f com.pm.settings.AboutDelegate}
        at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1882)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:762)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

在   getSupportDelegate().start(new AboutDelegate());部分机型会出现错误

**Comment by beilo** [comment]
https://github.com/YoKeyword/Fragmentation/issues/546

请参考上面那个iss,进行排查问题
