### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2318423730** [YoKeyword/Fragmentation#1028]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.cmx.smartlock, PID: 7745
                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.support.v4.app.Fragment.getArguments()' on a null object reference
                      at me.yokeyword.fragmentation.TransactionDelegate.getArguments(TransactionDelegate.java:434)
                      at me.yokeyword.fragmentation.TransactionDelegate.access$200(TransactionDelegate.java:33)
                      at me.yokeyword.fragmentation.TransactionDelegate$3.run(TransactionDelegate.java:108)
                      at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:46)
                      at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:38)
                      at me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:16)
                      at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:30)
                      at android.os.Handler.handleCallback(Handler.java:742)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:157)
                      at android.app.ActivityThread.main(ActivityThread.java:5696)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by YoKeyword** [comment]
建议升级v1.3.7试试
