### ISSUE TITLE
报了java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by pye52** [YoKeyword/Fragmentation#103]
因为仿微信交互demo不支持左右滑动切换标签页
所以我用loadRootFragment添加了一个含viewpager的根fragment（其实我觉得与这个无关）
也是通过eventbus的方式从根fragment来启动fragment
但是发现每启动一个fragment都会报这个错…

`java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1527)
                at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1545)
                at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:654)
                at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:621)
                at me.yokeyword.fragmentation.Fragmentation.start(Fragmentation.java:220)
                at me.yokeyword.fragmentation.Fragmentation.dispatchStartTransaction(Fragmentation.java:135)
                at me.yokeyword.fragmentation.SupportActivity.start(SupportActivity.java:160)
                at me.yokeyword.fragmentation.SupportActivity.start(SupportActivity.java:155)
                at com.ctt.zuxin.push.activity.MainPage.startBrother(MainPage.java:169)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
                at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
                at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
                at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                at com.ctt.zuxin.push.fragment.PartnerFragment.onClick(PartnerFragment.java:67)
                at android.view.View.performClick(View.java:4792)
                at android.view.View$PerformClick.run(View.java:19915)
                at android.os.Handler.handleCallback(Handler.java:739)
                at android.os.Handler.dispatchMessage(Handler.java:95)
                at android.os.Looper.loop(Looper.java:135)
                at android.app.ActivityThread.main(ActivityThread.java:5298)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)`

**Comment by YoKeyword** [comment]
看样这个问题有必要写在文章里...

是这样的，在你离开当前Activity等情况下，系统会调用`onSaveInstanceState()`帮你保存当前Activity&Fragment的一些状态数据等，而在离开后（onSaveInstanceState()已经被执行），你又去执行Fragment的相关事务方法后，就会抛出该异常！

解决方法2个：
1、该事务使用`commitAllowingStateLoss()`方法提交事务，但是有可能导致该次提交无效！
2、（推荐）在重新回到该Activity的时候（比如onStart里），再执行该事务！
