### ISSUE TITLE
不兼容AppCompatDialogFragment

### ISSUE THREAD

**Issue by iostyle** [YoKeyword/Fragmentation#1038]
崩溃信息:
AppCompatDialogFragment cannot be cast to me.yokeyword.fragmentation.ISupportFragment

类名:VisibleDelegate.java

方法:isParentInvisible

行数:180

类型:java.lang.ClassCastException

时间2018-11-20 14:26

设备名称:MI 8

设备厂商:Xiaomi

系统版本:27

全部信息:
java.lang.ClassCastException: AppCompatDialogFragment cannot be cast to me.yokeyword.fragmentation.ISupportFragment
	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.isParentInvisible(VisibleDelegate.java:180)
	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.dispatchSupportVisible(VisibleDelegate.java:138)
	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.access$000(VisibleDelegate.java:19)
	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate$1.run(VisibleDelegate.java:132)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6650)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)

**Comment by iostyle** [comment]
需要一个SupportDialogFragment implements ISupportFragment ?

**Comment by androidCircle** [comment]
我也遇到这个问题  请问你解决了吗

**Comment by zhupengxiang** [comment]
这个问题怎么解决的  老铁
