### ISSUE TITLE
大佬, jetpack/androidx  还没支持 QAQ

### ISSUE THREAD

**Issue by tyzero** [YoKeyword/Fragmentation#1067]
#FragmentationMagician 返回的时候crash了
```
java.lang.NoSuchFieldError: No field mActive of type Landroid/util/SparseArray; in class Landroidx/fragment/app/FragmentManagerImpl; or its superclasses (declaration of 'androidx.fragment.app.FragmentManagerImpl' appears in /data/app/ x-2/base.apk)
        at androidx.fragment.app.FragmentationMagician.getActiveFragments(FragmentationMagician.java:153)
        at me.yokeyword.fragmentation.SupportHelper.getActiveFragment(SupportHelper.java:159)
        at me.yokeyword.fragmentation.SupportHelper.getActiveFragment(SupportHelper.java:131)
        at me.yokeyword.fragmentation.SupportActivityDelegate$1.run(SupportActivityDelegate.java:157)
        at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
        at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
        at me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:17)
        at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6247)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```
Following information can help us to resolve the issue faster.

**项目 移除了Android support 包，迁移到AndroidX** 
[https://developer.android.google.cn/jetpack/androidx/]( https://developer.android.google.cn/jetpack/androidx/
)

**Comment by leeyun** [comment]
开启兼容模式就好了

**Comment by tyzero** [comment]
> 开启兼容模式就好了

@leeyun 已经修复了，不是没开兼容模式的问题，是AndroidX 最新版本的SparseArray mActive换了个实现，变成了HashMap，我退回AndroidX 1.0.0 就好了

**Comment by yuxiujuan** [comment]
@tyzero 真的升级到的1.1不行了，退回来好了^-^

**Comment by snpmyn** [comment]
暂时添加如下依赖  implementation 'com.android.support:drawerlayout:28.0.0'   可以暂时避免，但不是根本解决。

**Comment by snpmyn** [comment]
说错了，解决不了。
