### ISSUE TITLE
Few time raised this crash , i got from crashlytics

### ISSUE THREAD

**Issue by sathishmscict** [YoKeyword/Fragmentation#1073]
Library version  : 1.3.6
Support-v4 version :  implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Logs

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5229)
       at android.view.ViewGroup.removeViewAt(ViewGroup.java:5192)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1796)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
       at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:814)
       at androidx.fragment.app.FragmentationMagician$4.run(FragmentationMagician.java:134)
       at androidx.fragment.app.FragmentationMagician.hookStateSaved(FragmentationMagician.java:194)
       at androidx.fragment.app.FragmentationMagician.executePendingTransactionsAllowingStateLoss(FragmentationMagician.java:131)
       at me.yokeyword.fragmentation.TransactionDelegate.safePopTo(TransactionDelegate.java:579)
       at me.yokeyword.fragmentation.TransactionDelegate.mockPopToAnim(TransactionDelegate.java:608)
       at me.yokeyword.fragmentation.TransactionDelegate.doPopTo(TransactionDelegate.java:565)
       at me.yokeyword.fragmentation.TransactionDelegate.access$1300(TransactionDelegate.java:32)
       at me.yokeyword.fragmentation.TransactionDelegate$11.run(TransactionDelegate.java:293)
       at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
       at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
       at me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:17)
       at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by YoKeyword** [comment]
[androidx support](https://github.com/YoKeyword/Fragmentation#how-do-i-use-fragmentation)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
