### ISSUE TITLE
在后台吧 权限关掉重新开启会出现 DebugStackDelegate 为Null的 情况 

### ISSUE THREAD

**Issue by w296488320** [YoKeyword/Fragmentation#1123]
java.lang.NullPointerException: Attempt to invoke virtual method 'void me.yokeyword.fragmentation.debug.DebugStackDelegate.onPostCreate(int)' on a null object reference
                                                       at me.yokeyword.fragmentation.SupportActivityDelegate.onPostCreate(SupportActivityDelegate.java:61)
                                                       at me.yokeyword.fragmentation.SupportActivity.onPostCreate(SupportActivity.java:45)
                                                       at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1343)
                                                       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3004)
                                                       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
                                                       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
                                                       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
                                                       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1838)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:201)

**Comment by qinyang1018** [comment]
能否详细描述下。 
初步认为你这个是自己的代码中没处理好运行时权限的问到时了崩溃。
