### ISSUE TITLE
androidX,   onDestroy case NPE

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#1136]
# Issues Guideline

rt

* Library version 
    me.yokeyword:fragmentationx:1.0.0

* Support-v4 version 
     androidx.appcompat:appcompat:1.1.0-beta01
* Logs
```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.fragment.app.FragmentManagerImpl.dispatchDestroy()' on a null object reference
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2820)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1027)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1237)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1302)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2655)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2640)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at me.yokeyword.fragmentation.SupportActivity.onDestroy(SupportActivity.java:51)
        at com.sf.ui.base.BaseActivity.onDestroy(BaseActivity.java:398)
```

**Comment by zhangshaobo87** [comment]
你怎么解决的，我这里也出现了
