### ISSUE TITLE
最新版本的androidx会报错java.lang.NoSuchFieldError: No field mActive of type Landroid/util/SparseArray

### ISSUE THREAD

**Issue by WangTao0127** [YoKeyword/Fragmentation#1196]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
    'me.yokeyword:fragmentation:1.3.7'
* Support-v4 version
    'androidx.appcompat:appcompat:1.1.0'
    'androidx.core:core-ktx:1.1.0'
* Logs
    java.lang.NoSuchFieldError: No field mActive of type Landroid/util/SparseArray; in class Landroidx/fragment/app/FragmentManagerImpl; or its superclasses (declaration of 'androidx.fragment.app.FragmentManagerImpl' appears in /data/app/com.yuzheng.iganalytics-Dvws7LZizve9jyR26UVXZA==/base.apk!classes3.dex)
        at androidx.fragment.app.FragmentationMagician.getActiveFragments(FragmentationMagician.java:156)
        at me.yokeyword.fragmentation.SupportHelper.getPreFragment(SupportHelper.java:95)
        at me.yokeyword.fragmentation.SupportFragmentDelegate$3.run(SupportFragmentDelegate.java:612)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
* Screenshots
   没有截图直接闪退
**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by DeAikon** [comment]
用 androidx 版本的框架
将依赖
me.yokeyword:fragmentation:1.3.7
改为
me.yokeyword:fragmentationx:1.0.1

参考 androidx 分支的英文 readme
