### ISSUE TITLE
activity中加载一个fragment在activity退出时crash 报空指针

### ISSUE THREAD

**Issue by zhangshaobo87** [YoKeyword/Fragmentation#1206]
使用的版本是 me.yokeyword:fragmentationx:1.0.1；
使用方式如下：
`
        SupportFragment fragment = findFragment(TestFragment.class);
        if (null == fragment) {
            loadRootFragment(R.id.container, new TestFragment(), false, true);
        }
`
错误日志如下：
` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManager.isDestroyed()' on a null object reference
        at androidx.fragment.app.Fragment.performDetach(Fragment.java:2942)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1519)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1668)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1748)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1812)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3118)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3103)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:330)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:365)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at me.yokeyword.fragmentation.SupportActivity.onDestroy(SupportActivity.java:51)
        at com.xxxxxx.BaseActivity.onDestroy(BaseActivity.java:81)
        at android.app.Activity.performDestroy(Activity.java:7524)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4502)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4535) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) `

**Comment by piakia** [comment]
遇到相同问题 请问怎么搞的
