### ISSUE TITLE
FragmentAnimator.getEnter() null object

### ISSUE THREAD

**Issue by romantiskt** [YoKeyword/Fragmentation#123]
程序从后台运行切回前台显示,某些时候会出现 这个错误..  并且在调试过程中因为其它原因崩溃抛 RuntimeException 时,程序会自动重启一遍,这个时候也会出现此错误

**Comment by YoKeyword** [comment]
有更详细的log吗？

是实际项目还是DEMO中出现的

**Comment by romantiskt** [comment]
` java.lang.RuntimeException: Unable to start activity ComponentInfo{.main.MainActivity_}: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:180)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1562)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5824)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
                                                       at me.yokeyword.fragmentation.helper.AnimatorHelper.initEnterAnim(AnimatorHelper.java:44)
                                                       at me.yokeyword.fragmentation.helper.AnimatorHelper.<init>(AnimatorHelper.java:23)
                                                       at me.yokeyword.fragmentation.SupportFragment.initAnim(SupportFragment.java:124)
                                                       at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:101)`

**Comment by romantiskt** [comment]
不是demo...

**Comment by YoKeyword** [comment]
FragmentAnimator为空了，检查下Activity/Fragment里的:
````java
 protected FragmentAnimator onCreateFragmentAnimator() {
 }
````
不能返回null，如果想让其无动画，返回DefaultNoAnimator对象；

指定某个行为(比如进栈)无动画时， retrun  new FragmentAnimator(0,xx,xx,xx);

**Comment by romantiskt** [comment]
@Override
    public FragmentAnimator onCreateFragmentAnimator() {
        // 设置横向(和安卓4.x动画相同)
        return new DefaultHorizontalAnimator();
    }

我是根据demo写的，如上。。。我猜是因为后台会把mFragmentAnimator回收了

**Comment by YoKeyword** [comment]
你可以看下源码，会保存的，在回收后，会重新找回的~

**Comment by YoKeyword** [comment]
我回头再检查下demo 看是否有这个问题哈~

**Comment by YoKeyword** [comment]
检查了下Demo，没发现这个异常
