### ISSUE TITLE
java.lang.IllegalStateException: No host

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#140]
@YoKeyword 
非常抱歉又来叨扰。
以下是我的报错信息。
` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shtoone.chenjiang/com.shtoone.chenjiang.mvp.view.main.project.ProjectActivity}: java.lang.IllegalStateException: No host
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:156)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:153)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5297)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.IllegalStateException: No host
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1277)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2144)
                                                                           at android.support.v4.app.Fragment.onCreate(Fragment.java:1258)
                                                                           at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:77)
                                                                           at me.yokeyword.fragmentation_swipeback.SwipeBackFragment.onCreate(SwipeBackFragment.java:21)
                                                                           at com.shtoone.chenjiang.mvp.view.base.BaseFragment.onCreate(BaseFragment.java:35)
                                                                           at com.shtoone.chenjiang.mvp.view.base.BaseLazyFragment.onCreate(BaseLazyFragment.java:19)
                                                                           at android.support.v4.app.Fragment.performCreate(Fragment.java:2068)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1055)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                           at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                           at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                                                                           at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                           at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1167)
                                                                           at android.app.Activity.performStart(Activity.java:5132)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358) 
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:156) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:153) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5297) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                           at dalvik.system.NativeStart.main(Native Method) `

平时都是用系统是5.0以上的手机调试，今天突然用一个系统是4.2的手机调试，报了这个错，然后我用模拟器开个4.4的系统，也是报这个错。这个Activity就是底部有三个tab，用来切换不同fragment，然后都是用的懒加载形式。一进去默认选中第一个tab，第一个tab对应的fragment就是你demo中的流式嵌套里的商店fragment。即左边一个fragment的菜单，右边一个fragment对应着内容。
在5.0以上手机好得很，可是今天就用4.4和一个4.2.1的手机就报错。java.lang.IllegalStateException: No host这个错误我也是第一看到，但我不知道为什么找不到宿主。
请问你在用fragment时遇到过这种情况吗？

**Comment by leguang** [comment]
我排查了一下，之前我就在另一个App上用这样的代码，用的好好的，只是第一个tab对应的fragment没有如你的shopfragment那样，只是一个简单fragment。开始还以为是你框架的版本问题，我升级和降低版本都不行。最终定位到loadMultipleRootFragment(R.id.fl_container_project_activity, 0, mFragments[0], mFragments[1], mFragments[2]);这行代码，如果我注释掉就可以启动这个Activity，能看到底部的三个tab，只是没有fragment而已（因为我的主题是透明的，所以知道没有feagment），然后我replaceLoadRootFragment(R.id.fl_container_project_activity, mFragments[0], false);这行代码代替，也可以启动，我明天写事务自己切换试试。暂时就只排查到这里。
大侠若有相关经验，望不吝赐教。

**Comment by YoKeyword** [comment]
(demo在4.4版本有测过，应该是没这个问题)
我google了下，有人说是getChildFragmentManager()，  而getChildFragmentManager()确实和getFragmentManager()创建和恢复的实际不同，getChildFragmentManager()会慢一些；

**一个建议是： 如果可能的话，在调用FragmentManager时，应尽量使用子Fragment的`getFragmentManager()`来代替父Fragment的`getChildFragmentManager()`**

**Comment by leguang** [comment]
原因找到了，是我的原因，我居然在BaseFragment里调用这个调试栈信息的代码
`    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mPresenter = createPresenter();

        //打印fragment栈
//        _mActivity.logFragmentStackHierarchy("SHTW");
    }`
当时记得是在调试，后来忘删了，估计在5.1.1以上机器调试没问题的原因是因为机器够快？而我的那台4.2.1的是一台历史悠久的机器，很慢？我瞎掰的。
哎，在基类中调用宿主Activity中的代码，可能当时宿主还没创建好。无辜的被自己坑了一把。
多有打扰哈。^_^

**Comment by YoKeyword** [comment]
哦哦 放到post或postDelay里就可以啦

**Comment by leguang** [comment]
明白。你可以关闭这个issue了。感谢！
