### ISSUE TITLE
回退栈错误，找不到原因....

### ISSUE THREAD

**Issue by adminLiu-s** [YoKeyword/Fragmentation#153]
java.lang.NullPointerException
                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:716)
                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at android.os.Looper.loop(Looper.java:136)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5288)
                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by YoKeyword** [comment]
😂  这个日志 神仙也找不到啊....
在什么场景下发生的，有更详尽的日志吗～

**Comment by adminLiu-s** [comment]
没....主要发生在点击主页第二个tab（主页4个tab）,隔一段时间会重现一次，就是点击进某个功能二级页面再退退退，退到主页点击第二个tab就挂了........

**Comment by YoKeyword** [comment]
tab里点击进入后的页面是Fragment吗？  栈层级是怎么样的？

**Comment by adminLiu-s** [comment]
全fragment，第一个项目已用了160多fragment，主mainfragment加载4个fragment对应4个tab，而且很奇怪，用了这架构之后报错不会直接崩掉，而是会ANR，错误日志一直打印个不停，不知道作者用这架构时有没有遇到过？

**Comment by YoKeyword** [comment]
留意出错前，栈视图是什么样子的， 观察是否错乱、异常等等

报错会直接崩，和AC一样，是手机问题？

**Comment by YoKeyword** [comment]
你的这个异常，我查了下，原因可能是
**存在add(null) ，或show(null) 或hide(null) 等情况，从而引起的**

观察好栈视图，然后必要的地方打log，如果能复现，在崩溃的地方打断点观察！

**Comment by adminLiu-s** [comment]
嗯嗯，现在重构项目有点忙，等有空了好好排查下，查出了给你原因
