### ISSUE TITLE
二级fragment中长时间后台，fragment丢失

### ISSUE THREAD

**Issue by z2045217** [YoKeyword/Fragmentation#188]
我是首页五个fragment,其中有两个Fragment中嵌套了二级fragment,首页fragment是if (savedInstanceState == null) {
            UserData.Current.Main_PageIndex = CommonEnum.MainPageIndex.Hall;
            listFragment.add(CommonEnum.MainPageIndex.Hall,Fragment_Main_Hall.newInstance());
            listFragment.add(CommonEnum.MainPageIndex.Attention,Fragment_Main_Attention.newInstance());
            listFragment.add(CommonEnum.MainPageIndex.Ranking,Fragment_Main_Rank.newInstance());
            listFragment.add(CommonEnum.MainPageIndex.Mine,Fragment_Main_Mine.newInstance());
            listFragment.add(CommonEnum.MainPageIndex.Search, Fragment_Main_Search.newInstance());

            loadMultipleRootFragment(R.id.flMain, UserData.Current.Main_PageIndex,
                    listFragment.get(CommonEnum.MainPageIndex.Hall),
                    listFragment.get(CommonEnum.MainPageIndex.Attention),
                    listFragment.get(CommonEnum.MainPageIndex.Ranking),
                    listFragment.get(CommonEnum.MainPageIndex.Mine),
                    listFragment.get(CommonEnum.MainPageIndex.Search));
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题
            UserData.Current.Main_PageIndex = savedInstanceState.getInt("Type");
            // 这里我们需要拿到mFragments的引用,也可以通过getSupportFragmentManager.getFragments()自行进行判断查找(效率更高些),用下面的方法查找更方便些
            listFragment.add(CommonEnum.MainPageIndex.Hall,findFragment(Fragment_Main_Hall.class));
            listFragment.add(CommonEnum.MainPageIndex.Attention,findFragment(Fragment_Main_Attention.class));
            listFragment.add(CommonEnum.MainPageIndex.Ranking,findFragment(Fragment_Main_Rank.class));
            listFragment.add(CommonEnum.MainPageIndex.Mine,findFragment(Fragment_Main_Mine.class));
            listFragment.add(CommonEnum.MainPageIndex.Search,findFragment(Fragment_Main_Search.class));
        }
方式写的。没有问题。也不会出现丢失，但是其中有嵌套fragment包含的fragment丢失了。再次点击之后没有显示。其中fragment中是这样写的
  if (savedInstanceState == null) {
            // ShopFragment是flow包里的
            listRankFragment.add(Fragment_Main_Rank_List.newInstance(2,"Beans"));
            listRankFragment.add(Fragment_Main_Rank_List.newInstance(1,"Coin"));
            listRankFragment.add(Fragment_Main_Rank_List.newInstance(2,"Anchor_Pomelo"));
            listRankFragment.add(Fragment_Main_Rank_Week.newInstance(1));
            listRankFragment.add(Fragment_Main_Rank_Week.newInstance(2));
            loadMultipleRootFragment(R.id.fl_content,0, listRankFragment.get(0)
                                                        ,listRankFragment.get(1)
                                                        ,listRankFragment.get(2)
                                                        ,listRankFragment.get(3)
                                                        ,listRankFragment.get(4));
        } else { // 这里可能会出现该Fragment没被初始化时,就被强杀导致的没有load子Fragment
            listRankFragment.add(Fragment_Main_Rank_List.newInstance(2,"Beans"));
            listRankFragment.add(Fragment_Main_Rank_List.newInstance(1,"Coin"));
            listRankFragment.add(Fragment_Main_Rank_List.newInstance(2,"Anchor_Pomelo"));
            listRankFragment.add(Fragment_Main_Rank_Week.newInstance(1));
            listRankFragment.add(Fragment_Main_Rank_Week.newInstance(2));
            if (findChildFragment(Fragment_Main_Rank_List.class) == null||findChildFragment(Fragment_Main_Rank_Week.class) == null) {
                loadMultipleRootFragment(R.id.fl_content,0, listRankFragment.get(0)
                                                            ,listRankFragment.get(1)
                                                            ,listRankFragment.get(2)
                                                            ,listRankFragment.get(3)
                                                            ,listRankFragment.get(4));
            }
        }。切换fragment都是showHideFragment（）的方式。在此请问下作者。希望得到作者的帮助。

**Comment by YoKeyword** [comment]
你会发现我的zhihu Demo里，嵌套 子Fragment的 load是放在onLazyInitView里加载的，你第二段代码放到onLazyInitView即可

**Comment by z2045217** [comment]
你好，作者。我的项目一共有三级嵌套，我就是按照你的demo写的。第二级嵌套的子fragment 是放在了 public void onLazyInitView(@Nullable Bundle savedInstanceState) 这个方法里。第三级，也就是最后一级没有加，是不是这个原因？？

**Comment by YoKeyword** [comment]
应该不是这个原因， 因为3级的父亲是2级，  2级是在`onLazyInitView `里加载的，2级不加载3级没机会被加载～

你可以打开 开发者模式里 -> 不保留活动 ， 通过回到桌面再回到App，模拟被强杀的情景，打断点调试来判断到底为何发生这种情况～

**Comment by z2045217** [comment]
我没有找了。我修改了别的方式。在每次销毁的时候。在重新生成一个新的。没有出现丢失问题了。

**Comment by z2045217** [comment]
但是我还遇见了新的问题，我在fragment中有个present对象在数据的处理。几乎所有的地方都有用。但是时间长了。会出现崩溃退出。报到问题是空指针。我截取了其中的一个。：
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.xiyounetworktechnology.xiutv.view.DialogAttentionView.initAttentionList(org.json.JSONArray)' on a null object reference
                                                                                    at com.xiyounetworktechnology.xiutv.presenter.DialogAttentionPresent.lambda$initAttentionList$1(DialogAttentionPresent.java:43)
                                                                                    at com.xiyounetworktechnology.xiutv.presenter.DialogAttentionPresent.access$lambda$1(DialogAttentionPresent.java:0)
                                                                                    at com.xiyounetworktechnology.xiutv.presenter.DialogAttentionPresent$$Lambda$2.call(Unknown Source)
                                                                                    at rx.Observable$28.onNext(Observable.java:8192)
                                                                                    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                    at rx.internal.operators.OperatorDoAfterTerminate$1.onNext(OperatorDoAfterTerminate.java:48)
                                                                                    at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
                                                                                    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
                                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                    at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                    at android.os.Looper.loop(Looper.java:207) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5689) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764) 
问下作者，这样的情况有什么思路解决吗？？或者保存吗？

**Comment by YoKeyword** [comment]
看起来是`DialogAttentionView `为null了～  建议你使用开发者模式调试下，可以很快定位到原因

你完全可以模拟这个`长时间放置，页面重启的问题`， 这个就是App内存不足，被系统回收了资源；

模拟方式：  打开“开发者模式” -> “不保留活动”  ；  开启后，一旦离开Activity，上个Activity就会被强杀掉，你可以打开App然后home键回到桌面，再重新打开来模拟你说的场景 :)
