### ISSUE TITLE
在android4.4系统下报错

### ISSUE THREAD

**Issue by hjldev** [YoKeyword/Fragmentation#203]
demo没问题，导入到自己的项目就报错。6.0的系统不报错
Caused by: java.lang.IllegalStateException: No host
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1282)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1277)
                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2149)
                                                                    at android.support.v4.app.Fragment.onCreate(Fragment.java:1265)
                                                                    at com.trello.rxlifecycle.components.support.RxFragment.onCreate(RxFragment.java:50)
                                                                    at mobi.xingqu.wo.fragmentation.SupportFragment.onCreate(SupportFragment.java:102)
                                                                    at mobi.xingqu.wo.mvp.ui.BaseFragment.onCreate(BaseFragment.java:61)
                                                                    at android.support.v4.app.Fragment.performCreate(Fragment.java:2075)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1060)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                                    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                                    at android.app.Activity.performStart(Activity.java:5368)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by YoKeyword** [comment]
> demo没问题，导入到自己的项目就报错

描述清楚点... 从异常日志看：   出现了`RxFragment `而不是SupportFragment，继承的机会只有一次，你继承了哪个类？  这个库都是在继承SupportActivity,SupportFragment的前提下才可以的

另外:No host的异常 有一种可能是你使用了嵌套Fragment，而没有使用正确的FragmentManager，比如你可能使用了`getSupportFragmentManager/getFragmentManager`，可能正确的是用`getChildFragmentManager()`

你仔细检查下代码，还没头绪就说明下具体情况，贴代码吧～

**Comment by hjldev** [comment]
找到问题了。在使用Fragment的时候有一个地方我是使用的getActivity()，可能在使用的时候getActivity得到的跟宿主activity不一样？替换成_mActivity就可以。还有一个问题是在Fragment弹出键盘之后pop掉这个fragment后用leakcanary会检测到内存泄漏。

**Comment by YoKeyword** [comment]
如果是 _mActivity替换getActivity() 就可以的话，  那我猜测你可能在detach后还在操作Fragment，此时使用getActivity()会报上述异常，_mActivity因为持有宿主引用，所有可以正常使用；

而内存泄漏也和这有关系，推荐看下相关文章或者搜索下； 总之，维护好Activity和Fragment的关系，Fragment的异步任务等等应该及时停止～
