### ISSUE TITLE
SupportFragment.dispatchSupportVisible NullPointerException

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#210]
```

java.lang.NullPointerException
	at me.yokeyword.fragmentation.SupportFragment.dispatchSupportVisible(SupportFragment.java:389)
	at me.yokeyword.fragmentation.SupportFragment.dispatchSupportVisible(SupportFragment.java:370)
	at me.yokeyword.fragmentation.SupportFragment.dispatchSupportVisible(SupportFragment.java:370)
	at me.yokeyword.fragmentation.SupportFragment.onHiddenChanged(SupportFragment.java:302)
	at android.support.v4.app.FragmentManagerImpl.completeShowHideFragment(FragmentManagerImpl.java:1502)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1553)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1585)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2145)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManagerImpl.java:2092)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1998)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:709)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5279)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(NativeStart.java)
```

上线后，大规模遇到以面的异常。(版本号：0.9.3 )

另外，还有

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.setNextTransition(int, int)' on a null object reference
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:716)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2303)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2132)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManagerImpl.java:2092)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1998)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:709)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5451)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by YoKeyword** [comment]
看崩溃应该是show hide Fragment时，Fragment还没有绑定宿主Activity，导致空指针，刚push了做了非空校验； 

现在还没更新版本，第二个异常发生在什么情况，看代码是Fragment为null了
