### ISSUE TITLE
showHideFragment Exception

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#213]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.setNextTransition(int, int)' on a null object reference
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:716)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2303)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2132)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManagerImpl.java:2092)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1998)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:709)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5451)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

 call `showHideFragment(currentFragment);`

```
List<Fragment> fragmentList = fragmentManager.getFragments();
```
List 中有 null 对象

![exception](https://cloud.githubusercontent.com/assets/18303646/21879691/6dd25e70-d8d5-11e6-95e2-e421b0b183a1.png)

**Comment by zhenian** [comment]
不少地方用到 List<Fragment> fragmentList = fragmentManager.getFragments(); 做循环处理，都应该加上非空判断

**Comment by YoKeyword** [comment]
感谢🙏，fragment!=showFragment 确实需要判断 非空的～ 已Merge

另外instanceof不需要判空，空的话不会报错，一样走不进if里的～ 我移除了 instanceof判空的代码

**Comment by dxiaogang** [comment]
我也遇到,正想提个

**Comment by YoKeyword** [comment]
:)   已经push了0.9.5， 修复了这个问题～
