### ISSUE TITLE
onSupportInvisible 能调用 SupportFragment.pop() 导致异常

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#216]
# 异常堆栈

```
java.lang.RuntimeException: Unable to pause activity {com.zhenian.reader/com.zhenian.reader.ui.reader.ReaderActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3070)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3025)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3003)
	at android.app.ActivityThread.access$800(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5109)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
	at me.yokeyword.fragmentation.SupportFragment.pop(SupportFragment.java:652)
	at com.zhenian.reader.ui.reader.fragment.reading.ReadingFragment.closeMenu(ReadingFragment.java:185)
	at com.zhenian.reader.ui.reader.fragment.reading.ReadingFragment.onSupportInvisible(ReadingFragment.java:134)
	at me.yokeyword.fragmentation.SupportFragment.dispatchSupportVisible(SupportFragment.java:390)
	at me.yokeyword.fragmentation.SupportFragment.onPause(SupportFragment.java:286)
	at com.zhenian.reader.ui.reader.fragment.reading.ReadingFragment.onPause(ReadingFragment.java:306)
	at android.support.v4.app.Fragment.performPause(Fragment.java:2363)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1354)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1523)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1585)
	at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2846)
	at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
	at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:448)
	at com.zhenian.reader.ui.reader.ReaderActivity.onPause(ReaderActivity.java:269)
	at android.app.Activity.performPause(Activity.java:5235)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1233)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3056)
	... 12 more
java.lang.NullPointerException
	at me.yokeyword.fragmentation.SupportFragment.pop(SupportFragment.java:652)
	at com.zhenian.reader.ui.reader.fragment.reading.ReadingFragment.closeMenu(ReadingFragment.java:185)
	at com.zhenian.reader.ui.reader.fragment.reading.ReadingFragment.onSupportInvisible(ReadingFragment.java:134)
	at me.yokeyword.fragmentation.SupportFragment.dispatchSupportVisible(SupportFragment.java:390)
	at me.yokeyword.fragmentation.SupportFragment.onPause(SupportFragment.java:286)
	at com.zhenian.reader.ui.reader.fragment.reading.ReadingFragment.onPause(ReadingFragment.java:306)
	at android.support.v4.app.Fragment.performPause(Fragment.java:2363)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1354)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1523)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1585)
	at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2846)
	at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
	at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:448)
	at com.zhenian.reader.ui.reader.ReaderActivity.onPause(ReaderActivity.java:269)
	at android.app.Activity.performPause(Activity.java:5235)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1233)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3056)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3025)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3003)
	at android.app.ActivityThread.access$800(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5109)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(NativeStart.java)

```

# 说明 

![exception](https://cloud.githubusercontent.com/assets/18303646/21916074/e33b394a-d978-11e6-8983-36b85fb7e8f7.png)

在 `ReadingFragment` 中的 `onSupportInvisible`会调用`closeMenu()`
```
    private void closeMenu(){
        L.e(" close menu");
        actionFrameLayout.setVisibility(View.GONE);
        if(menuFragment!=null){
            menuFragment.pop();
        }
        menuFragment = null;
    }
```

去关闭一个 `SupportFragment `，但是此时：

```
// SupportFragment.java
/**
     * 出栈
     */
    @Override
    public void pop() {
        mFragmentation.back(getFragmentManager());
    }
```
mFragmentation 为 null.

**Comment by YoKeyword** [comment]
`mFragmentation`在Fragment的`onAttach`里绑定Activity的mFragmentation， 而在Fragment的`onPause`时回调了`onSupportInvisible()`，在`onSupportInvisible()`里使用了`pop()`报了mFragmentation=null；

说明SupportActivity的`mFragmentation`被置为了null， 猜测宿主Activity已经被销毁了～

是一个必先BUG吗？ 可以复现吗～  你可以调试观察下
