### ISSUE TITLE
Fragment newInstance 不调用 setArguments, 会遇到空指针异常

### ISSUE THREAD

**Issue by senlove** [YoKeyword/Fragmentation#221]
```
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
                                                                       at me.yokeyword.fragmentation.Fragmentation.start(Fragmentation.java:258)
                                                                       at me.yokeyword.fragmentation.Fragmentation.dispatchStartTransaction(Fragmentation.java:166)
                                                                       at me.yokeyword.fragmentation.SupportActivity.start(SupportActivity.java:222)
                                                                       at me.yokeyword.fragmentation.SupportActivity.start(SupportActivity.java:217)

```

**Comment by YoKeyword** [comment]
诶？ 讲道理应该不会＝。＝

报错在Fragmentation的start()处，  getArguments()为 null了， 而start()方法只有被 `dispatchStartTransaction()`这个方法调用，  这个方法里会在 `fromFragment!=null`时调用这个`bindContainerId()` ：
````java
 private void bindContainerId(int containerId, SupportFragment to) {
        Bundle args = to.getArguments();
        if (args == null) {
            args = new Bundle();
            to.setArguments(args);
        }
        args.putInt(FRAGMENTATION_ARG_CONTAINER, containerId);
    }
````

你现在的情况是fromFragment = null了， 为null的情况只有2种：
1、 使用了`loadRootFragment()` 但是这个方法里内部也是调用了`bindContainerId()`,所以不会是这种情况
2、调用了Activity的start()方法， 但是此时getTopFragment(即fromFragment)为null

你检查下，最好能贴出调用处的代码哈～
