### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by littlezan** [YoKeyword/Fragmentation#223]
在小米手机上，在`A_Activity` 跳转 `B_Activity`后，A_Activity 会回调 `protected void onSaveInstanceState(Bundle outState)`方法，当 `B_Activity`返回`A_Activity`时，报了如下异常(小米手机必现, 其他手机不会)：
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
      at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1538)
      at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1556)
      at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
      at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
      at me.yokeyword.fragmentation.SupportFragment.processRestoreInstanceState(SupportFragment.java:112)
      at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:98)
```
是否需要在，`SupportFragment.java` 的`processRestoreInstanceState(Bundle savedInstanceState)`方法中的
`  ft.commit()` 修改呢？

**Comment by YoKeyword** [comment]
`processRestoreInstanceState()`是在`onCreate()`中回调的，说明回来时 A_Activity已经被销毁重建了，而销毁重建:
````java
private void checkStateLoss() {
        if (mStateSaved) {
            throw new IllegalStateException(
                    "Can not perform this action after onSaveInstanceState");
        }
        ...
    }
````
销毁重建的情况下 mStateSaved会被初始化为false，所以理论上不会报该异常 ＝。＝

你试下Demo会出现这个问题吗？
