### ISSUE TITLE
最新的版本，微信Demo按钮点击闪退，360Q5，6.0

### ISSUE THREAD

**Issue by BeMyWife1991** [YoKeyword/Fragmentation#232]
在FragmentationDelegate中，需屏蔽如下，否则报错：
          // for compatibility with 25.1.1
       `  fragmentManager.executePendingTransactions();`

错误如下：
 Caused by: java.lang.IllegalStateException: Fragment does not have a view
android.support.v4.app.Fragment$2.onFindViewById(Fragment.java:2154)
android.support.v4.app.FragmentTransition.configureTransitionsOptimized(FragmentTransition.java:190)
android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:111)
android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2143)
android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:762)
`me.yokeyword.fragmentation.FragmentationDelegate.loadMultipleRootTransaction(FragmentationDelegate.java:106)`
`me.yokeyword.fragmentation.SupportFragment.loadMultipleRootFragment(SupportFragment.java:538)`
`me.yokeyword.sample.demo_wechat.ui.fragment.MainFragment.onCreateView(MainFragment.java:57)`
初次留言，没什么格式，抱歉！

**Comment by BeMyWife1991** [comment]
你有说明是为了兼容安卓7.0，但是7.0手机要加上，但其它版本得去掉？

**Comment by YoKeyword** [comment]
是为了兼容support-v4: 25.1.1的版本；

我测下低版本support包下6.0手机的情况哈～ 忘记测试低版本的兼容性了～  感谢反馈

**Comment by summer0906** [comment]
`Fragment does not have a view
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                      Caused by: java.lang.IllegalStateException: Fragment does not have a view
                                                                         at android.support.v4.app.Fragment$2.onFindViewById(Fragment.java:2154)
                                                                         at android.support.v4.app.FragmentTransition.configureTransitionsOptimized(FragmentTransition.java:190)
                                                                         at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:111)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2143)
                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                                                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:762)
                                                                         at me.yokeyword.fragmentation.FragmentationDelegate.loadMultipleRootTransaction(FragmentationDelegate.java:106)
                                                                         at me.yokeyword.fragmentation.SupportFragment.loadMultipleRootFragment(SupportFragment.java:538)
                                                                         at me.yokeyword.sample.demo_wechat.ui.fragment.MainFragment.onCreateView(MainFragment.java:57)
                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                                                                         at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1228)
                                                                         at android.app.Activity.performStart(Activity.java:5991)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2433)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) `

**Comment by summer0906** [comment]
红米note3   5.0.2也会crash,网上搜了一下貌似是在onCreateView()中调用getChildFragmentManager()导致的

**Comment by BeMyWife1991** [comment]
网上确实有相关资料，但为什么是屏蔽那两句就不会闪退呢？屏蔽那两句，不是仍然要执行getChildFragmentManage()方法吗？

**Comment by YoKeyword** [comment]
`IllegalStateException: Fragment does not have a view`
报的这个异常，Demo中load代码是在Fragment的onCreateView里调用的，此时Fragment还没有View，所以Crash了；

25.1.1中没有这个问题，官方修改了机制，同时应该是这个机制导致25.1.1 在load多Fragment时会阻塞了事务队列～

我再看看源码～ 稍后给出解决方案哈

**Comment by YoKeyword** [comment]
发现是loadMultipleRootFragment加载多Fragment时设置了`.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN)`，导致会阻塞Fragment的事务队列，去掉即可解决v4-25.1.1的阻塞问题，同时25.1.1-的版本也不会影响了～

**Comment by LittleWaver** [comment]
刚出现了这个问题，mark一下
