### ISSUE TITLE
升级后 Exception 

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#233]
```loadRootFragment(R.id.fl_container, EnterFragment.newInstance());```

之前 work 的，从 0.9.5 升级到 0.10.1 后

```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhenian.training/com.zhenian.training.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.res.Resources.getAnimation(int)' on a null object reference
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2441)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2501)
      at android.app.ActivityThread.access$1000(ActivityThread.java:153)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:5462)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.res.Resources.getAnimation(int)' on a null object reference
      at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:75)
      at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:46)
      at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
      at me.yokeyword.fragmentation.SupportFragment.initAnim(SupportFragment.java:151)
      at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:126)
      at android.support.v4.app.Fragment.performCreate(Fragment.java:2177)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
      at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1080)
      at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:971)
      at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2143)
      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
      at android.app.Activity.performStart(Activity.java:6320)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2501) 
      at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:154) 
      at android.app.ActivityThread.main(ActivityThread.java:5462) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 

```

**Comment by YoKeyword** [comment]
看异常， 此时Resources对象为空，即context.getResources()为空，理论上不可能为空，是个必现的异常吗？ 什么机型系统？ 

load处的代码贴一下看看～

**Comment by zhenian** [comment]
1
```
public class BaseActivity extends SupportActivity {
    // 再点一次退出程序时间设置
    private static final long WAIT_TIME = 2000L;
    private long TOUCH_TIME = 0;

    protected View topStatusBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        PushAgent.getInstance(this).onAppStart();

        //判断当前SDK版本号，如果是4.4以上，就是支持沉浸式状态栏的
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
        }
        this.hideTopStatusBar();
    }

    protected void hideTopStatusBar(){
        try{
            topStatusBar = findViewById(R.id.top_status_bar);
        }catch (Exception e){
            e.printStackTrace();
        }
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.KITKAT && topStatusBar != null) {
            topStatusBar.setVisibility(View.GONE);
        }
    }

    /**
     * 处理回退事件
     *
     * @return
     */
    @Override
    public void onBackPressedSupport() {
        if (getSupportFragmentManager().getBackStackEntryCount() > 1) {
            pop();
        }else{
            if (System.currentTimeMillis() - TOUCH_TIME < WAIT_TIME) {
                finish();
            } else {
                TOUCH_TIME = System.currentTimeMillis();
                Toast.makeText(this, R.string.press_again_exit, Toast.LENGTH_SHORT).show();
            }
        }
    }
}

```
2
```
public class MainActivity extends BaseActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (savedInstanceState == null) {
            loadRootFragment(R.id.fl_container, EnterFragment.newInstance());
        }
    }
}
```

**Comment by zhenian** [comment]
MI 4LTE

**Comment by YoKeyword** [comment]
必现吗？ 安卓版本？  我用了6.0，5.0的机子试了下Demo，没发现问题   v4版本25.1.1 ,25.1.0均试了

Demo也有这个问题吗

**Comment by YoKeyword** [comment]
你Clean下试试， 我看了下 `loadRootFragment()`方法在0.10中与0.9.X无任何改动；  改动的是`loadMultipleRootFragment()`为了兼容25.1.1的transiation新机制～
