### ISSUE TITLE
mFragmentationDelegate为空

### ISSUE THREAD

**Issue by smarthityou** [YoKeyword/Fragmentation#251]
在继承SupportFragment的fragment中跳转到没有继承SupportActivity中处理事物后回到页面中使用start（）报空指针，打断点看到mFragmentationDelegate为空

**Comment by YoKeyword** [comment]
必现的异常吗？     异常Log提供下

mFragmentationDelegate是在Fragment绑定到宿主AC时获取的：
````java
   @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        if (activity instanceof SupportActivity) {
            this._mActivity = (SupportActivity) activity;
            mFragmentationDelegate = _mActivity.getFragmentationDelegate();
        } else {
            throw new RuntimeException(activity.toString() + "must extends SupportActivity!");
        }
    }
````

**Comment by smarthityou** [comment]
以下是日志
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=33, result=-1, data=Intent { (has extras) }} to activity {com.spkj.happyeloan/com.spkj.happyeloan.mvp.ui.activitys.MainActivity}: java.lang.NullPointerException
     at android.app.ActivityThread.deliverResults(ActivityThread.java:3778)
     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3821)
     at android.app.ActivityThread.access$1600(ActivityThread.java:151)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1410)
     at android.os.Handler.dispatchMessage(Handler.java:110)
     at android.os.Looper.loop(Looper.java:193)
     at android.app.ActivityThread.main(ActivityThread.java:5551)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
     at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
     at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:577)
     at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:572)
     at com.spkj.happyeloan.mvp.ui.fragment.MaritalStatusFragment.onActivityResult(MaritalStatusFragment.java:153)
     at com.spkj.happyeloan.mvp.ui.activitys.MainActivity.onActivityResult(MainActivity.java:87)
     at android.app.Activity.dispatchActivityResult(Activity.java:5517)
     at android.app.ActivityThread.deliverResults(ActivityThread.java:3774)
     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3821) 
     at android.app.ActivityThread.access$1600(ActivityThread.java:151) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1410) 
     at android.os.Handler.dispatchMessage(Handler.java:110) 
     at android.os.Looper.loop(Looper.java:193) 
     at android.app.ActivityThread.main(ActivityThread.java:5551) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730) 
     at dalvik.system.NativeStart.main(Native Method)
以下是fragment中代码
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (RESULT_OK == resultCode && requestCode == REQ_CODE) {
            String videoPath = data.getStringExtra(WechatRecoderActivity.VIDEO_PATH);
            KLog.i("onActivityResult: " + videoPath + "\n大小为:" + FileSizeUtil.getFileOrFilesSize(videoPath, FileSizeUtil.SIZETYPE_KB));
            start(LoanSigntureFragment.newInstance());
        }
    }
控制台打印了[ (MaritalStatusFragment.java:151)#onActivityResult ] onActivityResult: /storage/emulated/0/DCIM/WeChatJuns/1489243730624/1489243730624.mp4
                                                                                 大小为:394.03

**Comment by YoKeyword** [comment]
判断下 `data!=null` 试试 ，这个崩溃直接关系的是`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=33, result=-1, data=Intent { (has extras) }} to activity `这个异常， 后面的空指针异常是间接导致的

**Comment by smarthityou** [comment]
一样的        #
![tim 20170311231647](https://cloud.githubusercontent.com/assets/16317348/23824396/f7d708ec-06b0-11e7-8456-a8d9e422e3c0.png)

**Comment by YoKeyword** [comment]
奇怪，这个场景以前就测试通过；   刚刚我还特意试了一次打开一个非SupportAC的页面模拟你的场景，没什么问题；

你用的什么版本？

**Comment by smarthityou** [comment]
compile 'me.yokeyword:fragmentation:0.10.1'

**Comment by YoKeyword** [comment]
如何启动的第二个AC，在哪个类里启动的？

**Comment by smarthityou** [comment]
startActivityForResult  在fragment中启动的  是必现的情况

**Comment by YoKeyword** [comment]
我的目前测试结果是正常的，你可以先试下：

在Demo中随便一个Fragment中`startActivity()`一个普通AC， `setResult()`后关闭后，可以正常`start()`新Fragment。

**Comment by smarthityou** [comment]
我现在的做法是在fragment中先跳转到一个ac  然后在跳转目标ac 完了再关闭两个ac，设置setResult（）后就能正常的start到新的fragment中去

**Comment by YoKeyword** [comment]
这个异常是因为 你在AC不可见时（通常是已经调用了`onPause()`），执行了Fragment的事务方法，就会抛出该异常；

原理你可以搜下相关issue， 解决办法参照 异常提示，或者翻看issue；

PS: 虽然你现在用的临时方案解决，还是建议看下正常使用为何会报空指针异常的问题，我模拟场景后没有任何异常，你看下是否哪里场景不同～
