### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by AnkurJagani** [YoKeyword/Fragmentation#263]
`Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 1
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.set(ArrayList.java:481)
       at android.support.v4.app.FragmentManagerImpl.makeInactive(FragmentManager.java:1340)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
       at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1383)
       at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:939)
       at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1785)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:617)
       at me.yokeyword.fragmentation.Fragmentation.popToFix(Fragmentation.java:574)
       at me.yokeyword.fragmentation.Fragmentation.popTo(Fragmentation.java:548)
       at me.yokeyword.fragmentation.SupportFragment.popToChild(SupportFragment.java:490)
       at me.yokeyword.fragmentation.SupportFragment.popToChild(SupportFragment.java:474)
       at com.comnet.ekchat.MainActivity$8.onTabReselected(MainActivity.java:422)
       at com.comnet.ekchat.helper.BottomBar$1.onClick(BottomBar.java:65)
       at android.view.View.performClick(View.java:4759)
       at android.view.View$PerformClick.run(View.java:19770)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5237)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)`

How this got occur? Please let me know asap.
Thanks in advance.

**Comment by YoKeyword** [comment]
**I guess your tag is repeated : 
You use the same Fragment in different stack levels.**

### FragmentManagerImp: 
````java
 void makeInactive(Fragment f) {
        ...
        // Invalid index 4, size is 1
        // mActive: FragmentManager's fragments
        // mIndex : Index in FragmentManager's Stack
        mActives.set(f.mIndex, null);
        ...
    }
````

### E.g:
<img width="159" alt="1" src="https://cloud.githubusercontent.com/assets/9691640/24240217/c4d8250e-0feb-11e7-902c-5bf4c6042ae7.png">

**Comment by YoKeyword** [comment]
#### makeInactive(FragmentManager.java:1340):
````java
void makeInactive(Fragment f) {
       ...
       mActive.set(f.mIndex, null);
       ...
    }
````

#### E.g：
<img width="159" alt="1" src="https://cloud.githubusercontent.com/assets/9691640/24241040/81eeccae-0fee-11e7-89c9-89d90f4ce096.png">


So i guess you called `popToChild()` at the wrong stack level.

**Comment by AnkurJagani** [comment]
Thanks. i am review and trying to resolve it.
