### ISSUE TITLE
The adapter to jump to my fragment

### ISSUE THREAD

**Issue by JairDavis** [YoKeyword/Fragmentation#273]
您好，YoKeyword.
首先非常感谢您的库。
然后问一个比较初级的问题。
我又在适配器中通过view的点击事件去跳转到指定的fragment，我的做法这样的，想必有错误，希望指点一二。谢谢了。
```
                 SupportFragment supportFragment=new SupportFragment();
                 DetailFragment mDetailFragment=DetailFragment .newInstance();
                supportFragment.getTopFragment().start(DetailFragment );
```
空指针了。sorry。

**Comment by JairDavis** [comment]
04-04 16:16:40.523 4153-4153/com.jair.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.jair.android, PID: 4153
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void me.yokeyword.fragmentation.FragmentationDelegate.dispatchStartTransaction(android.support.v4.app.FragmentManager, me.yokeyword.fragmentation.SupportFragment, me.yokeyword.fragmentation.SupportFragment, int, int, int)' on a null object reference
                                                                    at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:577)
                                                                    at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:572)
                                                                    at com.jair.android.ui.home.HomeFragment.entryFragment(HomeFragment.java:373)
                                                                    at com.jair.android.adapter.HotSalePagerAdapter$1.onClick(HotSalePagerAdapter.java:74)
                                                                    at android.view.View.performClick(View.java:5646)
                                                                    at android.view.View$PerformClick.run(View.java:22450)
                                                                    at android.os.Handler.handleCallback(Handler.java:755)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:156)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)``

**Comment by YoKeyword** [comment]
>                  SupportFragment supportFragment=new SupportFragment();
                 DetailFragment mDetailFragment=DetailFragment .newInstance();
                supportFragment.getTopFragment().start(DetailFragment );

`supportFragment`是new的对象，还没有被加到FragmentManager，它的`getTopFragment()`是没意义的，返回的是Null

**Comment by JairDavis** [comment]
感谢您的回复！
是的，后来我换了一个方式，通过接口回调把方法写到fragment中去，结果还是没有获取到，希望得到您的帮助，我会进一步去看项目中的案例。
我继续看看吧。


thanks！
发自网易邮箱大师


On 04/4/2017 22:10，YoKey<notifications@github.com> wrote：
SupportFragment supportFragment=new SupportFragment();

DetailFragment mDetailFragment=DetailFragment .newInstance();
supportFragment.getTopFragment().start(DetailFragment );


supportFragment是new的对象，还没有被加到FragmentManager，它的getTopFragment()是没意义的，返回的是Null

**Comment by YoKeyword** [comment]
嗯，多看对应的Demo。

另外一说ViewPager下的Fragment是不能直接`start` Fragment的，需要用其子Fragment或者父Fragment去start，原因 #268 有提到

**Comment by JairDavis** [comment]
恩恩，，我的是在recycleview的子布局中去拿的，不知道怎么才可以比较好调用子view的fragment去跳转，我看了下代码，我把业务从fragment分离到适配器中，好多地方都得通过自定义view去跳转，苦恼了。




发自网易邮箱大师


在2017年04月4日 22:39，YoKey<notifications@github.com> 写道：

嗯，多看对应的Demo。

另外一说ViewPager下的Fragment是不能直接start Fragment的，需要用其子Fragment或者父Fragment去start，原因 #268 有提到

**Comment by YoKeyword** [comment]
建议回调的方式 或者 EventBus，  EventBus最好节制使用，管理时也注意下，避免解耦太彻底，难以维护~

**Comment by JairDavis** [comment]
前面有一个关于路由的issues，感觉他说的那种方式正是我想要的方案，再次感谢，我考虑一下eventbus好了。
Thank you for your help
