### ISSUE TITLE
replaceFragment Error

### ISSUE THREAD

**Issue by ngochuu90** [YoKeyword/Fragmentation#283]
Hi @YoKeyword 

I have a Viewpager include: Fragment A, B, C, D
A is a blank Fragment 
-> in A, `loadRootFragment(Fragment E)`
-> in E, button click to `replace(Fragment F, false);`
-> `viewpager setCurrentItem(1)`
-> `viewpager setCurrentItem(0)`. Fragment F come back
When `Fragment F` come back, both `onLazyInitView` and `onSupportVisible` are still called in E

How to replace(Fragment F), then Fragment E is removed (`onLazyInitView` and `onSupportVisible` isn't called in E)

**Comment by YoKeyword** [comment]
`loadRootFragment()` will add Fragment B to the backStack.  `replace(C,false)`'s source is `remove` B + `add` C, so it can not let B pop.

You can try `replaceLoadRootFragment(B, false);`.

**Comment by ngochuu90** [comment]
I just edited my question. 
-> viewpager setCurrentItem(1)
-> viewpager setCurrentItem(0). Fragment F come back
but  both onLazyInitView and onSupportVisible are still called in E

**Comment by ngochuu90** [comment]
I also try in "demo_zhihu":
In ZhihuFirstFragment --> `loadRootFragment(FirstHomeFragment) `--> `start FirstDetailFragment`
I edit click favButton to `replaceFragment(CycleFragment.newInstance(1), false);`

I chose tab 2, then re-selected tab 1, `onLazyInitView `and `onSupportVisible `are still called in `FirstDetailFragment`
![bug](https://cloud.githubusercontent.com/assets/9895294/24825552/9e269542-1c4a-11e7-93c7-622f2e90d649.PNG)

**Comment by YoKeyword** [comment]
`loadRootFragment()` will add Fragment E to the backStack. replace(F,false)'s source is remove E + add F, so it can not let E pop.

You can try replaceLoadRootFragment(E, false);.

**Comment by ngochuu90** [comment]
I've been tried `replaceLoadRootFragment(R.id.fl_first_container, FirstHomeFragment.newInstance(), false);`
But when I chose tab 2, then re-selected tab 1, onLazyInitViewand onSupportVisibleare still called in FirstDetailFragment

**Comment by YoKeyword** [comment]
You `replaceLoadRootFragment(FirstHomeFragment)`, then re-selected tab1, onSupportVisibleare still called in FirstDetailFragment？

How did you start FirstDetailFragment from FirstHomeFragment?

**Comment by YoKeyword** [comment]
You `replaceLoadRootFragment(FirstHomeFragment)`, then re-selected tab1, onSupportVisibleare still called in FirstDetailFragment？

How did you start FirstDetailFragment from FirstHomeFragment?

**Comment by ngochuu90** [comment]
I do not edit your demo
```
FirstDetailFragment fragment = FirstDetailFragment.newInstance(mAdapter.getItem(position));
start(fragment);
```

**Comment by YoKeyword** [comment]
This can remove E(FirstHomeFragment):
`replaceLoadRootFragment(R.id.fl_first_container, FirstHomeFragment.newInstance(), false);`
+
`replaceFragment(firstDetailFragment,false);`

**Comment by ngochuu90** [comment]
Case 1: `replaceLoadRootFragment(R.id.fl_first_container, FirstHomeFragment.newInstance(), false);`
![bug2](https://cloud.githubusercontent.com/assets/9895294/24825778/465ed01c-1c50-11e7-8382-ad28073ddaae.PNG)

Case2: When I press Back, ZhihuActivity finish, EnterActivity come back
I want to from CycleFragmentback to FirstHomeFrag

**Comment by ngochuu90** [comment]
`onLazyInitView and onSupportVisible` seem to be faulty. Because E has been replaced, they are still called

**Comment by YoKeyword** [comment]
> How to replace(Fragment F), then Fragment E is removed
`replaceLoadRootFragment(,false)` + `replaceFragment(,false)` will remove E from backStack. It is working fine in my demo.


And once the Fragment is added to the backstack, it is not allowed to mix `add` and `replace`. 
This will cause confusion of stack and backstack.

So, you can try:
````java
->A
    ->E  (A.loadRootFragment(E))
        ->F  (E.replaceRootFragment(F))
````

**Comment by ngochuu90** [comment]
I have not done it yet. For example: I want to replace FirstDetailFragment to FirstHomeFragment, and remove FirstHomeFragment

In ZhihuFirstFragment
```
    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);
        if (savedInstanceState == null) {
            loadRootFragment(R.id.fl_first_container, FirstHomeFragment.newInstance());
        }
    }
```

-In FirstHomeFragment         
```
        mAdapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(int position, View view, RecyclerView.ViewHolder vh) {
                FirstDetailFragment fragment = FirstDetailFragment.newInstance(mAdapter.getItem(position));
                replaceLoadRootFragment(R.id.fl_first_container, fragment, false);
            }
        });
```
App crash. This is Error
```
 Process: me.yokeyword.sample, PID: 25255
                                                                     java.lang.IllegalArgumentException: No view found for id 0x7f0c00c4 (me.yokeyword.sample:id/fl_first_container) for fragment FirstDetailFragment{29e0459d #0 id=0x7f0c00c4 me.yokeyword.sample.demo_zhihu.ui.fragment.first.child.FirstDetailFragment}
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1293)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                         at android.os.Handler.handleCallback(Handler.java:815)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by YoKeyword** [comment]
You use the same id(fl_first_container) at different levels.

-In FirstHomeFragment:
````java
// fl_home_container is FirstHomeFragment's FrameLayout'id
replaceLoadRootFragment(R.id.fl_home_container, fragment, false);  
````

**Comment by ngochuu90** [comment]
Thanks for you support.

I have one more question:
Original code like your demo

 **ZhihuFirstFragment** 
   --> **FirstHomeFragment** ( `ZhihuFirstFragment .loadRootFragment(R.id.fl_first_container, FirstHomeFragment.newInstance());`
      --> **FirstDetailFragment** (`FirstHomeFragment .start(FirstDetailFragment.newInstance) `)
       in **FirstDetailFragment** , click favButton, --> `replace CycleFragment to FirstHomeFragment, then FirstDetailFragment  and FirstHomeFragment remove`

**Comment by ngochuu90** [comment]
@YoKeyword

**Comment by YoKeyword** [comment]
> replace CycleFragment to FirstHomeFragment, then FirstDetailFragment and FirstHomeFragment remove.

````java
ZhihuFirstFragment.popToChild(FirstHomeFragment,true, new Runnable(
()->loadRootFragment(firstHomeFragment)
)
````

**Comment by ngochuu90** [comment]
Sorry. I wrote wrong. I want to replace FirstHomeFragment to CycleFragment

**Comment by ngochuu90** [comment]
Sorry, I wrote it wrong. I want to replace replace FirstHomeFragment to CycleFragment 
Same as: ZhihuFirstFragment .loadRootFragment(R.id.fl_first_container, CycleFragment )

In FirstDetailFragment , I call 
```
popTo(FirstHomeFragment,true, new Runnable(
   ()->loadRootFragment(firstHomeFragment)
)
```
Can you write a abstract function? From child, popTo parent, then clear backstack, and loadroot(other Fragment)

**Comment by YoKeyword** [comment]
In FirstDetailFragment:
````java
popTo(FirstHomeFragment,true, new Runnable(
   ()->loadRootFragment(cycleFragment)
)
````

or in ZhihuFirstFragment:
````java
popToChild(FirstHomeFragment,true, new Runnable(
   ()->loadRootFragment(cycleFragment)
)
````

**Comment by ngochuu90** [comment]
Thanks for your support!
