### ISSUE TITLE
用start，在activity加载另一个fragment时，偶现FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by wdeo3601** [YoKeyword/Fragmentation#293]
compile 'me.yokeyword:fragmentation:0.10.1'
compile 'me.yokeyword:fragmentation-swipeback:0.7.9'

start(SexualOrientationFragment.newInstance(), SINGLETASK);在这句跳转的时候出现的。

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quxiangtou.release/com.quxiangtou.app.modules.register.RegisterActivity}: java.lang.IllegalStateException: FragmentManager is already executing transactions
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2547)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2613)
	at android.app.ActivityThread.access$900(ActivityThread.java:180)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
	at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2007)
	at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:816)
	at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:787)
	at me.yokeyword.fragmentation.FragmentationDelegate.popToFix(FragmentationDelegate.java:573)
	at me.yokeyword.fragmentation.FragmentationDelegate.handleLaunchMode(FragmentationDelegate.java:444)
	at me.yokeyword.fragmentation.FragmentationDelegate.dispatchStartTransaction(FragmentationDelegate.java:158)
	at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:577)
	at com.quxiangtou.app.modules.register.GenderFragment.setGender(GenderFragment.java:84)
	at com.quxiangtou.app.modules.register.GenderFragment.onCheckedChanged(GenderFragment.java:71)
	at com.quxiangtou.app.modules.register.GenderFragment_ViewBinding$1.onCheckedChanged(GenderFragment_ViewBinding.java:33)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:156)
	at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:548)
	at android.view.View.dispatchRestoreInstanceState(View.java:14934)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3253)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3253)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3253)
	at android.view.View.restoreHierarchyState(View.java:14912)
	at android.support.v4.app.Fragment.restoreViewState(Fragment.java:475)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1329)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
	at android.app.Activity.performStart(Activity.java:6304)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2510)
	... 9 more

**Comment by YoKeyword** [comment]
场景再稍微详细描述下， 异常提示是：
GenderFragment的'setGender()'里调用了`start()`， 首先先排查是否是栈层级问题，有没有使用ViewPager？

如果一切正常：
该异常是`transactions`冲突引起的，所以可以这么简单处理：
````java
事务1执行；
getFragmentManager().executePendingTransactions();
事务2执行；
````
或者
````java
事务1执行；
handle.post(()->事务2执行；)
````

**Comment by wdeo3601** [comment]
@YoKeyword 这个crash我是在bugtags上看到的，目前无法复现。 GenderFragment依附的avtivity没有viewpager。  该activity是分别依次start4个fragment，fragmentA->fragmentB->GenderFragment->fragmentD。

**Comment by YoKeyword** [comment]
你找下异常代码附近，start(SINGLETASK)上下代码看下是否有操作事务，如果有，用上述2种解决方法

计划未来库会对连续的事务做一个安全处理，可以不用担心这个问题

**Comment by wdeo3601** [comment]
@YoKeyword  异常代码附近没有操作事务，GenderFragment里边代码很简单，两个选项的单选，不管选中哪一个，都执行start( SINGLETASK)，在start之前用eventbus把一个值传到activity中赋值给其中的变量，这是这块的全部逻辑了，有点诡异

**Comment by YoKeyword** [comment]
@wdeo3601  你测下，会不会是快速连续点击引起的

**Comment by wdeo3601** [comment]
@YoKeyword 找到原因了，因为那几个fragment都有中radiobutton都有状态监听，当fragment被系统回收，再次进入时，会触发状态监听重新start多个fragment，目前已根据onSupportInvisible()、onSupportVisible()方法去处理radiobutton监听事件的绑定与解绑

**Comment by YoKeyword** [comment]
也可以判断处理下，在回收重启后，不去start；   
````java
if(findFragment(homeFragment)==null){
    // start
}
````
