### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by chordw** [YoKeyword/Fragmentation#299]
## java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1538)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1556)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
	at me.yokeyword.fragmentation.Fragmentation.showHideFragment(Fragmentation.java:195)
	at me.yokeyword.fragmentation.SupportFragment.showHideFragment(SupportFragment.java:364)
	at com.uu393.market.module.MainFragment$1.onTabSelected(MainFragment.java:109)
	at com.uu393.market.view.bottombar.BottomBar$1.onClick(BottomBar.java:70)
	at android.view.View.performClick(View.java:5273)
	at android.view.View$PerformClick.run(View.java:21315)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5643)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

**Comment by chordw** [comment]
### 查了一下解决办法：
onSaveInstanceState方法是在该Activity即将被销毁前调用，来保存Activity数据的，如果在保存玩状态后
再给它添加Fragment就会出错。解决办法就是把commit（）方法替换成 commitAllowingStateLoss()就行
了，其效果是一样的。

**上面的说法对吗？？？ 求解**

**Comment by chordw** [comment]
不好意思，我依赖的版本是0.7的，刚刚看到0.8版本中已经解决了，，好尴尬

**Comment by YoKeyword** [comment]
额，解决就好；  但是正确的处理方式还是避免在 onSaveInstance之后去执行事务， 我的简书里有简单的介绍 :)
