### ISSUE TITLE
异常：SupportActivity的dispatchTouchEvent异常导致了软键盘显示不正常

### ISSUE THREAD

**Issue by lizhaoXXX** [YoKeyword/Fragmentation#340]
W/InputMethodManager: IME died: com.android.inputmethod.latin/.LatinIME
                                                                                    android.os.DeadObjectException
                                                                                        at android.os.BinderProxy.transactNative(Native Method)
                                                                                        at android.os.BinderProxy.transact(Binder.java:503)
                                                                                        at com.android.internal.view.IInputMethodSession$Stub$Proxy.viewClicked(IInputMethodSession.java:232)
                                                                                        at android.view.inputmethod.InputMethodManager.viewClicked(InputMethodManager.java:1543)
                                                                                        at android.widget.TextView.viewClicked(TextView.java:9661)
                                                                                        at android.widget.TextView.onTouchEvent(TextView.java:8348)
                                                                                        at android.view.View.dispatchTouchEvent(View.java:9294)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                                        at me.yokeyword.fragmentation.SupportActivity.dispatchTouchEvent(SupportActivity.java:362)
                                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                        at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                                    	at android.view.ViewRootImpl.enqueueInputE

**Comment by YoKeyword** [comment]
库中源码：
````java
 @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (!mFragmentClickable) return true;
        return super.dispatchTouchEvent(ev);
    }
````
错误指向362行，即：return super.dispatchTouchEvent(ev);
所以`if`判断没有走进去，相当于这个方法没做任何事即发生该异常，应该和库的`dispatchTouchEvent`没关系。

你看下何种操作引起该异常
