### ISSUE TITLE
使用中统计出来的错误

### ISSUE THREAD

**Issue by N-Richard** [YoKeyword/Fragmentation#350]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxxx/com.xxx.xxxx.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 7, size is 2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5524)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 7, size is 2
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManagerImpl.java:2775)
	at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:158)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:328)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:88)
	at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:54)
	at com.xxx.xxxx.MainActivity.onCreate(MainActivity.java)
	at android.app.Activity.performCreate(Activity.java:6303)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
	... 9 more
java.lang.IndexOutOfBoundsException: Invalid index 7, size is 2
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManagerImpl.java:2775)
	at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:158)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:328)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:88)
	at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:54)
	at com.xxx.xxxx.MainActivity.onCreate(MainActivity.java)
	at android.app.Activity.performCreate(Activity.java:6303)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5524)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

**Comment by YoKeyword** [comment]
你使用哪个版本的support-v4？    有人怀疑这个是v4包的BUG ，
 看这里https://issuetracker.google.com/issues/36936138

**Comment by N-Richard** [comment]
囧，我打不开他
我用了v7:25.1.0，有什么办法呢...

**Comment by YoKeyword** [comment]
可以考虑升级下v4包， 另外一说今天释放了v1.0.0，建议使用 🍺 :)
