### ISSUE TITLE
java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#364]
```
 java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)
     at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:1930)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3967)
     at android.view.View.draw(View.java:18929)
     at android.view.View.updateDisplayListIfDirty(View.java:17876)
     at android.view.View.draw(View.java:18654)
     at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3970)
     at android.view.View.draw(View.java:18929)
     at android.view.View.updateDisplayListIfDirty(View.java:17876)
     at android.view.View.draw(View.java:18654)
     at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
     at me.yokeyword.fragmentation.SwipeBackLayout.drawChild(SwipeBackLayout.java:199)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3970)
     at android.view.View.draw(View.java:18929)
     at android.view.View.updateDisplayListIfDirty(View.java:17876)
     at android.view.View.draw(View.java:18654)
     at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3994)
     at android.view.View.updateDisplayListIfDirty(View.java:17867)
     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4168)
     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4148)
     at android.view.View.updateDisplayListIfDirty(View.java:17835)
     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4168)
     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4148)
     at android.view.View.updateDisplayListIfDirty(View.java:17835)
     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4168)
     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4148)
     at android.view.View.updateDisplayListIfDirty(View.java:17835)
     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4168)
     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4148)
     at android.view.View.updateDisplayListIfDirty(View.java:17835)
     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4168)
     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4148)
     at android.view.View.updateDisplayListIfDirty(View.java:17835)
     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:636)
     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:642)
     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:750)
     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2968)
     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2782)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2346)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1385)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6722)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
     at android.view.Choreographer.doCallbacks(Choreographer.java:698)
     at android.view.Choreographer.doFrame(Choreographer.java:633)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
     at android.os.Handler.handleCallback(Handler.java:769)
     at android.os.Handler.dispatchMessage(Handler.java:98)
     at android.os.Looper.loop(Looper.java:164)
     at android.app.ActivityThread.main(ActivityThread.java:6540)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
使用`android.support.v4.widget.SwipeRefreshLayout` refresh状态下按返回键退出，就会报这个错。

**Comment by weiyf** [comment]
应该是别的库引起的， 先检查原因，close掉
