### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by KeqingLI** [YoKeyword/Fragmentation#394]
1 、 使用 _mActivity.popTo(MainFragment.class, false);

```
CustomCrashHandler: java.lang.NoSuchFieldError: No instance field mAvailIndices of type Ljava/util/ArrayList; in class Landroid/support/v4/app/FragmentManagerImpl; or its superclasses (declaration of 'android.support.v4.app.FragmentManagerImpl' appears in /data/app/com.dongqiu.dqk.dev-1/split_lib_dependencies_apk.apk:classes36.dex)
                                                                           at android.support.v4.app.FragmentTransactionBugFixHack.reorderIndices(FragmentTransactionBugFixHack.java:16)
                                                                           at me.yokeyword.fragmentation.FragmentationDelegate$3.run(FragmentationDelegate.java:602)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

2、1.0.3 自己实现SwipebackFragment时 使用SwipebackLayout有用到SupportFragmentDelegate.mLockAnim  请提供访问权限或方法

**Comment by KeqingLI** [comment]
不好意思  问题一在 support25.3.0没有问题   25.4.0时就会产生问题

**Comment by YoKeyword** [comment]
第1个问题用了1.0.3的包还存在吗？

第2个问题 应该是目前代码:
````java
 public void attachToFragment(SwipeBackFragment swipeBackFragment, View view) {
        addView(view);
        setFragment(swipeBackFragment, view);
    }
````

使用了SwipeBackFragment，导致你不能直接用SwipeBackLayout，今天放出1.0.4会修复该问题，同时给出 SwipeBackDelegate，来方便定制 :)

**Comment by KeqingLI** [comment]
第一个问题应该是我用了低版本库的问题 1.0.3改动比较大 暂时还未引入项目中 

另外想问下大佬对于FragmentStatePagerAdapter和FragmentPagerAdapter的区别和用法 
我之前使用FragmentPagerAdapter 产生了类似 #384 的问题，之前通过改库的方式解决，想问下如果我全部采用FragmentStatePagerAdapter会不会产生其他问题

**Comment by YoKeyword** [comment]
1.0之前的版本不支持25.4.0，google终于在25.4.0修复了出栈可能导致栈顺序错误的BUG...

https://github.com/YoKeyword/Fragmentation/issues/384问题的原因是v1.0 `onLazyInitView`在`onCreateView`之前调用了，v1.0.3已经修复了

FragmentStatePagerAdapter建议用在数据量大、多，不易释放视图内存的场景 :)

**Comment by YoKeyword** [comment]
v1.0.4已放出，SwipeBack库多余引用问题移除了， 同时提供了Interface + Delegate  🍺
