### ISSUE TITLE
更新 1.0.4 后出现的问题

### ISSUE THREAD

**Issue by glassweichao** [YoKeyword/Fragmentation#403]
更新1.0.4后，在nexus 5x ， 三星 S4 S5等机型上可以正常使用。在oppo vivo 等机型上有报错。以下是log，有遇到过此类情况吗？看log是v4包找不到文件？
07-03 15:23:54.953 20382-20382/? E/System: java.lang.NoSuchFieldError: No field mActive of type Landroid/util/SparseArray; in class Landroid/support/v4/app/ab; or its superclasses (declaration of 'android.support.v4.app.ab' appears in /data/app/com.yeahka.android.jinjianbao-1/base.apk)
                                               at android.support.v4.app.bg.c(Unknown Source)
                                               at me.yokeyword.fragmentation.i.a(Unknown Source)
                                               at me.yokeyword.fragmentation.SupportActivity.a(Unknown Source)
                                               at com.yeahka.android.jinjianbao.core.SpMainActivity.onCreate(Unknown Source)
                                               at android.app.Activity.performCreate(Activity.java:6935)
                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2764)
                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2872)
                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:186)
                                               at android.app.ActivityThread.main(ActivityThread.java:6477)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)

**Comment by YoKeyword** [comment]
该异常出现原因如下：  25.4.0 mActive的类型改变了
````java
public static List<Fragment> getActiveFragments(FragmentManager fragmentManager) {
        if (!(fragmentManager instanceof FragmentManagerImpl))
            return Collections.EMPTY_LIST;
        // For pre-25.4.0
        if (sSupportLessThan25dot4) return fragmentManager.getFragments();

        // For compat 25.4.0+
        try {
            FragmentManagerImpl fragmentManagerImpl = (FragmentManagerImpl) fragmentManager;
            // Since v4-25.4.0，mActive: ArrayList -> SparseArray
            return getActiveList(fragmentManagerImpl.mActive);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return fragmentManager.getFragments();
    }
````

兼容问题，我等下测试

**Comment by YoKeyword** [comment]
@glassweichao 我用了oppo R9没复现  

Fragmentation是作为gradle依赖的，还是Module依赖的？ 
如果是Module依赖的，编译环境需要至少v4版本25.4.0，如果是gradle依赖v4版本无要求

**Comment by glassweichao** [comment]
是作为gradle依赖的。

**Comment by YoKeyword** [comment]
@glassweichao OK 我这边oppo没有复现，  加我QQ：328903522看下吧  :)

**Comment by YoKeyword** [comment]
已解决， 混淆问题，添加混淆规则即可：
`-keep class * extends android.support.v4.app.FragmentManager{ *; }`

**Comment by huangchaoqingcheng** [comment]
我也出现了 gradle依赖的
