### ISSUE TITLE
android5.0以下不能成功运行

### ISSUE THREAD

**Issue by RoyXing** [YoKeyword/Fragmentation#406]
` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lecai/com.lecai.activity.MainActivity}: java.lang.IllegalStateException: No host
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:193)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5318)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.IllegalStateException: No host
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1273)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2138)
                                                       at android.support.v4.app.Fragment.onCreate(Fragment.java:1254)
                                                       at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:47)
                                                       at com.yxt.base.frame.base.BaseFragment2.onCreate(BaseFragment2.java:72)
                                                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2062)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1051)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:585)
                                                       at me.yokeyword.fragmentation.TransactionDelegate.supportCommit(TransactionDelegate.java:254)
                                                       at me.yokeyword.fragmentation.TransactionDelegate.loadMultipleRootTransaction(TransactionDelegate.java:89)
                                                       at me.yokeyword.fragmentation.SupportActivityDelegate.loadMultipleRootFragment(SupportActivityDelegate.java:187)
                                                       at me.yokeyword.fragmentation.SupportActivity.loadMultipleRootFragment(SupportActivity.java:132)
                                                       at com.lecai.activity.MainActivity.setFragment(MainActivity.java:219)
                                                       at com.lecai.activity.MainActivity.onCreate(MainActivity.java:94)
                                                       at android.app.Activity.performCreate(Activity.java:5354)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                       at android.os.Looper.loop(Looper.java:193) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5318) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
                                                       at dalvik.system.NativeStart.main(Native Method) `
 使用loadMultipleRootFragment()方法加载 不能进入app

**Comment by YoKeyword** [comment]
@RoyXing 
使用1.0后，在onCreate()/ onCreateView()中加载Fragment的事务（比如loadRootFragment()），请迁移到onViewCreated()或者onActivityCreated()中 :)

**Comment by RoyXing** [comment]
@YoKeyword loadMultipleRootFragment()这个方法是在Activity中调用的的没有onViewCreated()或者onActivityCreated()方法哎，Activity中只有onCreateView()方法呢

**Comment by YoKeyword** [comment]
哦哦，`com.yxt.base.frame.base.BaseFragment2.onCreate(BaseFragment2.java:72) at `
异常指向的这一行附近的代码贴一下

**Comment by RoyXing** [comment]
@YoKeyword `    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (!EventBus.getDefault().isRegistered(this))
            EventBus.getDefault().register(this);
        Alert.getInstance().init(mbContext);
    }`
指向的是onCreate的super方法

**Comment by YoKeyword** [comment]
`com.lecai.activity.MainActivity.setFragment(MainActivity.java:219) at `
这里代码也贴一下 :)

**Comment by RoyXing** [comment]
`  private void setFragment() {

        int size = getBottomInfo().size();
        mFragments = new SupportFragment[size];

        if (findFragment(MyInfoFragment.class) == null) {
            bottomNavigationBar.selectTab(0);
            for (int i = 0; i < size; i++) {
                tagTmp = getBottomInfo().get(i).getCode();
                switch (tagTmp) {
                    case "message":
                        mFragments[i] = messageFragment = MessageFragment.newInstance();
                        break;
                    case "meeting":
                        mFragments[i] = meetingFragment = MeetingFragment.newInstance();
                        break;
                    case "index":
                        mFragments[i] = studyFragment = StudyFragment.newInstance();
                        break;
                    case "my":
                        mFragments[i] = myInfoFragment = MyInfoFragment.newInstance();
                        break;
                }
            }

            switch (size) {
                case 0:
                    finish();
                    break;
                case 1:
                    loadMultipleRootFragment(R.id.ui_container, FIRST, mFragments[FIRST]);
                    break;
                case 2:
                    loadMultipleRootFragment(R.id.ui_container, FIRST, mFragments[FIRST], mFragments[SECOND]);
                    break;
                case 3:
                    loadMultipleRootFragment(R.id.ui_container, FIRST, mFragments[FIRST], mFragments[SECOND], mFragments[THIRD]);
                    break;
                case 4:
                    loadMultipleRootFragment(R.id.ui_container, FIRST, mFragments[FIRST], mFragments[SECOND], mFragments[THIRD], mFragments[FOURTH]);
                    break;
            }

        } else {

            for (int i = 0; i < size; i++) {
                tagTmp = getBottomInfo().get(i).getCode();

                switch (tagTmp) {
                    case "message":
                        mFragments[i] = messageFragment = findFragment(MessageFragment.class);
                        break;
                    case "meeting":
                        mFragments[i] = meetingFragment = findFragment(MeetingFragment.class);
                        break;
                    case "index":
                        mFragments[i] = studyFragment = findFragment(StudyFragment.class);
                        break;
                    case "my":
                        mFragments[i] = myInfoFragment = findFragment(MyInfoFragment.class);
                        break;
                }

                ISupportFragment topFragment = getTopFragment();
                if (topFragment == mFragments[i]) {
                    bottomNavigationBar.selectTab(i);
                }
            }
        }
    }`
这里要动态判断加载几个fragment

**Comment by YoKeyword** [comment]
这台手机运行Demo是否有问题？

该异常是在Fragment `onCreate`时，Fragment没找到宿主Activity

**Comment by RoyXing** [comment]
@YoKeyword 运行demo没有问题的，但是在5.0以上的机型上运行 也是没有问题的

**Comment by YoKeyword** [comment]
你把 `setFragment()`放到 post(runnable)里执行下，试试

**Comment by RoyXing** [comment]
@YoKeyword ` new Handler().post(new Runnable() {
            @Override
            public void run() {
                setFragment();
            }
        });`
是这样么，不行哎

**Comment by YoKeyword** [comment]
这样还不行的话，我觉的可能是写法问题；和Demo再比较下

我搜了下这个异常，没有特别准确的答案，有说和内存泄漏有关系，有说和层级有关系...

你可以在你异常的Fragment里调试下`onAttach()`,`onCreate()`，看在执行`onCreate()`时是否已经绑定了宿主（`onAttach()`）

**Comment by RoyXing** [comment]
@YoKeyword 好的 打扰这么久 谢谢了 我再排查排查问题

**Comment by YoKeyword** [comment]
@RoyXing  #140 有相同问题，这位小伙伴也是在Base里操作了Context，他移除后正常了 :)

**Comment by RoyXing** [comment]
@YoKeyword 我自己写了几个直接继承SupportFragment的fragment，里面什么逻辑都没有 用loadMultipleRootFragment()加载也是不对的 好奇怪。

**Comment by YoKeyword** [comment]
简化环境，不要动态加载`loadMultipleRootFragment ()`， 直接在`onCreate`里`load`，模拟Demo环境试试，毕竟Demo没问题感觉很奇怪...

**Comment by RoyXing** [comment]
恩 好 晚上试试 今天我试着自己去控制hide和show是可以的 但是里面封装的懒加载不能懒加载了

**Comment by yygutn** [comment]
我今天试了一下，在Activity.OnCreate 使用 LoadM...Fragment也是报No  Host错。。。迷
Fragment就是在OnViewCreated显示一个text

**Comment by YoKeyword** [comment]
@RoyXing @yygutn  你们在使用什么版本的v4包？  

我查了下，这是在某些v4版本上的存在的BUG：
https://issuetracker.google.com/issues/37079910

**Comment by RoyXing** [comment]
@YoKeyword 我这边是24的版本

**Comment by yygutn** [comment]
@YoKeyword  我使用的是23.3.0的包

**Comment by YoKeyword** [comment]
无法复现...  @yygutn 
> 我就写的是一个Demo，，，，Activity和Fragment什么都没有。。。

你的Demo可以发我邮箱，我排查下吗？  报下出现问题的手机系统版本

**Comment by yygutn** [comment]
@YoKeyword  额。。。我是用Xamarin开发的。。。
我打过Log看过生命周期，attach/oncreate都很正常，但就是会有NO HOST异常，loadmultirootfragment我也参照transactionDelegation重写过，流程都没问题。。。断点没发现null问题
后来使用25.3.1版本的的V4/V7就可以正常使用了

**Comment by YoKeyword** [comment]
@yygutn   有个google issue是有提到可能是某个v4版本的BUG，这个问题后续再观察下，做下兼容

**Comment by yygutn** [comment]
@YoKeyword  嗯呢~持续关注

**Comment by YoKeyword** [comment]
@yygutn @RoyXing 
v1.0.9，优化了事务机制，理论上有更强的兼容性， 可以试下

**Comment by RoyXing** [comment]
@YoKeyword 好的 辛苦大神了
