### ISSUE TITLE
关于Fragment already added:的问题

### ISSUE THREAD

**Issue by guangshao** [YoKeyword/Fragmentation#426]
java.lang.IllegalStateException: Fragment already added: CustomizeTaskFragment_{931c09f #3 id=0x7f0f0085 net.skywalkerhong.yangdun.ui.fragment.IndexFragment.CustomizeTaskFragment_}
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1679)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:727)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

请问有什么办法防止出现这样的问题??

**Comment by YoKeyword** [comment]
重复add同一个Fragment实例到栈内了，

**Comment by YoKeyword** [comment]
重复add同一个Fragment实例到栈内了，简单处理方式：
````java
if(!fragment.isAdded()){
     // todo       
}
````

**Comment by guangshao** [comment]
谢谢 大大
