### ISSUE TITLE
发现 Attempt to read from field 'int android.support.v4.app.Fragment.mContainerId' on a null object reference这样的问题

### ISSUE THREAD

**Issue by guangshao** [YoKeyword/Fragmentation#434]
java.lang.NullPointerException: Attempt to read from field 'int android.support.v4.app.Fragment.mContainerId' on a null object reference
	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1017)
	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:976)
	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

请问一下这是什么情况引起的

**Comment by YoKeyword** [comment]
> java.lang.NullPointerException: Attempt to read from field 'int android.support.v4.app.Fragment.mContainerId' on a null object reference

此时Fragment为Null， 可以排查下为何Fragment为Null还在执行事务

**Comment by guangshao** [comment]
这个是友盟统计那边的反馈 , 我还不知道是哪个fragment为null 。

**Comment by sinawangnan7** [comment]
我也遇到这个问题了，我用的是腾讯Bugly，抛出异常的场景是后台状态。

**Comment by YoKeyword** [comment]
@sinawangnan7 
升级v4版本到至少25.4.0或以上（v26、v27）， 应该可以解决这个问题

**Comment by YoKeyword** [comment]
升级v4版本到26+，可应该可以解决该问题

> PS : 另外尽可能使用较新的Fragmentation版本
