### ISSUE TITLE
在onSupportVisible()直接start(fragment)会报错

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#461]
java.lang.IllegalStateException: FragmentManager is already executing transactions
                                                 at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
                                                 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2007)
                                                 at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
                                                 at me.yokeyword.fragmentation.TransactionDelegate.supportCommit(TransactionDelegate.java:257)
                                                 at me.yokeyword.fragmentation.TransactionDelegate.start(TransactionDelegate.java:219)
                                                 at me.yokeyword.fragmentation.TransactionDelegate.dispatchStartTransaction(TransactionDelegate.java:144)
                                                 at me.yokeyword.fragmentation.SupportFragmentDelegate.start(SupportFragmentDelegate.java:398)
                                                 at me.yokeyword.fragmentation.SupportFragmentDelegate.start(SupportFragmentDelegate.java:391)
                                                 at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:310)

加一个Handler改成如下就不会报错了，这个是什么原因？

`    @Override
    public void onSupportVisible() {
        super.onSupportVisible();
        new Handler().post(new Runnable() {
            @Override
            public void run() {
                start(SetupMenuFragment.newInstance());
            }
        });
    }`

**Comment by zhangz89** [comment]
使用的是1.0.7版本

**Comment by YoKeyword** [comment]
从`v4-25.3.0`开始， 官方不允许在任何生命周期内使用`fm.executePendingTransactions()` （官方真是够了），而库从1.0之后，各个事务都`fm.executePendingTransactions()`， 解决方式是：放到post里执行

不过我晚上会把`fm.executePendingTransactions()`的方式移除，来避免这个问题

**Comment by YoKeyword** [comment]
v1.0.9已放出， 取消`executePendingTransactions()`机制，同时做了判断，能更好的避免该异常

这个之前没问题是因为v4-25.3.0之前是可以在生命周期内执行事务的，但是25.3.0后，google在**每个**生命周期里都禁止直接`executePendingTransactions`，😂:
````java
 // FragmentManager.java:
 public void dispatchResume() {
        mStateSaved = false;
        mExecutingActions = true;  // true...
        moveToState(Fragment.RESUMED, false); // 这里调用 onResume()
        mExecutingActions = false;
}
````
