### ISSUE TITLE
clearAccessibilityFocus() on a null object reference

### ISSUE THREAD

**Issue by lelouch0823** [YoKeyword/Fragmentation#465]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.missf.life, PID: 4104
                                                              java.lang.RuntimeException: Unable to pause activity {com.missf.life/com.missf.life.mvp.home.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference
                                                                  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
                                                                  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
                                                                  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
                                                                  at android.app.ActivityThread.-wrap13(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference
                                                                  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4594)
                                                                  at android.view.ViewGroup.removeViewAt(ViewGroup.java:4552)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                  at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2997)
                                                                  at android.support.v4.app.Fragment.performPause(Fragment.java:2429)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1398)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                  at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2997)
                                                                  at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:225)
                                                                  at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:448)
                                                                  at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onPause(RxAppCompatActivity.java:81)
                                                                  at android.app.Activity.performPause(Activity.java:6348)
                                                                  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
                                                                  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
                                                                  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340) 
                                                                  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315) 
                                                                  at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `
我这有个问题想请教下,出现在这样的嵌套下MainActivity-MainFragment-ViewPager-4个Fragment,当ViewPager内Fragment切换过在切换回来(不切换无问题)以后启动任意Activity会出现该错误.

**Comment by LonelyMushroom** [comment]
@lelouch0823 请提供下v4包版本,以及lib的版本

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/359 跟这位老兄问题有点相似

**Comment by lelouch0823** [comment]
@LonelyMushroom 你好,support-v4:25.4.0 fragmentation:1.0.9

**Comment by YoKeyword** [comment]
@lelouch0823 
我模拟了场景：  第一个Demo的`MainActivity`加载`ViewPagerFragment`，其中的子Fragment：`FirstPagerFragment`点击启动`EnterActivity`

根据你的描述操作，我没有复现；  你可以用Demo试试

**Comment by lelouch0823** [comment]
@LonelyMushroom @YoKeyword 谢谢,尝试了更换基类Activity和Fragment都不行,最后把FragmentStatePagerAdapter换成FragmentPagerAdapter就没问题了...
