### ISSUE TITLE
在Activity里面start()调用Fragment出错

### ISSUE THREAD

**Issue by jaysowen** [YoKeyword/Fragmentation#480]
我在activity里面调用出错,activity跟demo一样是继承的BaseBackFragment.
找遍了google都没有合适的答案特来求解.我试过了在点击事件里面执行intent调用activity没有问题
错误如下:
 UncaughtException detected: java.lang.IllegalArgumentException: Must use non-zero containerViewId
                                                                    at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:427)
                                                                    at me.yokeyword.fragmentation.TransactionDelegate.start(TransactionDelegate.java:198)
                                                                    at me.yokeyword.fragmentation.TransactionDelegate.dispatchStartTransaction(TransactionDelegate.java:141)
                                                                    at me.yokeyword.fragmentation.SupportActivityDelegate.start(SupportActivityDelegate.java:220)
                                                                    at me.yokeyword.fragmentation.SupportActivityDelegate.start(SupportActivityDelegate.java:213)
                                                                    at me.yokeyword.fragmentation.SupportActivity.start(SupportActivity.java:158)
                                                                    at app.autoclub.bmw.module.community.ui.TimelineAddActivity.chooseTag(TimelineAddActivity.java:135)
                                                                    at app.autoclub.bmw.module.community.ui.TimelineAddActivity_ViewBinding$1.doClick(TimelineAddActivity_ViewBinding.java:43)
                                                                    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                    at android.view.View.performClick(View.java:5637)
                                                                    at android.view.View$PerformClick.run(View.java:22429)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

08-04 00:10:08.771 22456-22456/app.autoclub.bmw E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: app.autoclub.bmw, PID: 22456
                                                                  java.lang.IllegalArgumentException: Must use non-zero containerViewId
                                                                      at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:427)
                                                                      at me.yokeyword.fragmentation.TransactionDelegate.start(TransactionDelegate.java:198)
                                                                      at me.yokeyword.fragmentation.TransactionDelegate.dispatchStartTransaction(TransactionDelegate.java:141)
                                                                      at me.yokeyword.fragmentation.SupportActivityDelegate.start(SupportActivityDelegate.java:220)
                                                                      at me.yokeyword.fragmentation.SupportActivityDelegate.start(SupportActivityDelegate.java:213)
                                                                      at me.yokeyword.fragmentation.SupportActivity.start(SupportActivity.java:158)
                                                                      at app.autoclub.bmw.module.community.ui.TimelineAddActivity.chooseTag(TimelineAddActivity.java:135)
                                                                      at app.autoclub.bmw.module.community.ui.TimelineAddActivity_ViewBinding$1.doClick(TimelineAddActivity_ViewBinding.java:43)
                                                                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                      at android.view.View.performClick(View.java:5637)
                                                                      at android.view.View$PerformClick.run(View.java:22429)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by jaysowen** [comment]
冒似是因为我在activity里面没有loadRootFragment()导致的?

**Comment by YoKeyword** [comment]
@jaysowen 是的，在`start()`前确保 有`loadRootFragment()`，因为`start`时依赖load时设置的containerId

**Comment by guptapayal03** [comment]
java.lang.IllegalArgumentException: Must use non-zero containerViewId
Got this error while redirecting a fragment from an activity using 
 ApplicationContentPage applicationContentPage=ApplicationContentPage.newInstance();
 start(applicationContentPage);
