### ISSUE TITLE
关于开启fragment的问题.

### ISSUE THREAD

**Issue by colder112** [YoKeyword/Fragmentation#492]
/**
     * 加载会话页面 ConversationFragment
     *
     * @param mConversationType 会话类型
     * @param mTargetId 目标 Id
     */
    @SuppressLint("DefaultLocale")
    private void enterFragment(Conversation.ConversationType mConversationType, String mTargetId) {
        ConversationFragment fragment = (ConversationFragment) getSupportFragmentManager().findFragmentById(R.id.conversation);
        Uri uri = Uri.parse("rong://" + getApplicationInfo().packageName).buildUpon()
                .appendPath("conversation").appendPath(mConversationType.getName().toLowerCase())
                .appendQueryParameter("targetId", mTargetId).build();
        fragment.setUri(uri);
    }
我在融云聊天ChatRomActivity(以继承SupportActivity)中载入的fragment的是融云的,并不是supportFragment,而在ChatRomActivity中使用start()开启新的fragment,就报错了.
java.lang.IllegalArgumentException: Must use non-zero containerViewId
                                                                     at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:427)
                                                                     at me.yokeyword.fragmentation.TransactionDelegate.start(TransactionDelegate.java:203)
                                                                     at me.yokeyword.fragmentation.TransactionDelegate.dispatchStartTransaction(TransactionDelegate.java:144)
                                                                     at me.yokeyword.fragmentation.SupportActivityDelegate.start(SupportActivityDelegate.java:220)
                                                                     at me.yokeyword.fragmentation.SupportActivityDelegate.start(SupportActivityDelegate.java:213)
                                                                     at me.yokeyword.fragmentation.SupportActivity.start(SupportActivity.java:155)
                                                                     at com.siwu.paimeetandroid.ui.ChatRoomActivity.startChatRomBrother(ChatRoomActivity.java:103)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                     at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
                                                                     at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
                                                                     at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
                                                                     at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                     at com.siwu.paimeetandroid.ui.RongCloudEvent$11.onResponse(RongCloudEvent.java:563)
                                                                     at com.siwu.paimeetandroid.ui.RongCloudEvent$11.onResponse(RongCloudEvent.java:550)
                                                                     at com.zhy.http.okhttp.OkHttpUtils$3.run(OkHttpUtils.java:186)
                                                                     at android.os.Handler.handleCallback(Handler.java:743)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:150)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by colder112** [comment]
可不可以不跳转到mainActivity中开启fragment,我想在ChatRomActivity中开启fragment

**Comment by YoKeyword** [comment]
1、可以创建一个继承`SupportFragment`的ContainerFragment， 然后把ConversationFragment作为它的子Fragment加载 （一种简单的方式在xml使用<fragment/>标签加载）

2、第二种方案可能更适合你，ConversationFragment放到普通的Activity里，直接`startActivity`就可以了

**Comment by colder112** [comment]
我就是想在chatromactivity中开启一个新栈,.在这个新栈中开启fragment,不然的话,我在ConversationFragment搞交互,跳转的话难道要startactivity(MainActiivty) 然后再start(Fragment)么
您说得第一种方法,是不是创建一个ContainerFragment的view,在xml中引用它.还是说new ContainerFragment() ,在ContainerFragment中使用代码去加载ConversationFragment,我有点晕晕的

**Comment by colder112** [comment]
<fragment
        android:id="@+id/conversation"
        android:name="io.rong.imkit.fragment.ConversationFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
这个是chatromActivity的布局
 <activity
            android:name=".ui.ChatRoomActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateHidden|adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>

                <category android:name="android.intent.category.DEFAULT"/>

                <data
                    android:host="com.siwu.paimeetandroid"
                    android:pathPrefix="/conversation/"
                    android:scheme="rong"/>
            </intent-filter>
        </activity>
这个是清单文件配置,
我想知道,这个直接在xml的fragment更换成你的supportFragment,还是说在新创建一个supportfragment塞进这个fragment中,然后再把ConversationFragment塞到新创建的supportfragment中

**Comment by YoKeyword** [comment]
对于非SupportFragment可以通过： 作为子Fragment放到SupportFragment的父Fragment里来 曲线变成 "SupportFragment"

即创建一个继承SuppotFragment的父Fragment，布局里： <fragment name="ConversationFragment"/>， 这样`start(父Fragment)`即启动了ConversationFragment
