### ISSUE TITLE
version 1.0.9

### ISSUE THREAD

**Issue by rooho** [YoKeyword/Fragmentation#498]
java.lang.IllegalStateException: Fragment has not been attached yet.
	at android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java)
	at android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java)
	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.dispatchSupportVisible(VisibleDelegate.java)
	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.access$000(VisibleDelegate.java)
	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate$1.run(VisibleDelegate.java)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5739)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/488
