### ISSUE TITLE
IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1 version 1.0.9

### ISSUE THREAD

**Issue by rooho** [YoKeyword/Fragmentation#499]
java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2122)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
	at me.yokeyword.fragmentation.SupportActivity.dispatchTouchEvent(SupportActivity.java)
	at com.hlg.xsbapp.context.base.XBaseActivity.dispatchTouchEvent(XBaseActivity.java)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
	at android.view.View.dispatchPointerEvent(View.java:10228)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4845)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4705)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4384)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4441)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6665)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6639)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6600)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6792)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:330)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by LonelyMushroom** [comment]
八成是多点触控的问题，要不你关闭下试试？
```
<item name="android:splitMotionEvents">false</item>
```

**Comment by rooho** [comment]
不太确定是哪个页面报出的，不好排查问题。

**Comment by YoKeyword** [comment]
@rooho  这个和库没关系，应该是些 多点触控或者埋点等三方库引起的， try-catch 忽略处理即可

**Comment by rooho** [comment]
好🙏
