### ISSUE TITLE
java.lang.IllegalStateException: mDelegate.onCreateAnimat…transit, enter, nextAnim) must not be null

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#500]
报错：java.lang.IllegalStateException: mDelegate.onCreateAnimat…transit, enter, nextAnim) must not be null
版本：
Fragmentation: v1.1.1
support: v26.0.0

**Comment by YoKeyword** [comment]
@weiyf   有更详细的日志吗？
我搜了下库的代码和 v4包的源码，没有找到相关异常提示

**Comment by weiyf** [comment]
```
Process: *******, PID: 25663
java.lang.RuntimeException: Unable to start activity ComponentInfo{*******/*******.ui.activity.MainActivity}: java.lang.IllegalStateException: mDelegate.onCreateAnimat…transit, enter, nextAnim) must not be null
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.IllegalStateException: mDelegate.onCreateAnimat…transit, enter, nextAnim) must not be null
at *******.base.BaseCompatFragment.onCreateAnimation(BaseCompatFragment.kt:77)
at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1125)
at android.support.v4.app.FragmentManagerImpl.completeShowHideFragment(FragmentManager.java:1671)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1778)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2358)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
at *******.base.BaseCompatActivity.onStart(BaseCompatActivity.kt:66)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
at android.app.Activity.performStart(Activity.java:6992)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
at android.app.ActivityThread.-wrap11(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6541) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by YoKeyword** [comment]
我看到你使用了kotlin， Log提示： `mDelegate.onCreateAnimatiton() must not be null`， 我对kotlin不是很熟，但是我猜测是kotlin的写法问题

**Comment by weiyf** [comment]
一言惊醒啊，Animation忘了加?了

**Comment by Simon1121** [comment]
> 一言惊醒啊，Animation忘了加?了
@weiyf 
能请教一下为什么要加？号吗。我也碰到这个问题，只是想不明白为什么

**Comment by Hell-And** [comment]
> > 一言惊醒啊，Animation忘了加?了
> > @weiyf
> > 能请教一下为什么要加？号吗。我也碰到这个问题，只是想不明白为什么

我也刚碰到了类似的问题，看到这里的回复解决了，我猜应该是与kotlin安全检查有关，kotlin中不可以明目张胆的返回null，加？可以跳过空检查，加!! 碰到null会报空指针异常

**Comment by cjcj125125** [comment]
我也是同样的问题，请教如何解决呢？

**Comment by esirong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
