### ISSUE TITLE
从RootFragment启动到另一个rootfragment报错

### ISSUE THREAD

**Issue by SirZhao** [YoKeyword/Fragmentation#504]
首先启动loadRootFragment(R.id.fl_content,GuideFragment.class),然后再GuideFragment中点击按钮启动loadRootFragment(R.id.fl_content,LoginFragment.class，false,false)，就会报如下错误

java.lang.IllegalArgumentException: No view found for id 0x7f0e007e (com.zdd.project:id/fl_content) for fragment LoginFragment{37462c6 #0 id=0x7f0e007e com.zdd.project.fragment.account.LoginFragment}
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1293)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                             at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                             at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by YoKeyword** [comment]
应该使用`start(LoginFragment)`

load方法是开启一个子栈，并把根Fragment加载进来， `start`是在当前栈内启动新Fragment，即打开一个兄弟Fragment

**Comment by SirZhao** [comment]
第一次把guide根加载进来，然后我想把这个根替换掉，加载另一个根，开启新的子栈

**Comment by SirZhao** [comment]
@YoKeyword 老版本替换根fragment就是LoadRootFragment的

**Comment by YoKeyword** [comment]
@SirZhao `loadRootFragment()`会把Fragment加入回退栈，并不能真正的替换

替换的话 使用`guide.startWithPop(LoginFragment)`即可

**Comment by SirZhao** [comment]
多谢
