### ISSUE TITLE
java.lang.IndexOutOfBoundsException   super.drawChild(canvas, child, drawingTime);

### ISSUE THREAD

**Issue by Gundam0079** [YoKeyword/Fragmentation#506]
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:411)
	at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
	at android.widget.ListView.dispatchDraw(ListView.java:3412)
	at android.view.View.draw(View.java:17137)
	at android.widget.AbsListView.draw(AbsListView.java:4320)
	at android.view.View.updateDisplayListIfDirty(View.java:16116)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17137)
	at android.view.View.updateDisplayListIfDirty(View.java:16116)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17137)
	at android.view.View.updateDisplayListIfDirty(View.java:16116)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17137)
	at android.view.View.updateDisplayListIfDirty(View.java:16116)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17137)
	at android.view.View.updateDisplayListIfDirty(View.java:16116)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at me.yokeyword.fragmentation.f.drawChild(SwipeBackLayout.java:243)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17137)
	at android.view.View.updateDisplayListIfDirty(View.java:16116)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.updateDisplayListIfDirty(View.java:16111)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.updateDisplayListIfDirty(View.java:16111)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.updateDisplayListIfDirty(View.java:16111)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.updateDisplayListIfDirty(View.java:16111)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.updateDisplayListIfDirty(View.java:16111)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.updateDisplayListIfDirty(View.java:16111)
	at android.view.View.draw(View.java:16900)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17137)
	at com.android.internal.policy.DecorView.draw(DecorView.java:751)
	at android.view.View.updateDisplayListIfDirty(View.java:16116)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2830)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2638)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2245)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6396)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:619)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6209)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

跟
https://github.com/YoKeyword/Fragmentation/issues/263 
这个应该是一个问题

**Comment by YoKeyword** [comment]
@Gundam0079    从你的Log上来看和Fragment没有什么关系， 是ListView在dispatchDraw时 数组越界了，排查下相关代码吧

**Comment by Gundam0079** [comment]
找了到了问题 是自己疏忽  这是个listviewheader引发的错误
重写HeaderViewListAdapter 的dispatchDraw 解决了  谢谢支持
