### ISSUE TITLE
[其他问题]System.err: java.lang.IllegalArgumentException: Wrong state class

### ISSUE THREAD

**Issue by 1021454107** [YoKeyword/Fragmentation#51]
业务逻辑比较麻烦，viewPager + Fragment 顶部的导航条根据返回的数据动态添加。
总共三种类型，就分了三个Fragment。在 ViewPagerAdapter  getItem中用newInstance(id)来获取，id不相同。
RecyclerView 在不同的Fragment里面是用的不同的id的，在OnCreateView里面 initView(view)初始化。
在 OnDestroyView() 里 mRecy_news.getRefreshableView().setAdapter(null);
但是在左右滑动的时候出现了下面的错误代码，并且闪退。

 E/InputEventReceiver: Exception dispatching input event.
 E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.RecyclerView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/fragmetn_own_pager_rv. Make sure other views do not use the same id.
                                                                    at android.view.View.onRestoreInstanceState(View.java:13810)
                                                                    at com.handmark.pulltorefresh.library.PullToRefreshBase.onRestoreInstanceState(PullToRefreshBase.java:833)
                                                                    at android.view.View.dispatchRestoreInstanceState(View.java:13786)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2889)
                                                                    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2897)
                                                                    at android.view.View.restoreHierarchyState(View.java:13764)
                                                                    at android.support.v4.app.Fragment.restoreViewState(Fragment.java:465)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
                                                                    at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1430)
                                                                    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:732)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                    at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                    at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2050)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2390)
                                                                    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1734)
                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2830)
                                                                    at me.yokeyword.fragmentation.SupportActivity.dispatchTouchEvent(SupportActivity.java:240)
                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2351)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)

搜索了很久，试验了重写ViewPager捕捉异常，view判断为空复用，判断Recycler状态再初始化，都没用。

**Comment by YoKeyword** [comment]
@1021454107 
我看了下，从异常信息来看是，id重复引用了~  但是因为你是ViewPager滑动必这样，而不是页面重启情况下会发生，那可能和onRestoreInstanceState有些关系，我看到你下面的代码：
`
com.handmark.pulltorefresh.library.PullToRefreshBase.onRestoreInstanceState(PullToRefreshBase.java:833)
`
你是否使用了自定义RecyclerView？ 它的onRetoreInstanceState是否有问题？

**Comment by 1021454107** [comment]
@YoKeyword 
tk，换成普通的RecyclerView就没有问题了，看来是PullToRefreshBase那里有问题。
这里的话，如果想用PullToRefresh的话？ 应该怎么处理？ 因为项目需要上拉和下拉刷新，还有自定义动画，其余的地方都是使用的这个类，如果要换成别的话。可能比较麻烦。
或者我试一下ListView或者ScrollView。

	@Override
	protected final void onRestoreInstanceState(Parcelable state) {
		if (state instanceof Bundle) {
			Bundle bundle = (Bundle) state;

			setMode(Mode.mapIntToValue(bundle.getInt(STATE_MODE, 0)));
			mCurrentMode = Mode.mapIntToValue(bundle.getInt(STATE_CURRENT_MODE, 0));
			mScrollingWhileRefreshingEnabled = bundle.getBoolean(STATE_SCROLLING_REFRESHING_ENABLED, false);
			mShowViewWhileRefreshing = bundle.getBoolean(STATE_SHOW_REFRESHING_VIEW, true);

			// Let super Restore Itself
			super.onRestoreInstanceState(bundle.getParcelable(STATE_SUPER));

			State viewState = State.mapIntToValue(bundle.getInt(STATE_STATE, 0));
			if (viewState == State.REFRESHING || viewState == State.MANUAL_REFRESHING) {
				setState(viewState, true);
			}

			// Now let derivative classes restore their state
			onPtrRestoreInstanceState(bundle);
			return;
		}

		super.onRestoreInstanceState(state);
	}

**Comment by YoKeyword** [comment]
@1021454107 不好解决的话 可以考虑换个其他的库，有条件自己封装下也是可以的～ 看需求选择～

**Comment by 1021454107** [comment]
@YoKeyword 谢了，原因找到了就好说点，我再试试就好，不过现在赶着上线新功能没时间研究了，先用别的顶上去。
还有个Pdf阅读翻屏，底部ViewPager+Fragment ，还带聊天的需求。心累...
