### ISSUE TITLE
发现一个空指针的bug

### ISSUE THREAD

**Issue by Gundam0079** [YoKeyword/Fragmentation#523]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4368)
	at android.view.ViewGroup.removeViewAt(ViewGroup.java:4330)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1540)
	at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
	at me.yokeyword.fragmentation.i$c.onViewPositionChanged(SwipeBackLayout.java:445)
	at android.support.v4.widget.ViewDragHelper.continueSettling(ViewDragHelper.java:740)
	at me.yokeyword.fragmentation.i.computeScroll(SwipeBackLayout.java:295)
	at android.view.View.updateDisplayListIfDirty(View.java:14428)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3511)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3511)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3511)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3511)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3511)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3511)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3031)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2844)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2428)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1331)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6792)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:804)
	at android.view.Choreographer.doCallbacks(Choreographer.java:607)
	at android.view.Choreographer.doFrame(Choreographer.java:576)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:790)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5911)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by YoKeyword** [comment]
在Fragment中，这个空指针问题很常见，原因大多是层级出现异常导致

贴下 异常发生前的栈视图，以及库的版本，v4版本
