### ISSUE TITLE
一个空指针

### ISSUE THREAD

**Issue by Gundam0079** [YoKeyword/Fragmentation#524]
ava.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4595)
	at android.view.ViewGroup.removeViewAt(ViewGroup.java:4553)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1540)
	at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:823)
	at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
	at me.yokeyword.fragmentation.j.c(TransactionDelegate.java:254)
	at me.yokeyword.fragmentation.j.b(TransactionDelegate.java:245)
	at me.yokeyword.fragmentation.j.a(TransactionDelegate.java:139)
	at me.yokeyword.fragmentation.g.c(SupportFragmentDelegate.java:429)
	at me.yokeyword.fragmentation.SupportFragment.c(SupportFragment.java:335)

**Comment by YoKeyword** [comment]
在Fragment中，这个空指针问题很常见，原因大多是层级出现异常导致，这个问题本质和你提的 #523 一样，我关闭这个issue，在 #523 里讨论该问题
