### ISSUE TITLE
BottomBar Crashed !

### ISSUE THREAD

**Issue by hjw541988478** [YoKeyword/Fragmentation#544]
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setSelected(boolean)' on a null object reference
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at com.ssjj.recorder.widget.bottombar.BottomBar.onRestoreInstanceState(BottomBar.java:131)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.view.View.dispatchRestoreInstanceState(View.java:15032)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3247)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3253)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.view.View.restoreHierarchyState(View.java:15010)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v4.app.Fragment.restoreViewState(Fragment.java:475)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1329)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v4.app.ac.i(FragmentController.java:201)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at com.example.test.HomeActivity.onStart(HomeActivity.java:190)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1268)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.app.Activity.performStart(Activity.java:6378)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
09-06 16:45:12.202 E/AndroidRuntime(25907): 	... 9 more
```

**Comment by YoKeyword** [comment]
看Log，崩溃的代码:
````java
 @Override
    protected void onRestoreInstanceState(Parcelable state) {
        SavedState ss = (SavedState) state;
        super.onRestoreInstanceState(ss.getSuperState());

        if (mCurrentPosition != ss.position) { // 下面的child为Null
            mTabLayout.getChildAt(mCurrentPosition).setSelected(false);
            mTabLayout.getChildAt(ss.position).setSelected(true);
        }
        mCurrentPosition = ss.position;
    }
````

在恢复时崩溃了，这个`BottomBar` 我司项目也在用，一直很稳定，没出现过Crash的问题

你的BottomBar是否有改动过？ 或者Items的数量是否有动态的改变？

虽然加个不为null的判断可以解决问题，但是如果能复现的话，建议调试下解决

**Comment by ywp0919** [comment]
我这里小米MIX2把应用放在后台，过久了再返回这个应用超大的几率复现这个BottomBar.onRestoreInstanceState方法里面的空指针异常。

**Comment by YoKeyword** [comment]
@ywp0919 很好去复现，打开 开发者模式 -> 不保留活动， 试试，目前Demo是很稳定的

**Comment by ywp0919** [comment]
ok,谢谢

**Comment by ywp0919** [comment]
@YoKeyword 大佬 ，这个问题现在在不保留活动的情况下百分百复现。我用的是1.1.0的版本，一升级1.3.0就异常了，所以这个项目还没有升级，现在这个空指针的我用判断null的方式处理的话又会出现一个新的异常。java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.setNextAnim(int)' on a null object reference。项目里面的onSaveInstanceState()这些方法我都没有重写，是继承你的Support类。 可以请问这种情况我要怎么处理吗

**Comment by ywp0919** [comment]
大佬 ，这个问题是我的锅，已经排查了，现在的问题是我如果升级 1.3.0版本的话请问需要调整哪些代码呢，直接升级是有报了异常，现在又退回来了

**Comment by hegaojian** [comment]
@ywp0919 请问你是怎么解决的呢？我也碰到这个问题了

**Comment by ywp0919** [comment]
@hegaojian 检查一下首页的加载写法有没有问题，我是之前首页那块对多fragment的写法有问题导致的，然后打开 开发者模式 -> 不保留活动， 多跑一跑找找原因看看

**Comment by YoKeyword** [comment]
@ywp0919 1.3.0加了队列机制，新增`startWithPopTo()`，其他基本没区别，参考下[wikiChangeLog](https://github.com/YoKeyword/Fragmentation/wiki)

另外异常可以贴下
