### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'me.yokeyword.fragmentation.TransactionDelegate me.yokeyword.fragmentation.SupportActivityDelegate.getTransactionDelegate()' on a null object reference

### ISSUE THREAD

**Issue by liwk** [YoKeyword/Fragmentation#566]
java.lang.NullPointerException: Attempt to invoke virtual method 'me.yokeyword.fragmentation.TransactionDelegate me.yokeyword.fragmentation.SupportActivityDelegate.getTransactionDelegate()' on a null object reference
                                                                           at me.yokeyword.fragmentation.SupportFragmentDelegate.onAttach(SupportFragmentDelegate.java:79)
                                                                           at me.yokeyword.fragmentation.SupportFragment.onAttach(SupportFragment.java:41)
                                                                           at android.support.v4.app.Fragment.onAttach(Fragment.java:1222)
                                                                           at com.qct.qianchengtong.base.BaseSimpleFragment.onAttach(BaseSimpleFragment.java:28)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1231)
                                                                           at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
                                                                           at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:976)
                                                                           at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                           at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                           at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                           at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                           at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                           at android.view.View.measure(View.java:19734)
                                                                           at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                           at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                           at android.view.View.measure(View.java:19734)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                           at android.view.View.measure(View.java:19734)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                           at android.view.View.measure(View.java:19734)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at android.view.View.measure(View.java:19734)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                           at android.view.View.measure(View.java:19734)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                                           at android.view.View.measure(View.java:19734)
                                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
                                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1358)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)

**Comment by YoKeyword** [comment]
Fragmentation版本？  v4版本？ 场景？

看Log是`SupportActivityDelegate`为null，看下面源码mDelegate不可能为空，你用的是自己实现的`SupportActivity`?
````java
public class SupportActivity extends AppCompatActivity implements ISupportActivity {
    final SupportActivityDelegate mDelegate = new SupportActivityDelegate(this);

    @Override
    public SupportActivityDelegate getSupportDelegate() {
        return mDelegate;
    }
}
````
