### ISSUE TITLE
线上统计发现一个bug，是手势冲突么？

### ISSUE THREAD

**Issue by kuangzhe** [YoKeyword/Fragmentation#582]
出错最多机型小米Note | 出错最多系统Android 6.0 | 累计错误次数1 | 累计影响用户数1 | 修复状态未修复

下面是我的主题
 <style name="AppTheme" parent="android:Theme.Light">
        
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        
        <item name="android:splitMotionEvents">false</item>
        
        <item name="android:windowIsTranslucent">true</item>
    </style>

我的当前版本是：
// 如果想使用SwipeBack 滑动边缘退出Fragment/Activity功能，完整的添加规则如下：
    compile 'me.yokeyword:fragmentation:1.1.4'
    // swipeback基于fragmentation, 如果是自定制SupportActivity/Fragment，则参照SwipeBackActivity/Fragment实现即可
    compile 'me.yokeyword:fragmentation-swipeback:1.1.4'

报错日志：

java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2089)
	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
	at android.support.v4.widget.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1145)
	at me.yokeyword.fragmentation.SwipeBackLayout.onTouchEvent(SwipeBackLayout.java:520)
	at android.view.View.dispatchTouchEvent(View.java:9314)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2556)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2874)
	at com.ldcang.framework.SupportActivity.dispatchTouchEvent(SupportActivity.java:66)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
	at android.view.View.dispatchPointerEvent(View.java:9536)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4281)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4144)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3683)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3736)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3702)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3710)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3885)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3683)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3736)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3702)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3710)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3683)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5973)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5947)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5908)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6079)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:195)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6047)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6102)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:602)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:743)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)

**Comment by LonelyMushroom** [comment]
你改动下SwipeBackLayout.java的代码,改成下面这个样子试下.
```
    @Override
    public boolean onTouchEvent(MotionEvent event) {
    	try {
            if (!mEnable) return super.onTouchEvent(event);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        try {
            mHelper.processTouchEvent(event);
            return true;
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }
```
要是没问题了记得告诉下我哟...

**Comment by YoKeyword** [comment]
对的，根据经验，各种手势相关的库都有可能产生这个异常，因为频率很低，所以处理方式一般是在基类里 try-catch

下个版本会对SwipeBackLayout里的`onTouchEvent`,`onInterceptTouchEvent`里内置try-catch处理
