### ISSUE TITLE
"mActive"   NoSuchFieldError  

### ISSUE THREAD

**Issue by SirZhao** [YoKeyword/Fragmentation#609]
25.0.3升级至26.0.2  25.3.1升级到25.4.0之后出现
java.lang.NoSuchFieldError: No field mActive of type Ljava/util/ArrayList; in class Landroid/support/v4/app/FragmentManagerImpl; or its superclasses (declaration of 'android.support.v4.app.FragmentManagerImpl' appears in /data/app/com.pakage.name-ODkc-GZrzL7FPZ337xYeHQ==/split_lib_dependencies_apk.apk)
                                                         at android.support.v4.app.FragmentationHack.getActiveFragments(FragmentationHack.java:90)
                                                         at SupportHelper.getActiveFragment(SupportHelper.java:158)
                                                         at SupportHelper.getActiveFragment(SupportHelper.java:130)
                                                     at SupportActivityDelegate.onBackPressed(SupportActivityDelegate.java:143)

**Comment by YoKeyword** [comment]
Fragmentation版本提供下， 此外类似issue： #368
