### ISSUE TITLE
这个错误是因为什么呢？

### ISSUE THREAD

**Issue by andy91310** [YoKeyword/Fragmentation#619]
`Caused by: android.content.res.Resources$NotFoundException: File res/anim/h_fragment_exit.xml from xml type anim resource ID #0x7f050012
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:3743)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:3690)
	at android.content.res.Resources.getAnimation(Resources.java:2165)
	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:71)
	at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initExitAnim(AnimatorHelper.java:75)
	at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:30)
	at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
	at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:108)
	at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)
	at com.ftt.app.ui.fragment.BaseMvpFragment.onCreate(BaseMvpFragment.java:18)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2369)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
	at android.app.Activity.performStart(Activity.java:5321)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
	... 11 more`

**Comment by YoKeyword** [comment]
描述下发生异常的环境

偶现还是必现？ 线上环境还是开发环境？

**Comment by andy91310** [comment]
线上环境呢，目前只发现一个在三星4.4.4的手机上。

**Comment by YoKeyword** [comment]
如果发生在开发环境，一般clean下即可；

你的情况是只发生在线上该机型，并只有一次的话，可以忽略， 毕竟Android系统也会抽风 ＝，＝
