### ISSUE TITLE
Resource ID Not Found

### ISSUE THREAD

**Issue by asan855** [YoKeyword/Fragmentation#621]
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f050038
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:204)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2585)
	at android.content.res.Resources.getAnimation(Resources.java:1167)
	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:75)
	at me.yokeyword.fragmentation.helper.internal.a.f(AnimatorHelper.java:93)
	at me.yokeyword.fragmentation.helper.internal.a.a(AnimatorHelper.java:32)
	at me.yokeyword.fragmentation.helper.internal.a.<init>(AnimatorHelper.java:24)
	at me.yokeyword.fragmentation.e.a(SupportFragmentDelegate.java:101)
	at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)
	at me.yokeyword.fragmentation_swipeback.SwipeBackFragment.onCreate(SwipeBackFragment.java:24)

**Comment by asan855** [comment]
1.0.8

**Comment by LonelyMushroom** [comment]
你是不是哪里资源有问题.话说,要不你clean一下?

**Comment by asan855** [comment]
线上的包，崩溃日志看到的，仔细看了想代码就是加载一个xml文件，没想通是哪里问题

**Comment by LonelyMushroom** [comment]
你仔细找找代码吧,看看是不是哪里资源用错了.

**Comment by YoKeyword** [comment]
#619
