### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by jincheng0902** [YoKeyword/Fragmentation#654]
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                              at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1888)
                                                                              at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1910)
                                                                              at android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:785)
                                                                              at me.yokeyword.fragmentation.SupportFragmentDelegate.popTo(SupportFragmentDelegate.java:473)
                                                                              at me.yokeyword.fragmentation.SupportFragment.popTo(SupportFragment.java:359)
                                                                              at com.emnet.hairuishopping.fragment.PayOrderFragment$WebChatBroastCast.onReceive(PayOrderFragment.java:325)
                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1222)
                                                                              at android.os.Handler.handleCallback(Handler.java:761) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                              at android.os.Looper.loop(Looper.java:156) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6577) 
                                                                              at java.lang.reflect.Method.invoke(Native Method)

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/522

**Comment by jincheng0902** [comment]
多谢，已解决
