### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Shenrangege520** [YoKeyword/Fragmentation#657]
me.yokeyword.fragmentation.SwipeBackLayout.drawChild(SwipeBackLayout.java:247)
Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
为何会出现这样一个空指针？

**Comment by YoKeyword** [comment]
提供：
* Fragmentation version
* support-v4 version
* 完整Log

**Comment by Shenrangege520** [comment]
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3340)
	at android.view.View.draw(View.java:15571)
	at android.view.View.updateDisplayListIfDirty(View.java:14448)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at android.view.View.draw(View.java:15571)
	at android.view.View.updateDisplayListIfDirty(View.java:14448)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at me.yokeyword.fragmentation.SwipeBackLayout.drawChild(SwipeBackLayout.java:247)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at android.view.View.draw(View.java:15571)
	at android.widget.FrameLayout.draw(FrameLayout.java:658)
	at android.view.View.updateDisplayListIfDirty(View.java:14448)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3353)
	at android.view.View.updateDisplayListIfDirty(View.java:14440)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at android.view.View.updateDisplayListIfDirty(View.java:14440)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at android.view.View.updateDisplayListIfDirty(View.java:14440)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at android.view.View.updateDisplayListIfDirty(View.java:14440)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at android.view.View.updateDisplayListIfDirty(View.java:14440)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at android.view.View.updateDisplayListIfDirty(View.java:14440)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.View.draw(View.java:15268)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3548)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3341)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2847)
	at android.view.View.draw(View.java:15571)
	at android.widget.FrameLayout.draw(FrameLayout.java:658)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2826)
	at android.view.View.updateDisplayListIfDirty(View.java:14448)
	at android.view.View.getDisplayList(View.java:14477)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3031)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2844)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2428)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1331)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6792)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:804)
	at android.view.Choreographer.doCallbacks(Choreographer.java:607)
	at android.view.Choreographer.doFrame(Choreographer.java:576)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:790)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5929)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
Fragmentation version 1.1.8
com.android.support:support-v4:25.3.0

**Comment by YoKeyword** [comment]
> at me.yokeyword.fragmentation.SwipeBackLayout.drawChild(SwipeBackLayout.java:247)

对应源码 : `super.drawChild(canvas, child, drawingTime)`

应该和库无关，你再排查下

另外是开发过程必先的bug 还是线上统计到的？
