### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Shenrangege520** [YoKeyword/Fragmentation#658]
ava.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)
	at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:1772)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3549)
	at android.view.View.draw(View.java:17099)
	at android.view.View.updateDisplayListIfDirty(View.java:16078)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.draw(View.java:17099)
	at android.view.View.updateDisplayListIfDirty(View.java:16078)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at me.yokeyword.fragmentation.SwipeBackLayout.drawChild(SwipeBackLayout.java:247)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.draw(View.java:17099)
	at android.view.View.updateDisplayListIfDirty(View.java:16078)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3576)
	at android.view.View.updateDisplayListIfDirty(View.java:16073)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.updateDisplayListIfDirty(View.java:16073)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.updateDisplayListIfDirty(View.java:16073)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.updateDisplayListIfDirty(View.java:16073)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.updateDisplayListIfDirty(View.java:16073)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.updateDisplayListIfDirty(View.java:16073)
	at android.view.View.draw(View.java:16862)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3766)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.draw(View.java:17099)
	at com.android.internal.policy.DecorView.draw(DecorView.java:754)
	at android.view.View.updateDisplayListIfDirty(View.java:16078)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2842)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2257)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6368)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
	at android.view.Choreographer.doCallbacks(Choreographer.java:685)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by YoKeyword** [comment]
> at me.yokeyword.fragmentation.SwipeBackLayout.drawChild(SwipeBackLayout.java:247)

对应源码 : `super.drawChild(canvas, child, drawingTime)`

应该和库无关，你再排查下

另外是开发过程必先的bug 还是线上统计到的？
