### ISSUE TITLE
调用loadMultipleRootFragment（）黑屏问题

### ISSUE THREAD

**Issue by jackandroid2016** [YoKeyword/Fragmentation#672]
if (savedInstanceState == null) {
            mFragments[Consulting] = ConsultingFragment.newInstance();
            mFragments[LiveStream] = LiveStreamFragment.newInstance();
            mFragments[Events] = EventsFragment.newInstance();
            mFragments[My] = MyFragment.newInstance();

            **loadMultipleRootFragment(R.id.fl_container, Consulting,
                    mFragments[Consulting],
                    mFragments[LiveStream],
                    mFragments[Events],
                    mFragments[My]);**
        } else {
            mFragments[Consulting] = findFragment(ConsultingFragment.class);
            mFragments[LiveStream] = findFragment(LiveStreamFragment.class);
            mFragments[Events] = findFragment(EventsFragment.class);
            mFragments[My] = findFragment(MyFragment.class);
        }

加上这句就黑屏

**Comment by jackandroid2016** [comment]
Process: zl.test.tablayoutdemo, PID: 15939
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{zl.test.tablayoutdemo/zl.test.tablayoutdemo.MainActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f080054 (zl.test.tablayoutdemo:id/fl_container) for fragment EventConsultFragment{6eb877a #0 id=0x7f080054 zl.test.tablayoutdemo.EventConsultFragment}
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                           at android.os.Looper.loop(Looper.java:156)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                        Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f080054 (zl.test.tablayoutdemo:id/fl_container) for fragment EventConsultFragment{6eb877a #0 id=0x7f080054 zl.test.tablayoutdemo.EventConsultFragment}
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1413)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                                                                           at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2369)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                                                                           at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                           at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
                                                                           at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                           at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
                                                                           at android.app.Activity.performStart(Activity.java:6930)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                           at android.os.Looper.loop(Looper.java:156) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by YoKeyword** [comment]
> java.lang.IllegalArgumentException: No view found for id 0x7f080054 (zl.test.tablayoutdemo:id/fl_container) for fragment EventConsultFragment{6eb877a #0 id=0x7f080054 zl.test.tablayoutdemo.EventConsultFragment}

Log提示比较明确，可以排查下相关代码
