### ISSUE TITLE
线上bug

### ISSUE THREAD

**Issue by andy91310** [YoKeyword/Fragmentation#680]
- java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
	at android.util.ArrayMap.allocArrays(ArrayMap.java:187)
	at android.util.ArrayMap.put(ArrayMap.java:459)
	at android.os.BaseBundle.putInt(BaseBundle.java:383)
	at me.yokeyword.fragmentation.TransactionDelegate.bindContainerId(TransactionDelegate.java:226)
	at me.yokeyword.fragmentation.TransactionDelegate.loadRootTransaction(TransactionDelegate.java:72)
	at me.yokeyword.fragmentation.SupportActivityDelegate.loadRootFragment(SupportActivityDelegate.java:180)
	at me.yokeyword.fragmentation.SupportActivityDelegate.loadRootFragment(SupportActivityDelegate.java:176)
	at me.yokeyword.fragmentation.SupportActivity.loadRootFragment(SupportActivity.java:121)
	at com.ftt.app.ui.activity.MainActivity.setupViews(MainActivity.java:60)
	at com.ftt.app.ui.activity.BaseActivity.onCreate(BaseActivity.java:31)
	at android.app.Activity.performCreate(Activity.java:6324)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2556)
	at android.app.ActivityThread.access$1200(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5645)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

这个错误是线上友盟统计里报出来的，影响的用户有点多
setupViews()方法里就这一句loadRootFragment(R.id.fl_container, MainFragment.newInstance());
MainFragment里面Bundle也没有传参数
求大神们帮忙分析下呢。

**Comment by YoKeyword** [comment]
告知下 support-v4 版本，该异常是Bundle内部扩容时引起的Exception，我目前还没遇到过。
另外可以分析下 影响用户的系统机型等

目前看起来是Google的BUG： [AOSP Issue 218944](https://code.google.com/p/android/issues/detail?id=218944)

**Comment by andy91310** [comment]
support-v4:26.1.0是这个版本。大部分是7.0的。
