### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by xiaoerMr** [YoKeyword/Fragmentation#688]
Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                         at android.view.ViewGroup.addViewInner(ViewGroup.java:3880)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:3733)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:3678)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:3654)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                                                                         at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
                                                                         at android.app.Activity.performStart(Activity.java:5949)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 

-------
 if (savedInstanceState == null) {
            mFragments[FIRST]  = Num1Fragment.newInstance();
            mFragments[SECOND] = Num2Fragment.newInstance();
            mFragments[THIRD]  = Num3Fragment.newInstance();
            mFragments[FOURTH] = Num4Fragment.newInstance();

            loadMultipleRootFragment(R.id.fl_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD],
                    mFragments[FOURTH]);
        }else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题
            // 这里我们需要拿到mFragments的引用,也可以通过getSupportFragmentManager.getFragments()
            // 自行进行判断查找(效率更高些),用下面的方法查找更方便些
            mFragments[FIRST] = findFragment(Num1Fragment.class);
            mFragments[SECOND] = findFragment(Num2Fragment.class);
            mFragments[THIRD] = findFragment(Num3Fragment.class);
            mFragments[FOURTH] = findFragment(Num4Fragment.class);
        }

**Comment by xiaoerMr** [comment]
loadMultipleRootFragment 注释掉就不报错了,这是为啥?

**Comment by YoKeyword** [comment]
该异常原因是 在添加某个子View的时候，该子View已经被添加到某个父ViewGroup上了，导致的异常

提供v4版本和库版本

先检查下上下文代码，建议在clone Demo工程测试下

**Comment by luteng123** [comment]
你好，我也遇到这个IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first. 查看log日志，发生在SupportActivity的 startWithPop(ISupportFragment toFragment)。 v4包是25.3.1.  fragmentation库是fragmentation-swipeback:1.1.1'

**Comment by luteng123** [comment]
1Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
2    at android.view.ViewGroup.addViewInner(ViewGroup.java:4471)
3    at android.view.ViewGroup.addView(ViewGroup.java:4312)
4    at android.view.ViewGroup.addView(ViewGroup.java:4252)
5    at android.view.ViewGroup.addView(ViewGroup.java:4225)
6    at me.yokeyword.fragmentation.j.a(TransactionDelegate.java:646)
7    at me.yokeyword.fragmentation.j.a(TransactionDelegate.java:533)
8    at me.yokeyword.fragmentation.j.c(TransactionDelegate.java:257)
9    at me.yokeyword.fragmentation.j.b(TransactionDelegate.java:249)
10    at me.yokeyword.fragmentation.j.a(TransactionDelegate.java:142)
11    at me.yokeyword.fragmentation.f.c(SupportActivityDelegate.java:234)
12    at me.yokeyword.fragmentation.SupportActivity.c(SupportActivity.java:183)

**Comment by YoKeyword** [comment]
@luteng123 建议先升级到1.2.x，1.2.x新增队列机制，在极端情况下依然稳定

**Comment by luteng123** [comment]
感谢作者回复，应该是我这边问题 addview出现的问题，还有个问题，我在pop完了 getPreFragment会不会出现空指针一场？

**Comment by luteng123** [comment]
比如我在一个方法  同时调用supportFragment pop();和getPreFragment 会不会报空指针，我使用的fragmentation库是1.1.1，期待作者回复

**Comment by YoKeyword** [comment]
为了健壮性，这种情况建议对`getPreFragment()`判空处理下
