### ISSUE TITLE
clearAccessibilityFocus() on a null object reference

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#696]
`Could not dispatch event: class cn.unionpay.national.bankcard.framework.events.StartViewEvent to subscribing class class cn.unionpay.national.bankcard.view.fragments.InstallMenuFragment
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference
    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4212)
    at android.view.ViewGroup.removeViewAt(ViewGroup.java:4170)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1540)
    at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
    at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:823)
    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:787)
    at me.yokeyword.fragmentation.TransactionDelegate.popToFix(TransactionDelegate.java:503)
    at me.yokeyword.fragmentation.TransactionDelegate.access$300(TransactionDelegate.java:30)
    at me.yokeyword.fragmentation.TransactionDelegate$7.call(TransactionDelegate.java:480)
    at me.yokeyword.fragmentation.TransactionDelegate.handleMock(TransactionDelegate.java:589)
    at me.yokeyword.fragmentation.TransactionDelegate.mockPopAnim(TransactionDelegate.java:581)
    at me.yokeyword.fragmentation.TransactionDelegate.executePopTo(TransactionDelegate.java:477)
    at me.yokeyword.fragmentation.TransactionDelegate.popTo(TransactionDelegate.java:441)
    at me.yokeyword.fragmentation.SupportFragmentDelegate.popTo(SupportFragmentDelegate.java:486)
    at me.yokeyword.fragmentation.SupportFragmentDelegate.popTo(SupportFragmentDelegate.java:482)
    at me.yokeyword.fragmentation.SupportFragmentDelegate.popTo(SupportFragmentDelegate.java:474)
    at me.yokeyword.fragmentation.SupportFragment.popTo(SupportFragment.java:359)
    at cn.unionpay.national.bankcard.view.fragments.BaseMenuFragment.backToPage(BaseMenuFragment.java:72)
    at cn.unionpay.national.bankcard.view.fragments.BaseMenuFragment.onNextView(BaseMenuFragment.java:58)
    at cn.unionpay.national.bankcard.framework.view.ViewFragment.onStartViewEvent(ViewFragment.java:152)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5271)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
`
稍后发调用方式

**Comment by zhangz89** [comment]
具体调用流程：
ActivityA FragmentA-》FragmentB-》FragmentC-》ActivityB FragmentD finishActivity
这时候是回到FragmentC，然后FragmentC直接popTo FragmentA 有一定概率出现上述的异常。
在FragmentC中有判断在resume之后再调用popTo

**Comment by YoKeyword** [comment]
`popTo`之前ActivityA的栈视图贴一下

**Comment by zhangz89** [comment]
![image](https://user-images.githubusercontent.com/8952784/34338102-2cb2df14-e9a0-11e7-98c5-f51b0cde71d0.png)
这个是正常时候的，异常情况是概率性出现，得重新提交测试下，后面出现异常再发上来

**Comment by zhangz89** [comment]
'me.yokeyword:fragmentation:1.0.9'
'com.android.support:appcompat-v7:25.3.1'

**Comment by YoKeyword** [comment]
嗯，该异常是因为：找不到对应的Fragment，然后操作其`clearAccessibilityFocus ()`方法时空指针

一般原因是 栈内顺序不正确

**Comment by zhangz89** [comment]
![image](https://user-images.githubusercontent.com/8952784/34338830-64e35dd0-e9a7-11e7-98ee-3f57e2089725.png)
![image](https://user-images.githubusercontent.com/8952784/34338841-6f78a76e-e9a7-11e7-8d47-67dfd9fdcb02.png)
试出来了，在A快速点击到B的跳转可以重现：A连续两下点击跳转到B，然后下面流程一致，栈图如一。这个时候没有异常奔溃，然后第二次正常按流程操作，栈图如二，并出现异常

**Comment by YoKeyword** [comment]
同时多次`start(B)`是没问题的， 一般引起顺序异常的原因是： `pop()`和`start()`有交叉，比如`pop`动画没有结束时，就存在`start()`

可以贴下相关代码，另外建议简化环境，排除ActivityB的外部条件， 在C中按钮事件里直接`popTo(A)`来测试，是否依然存在该问题

**Comment by YoKeyword** [comment]
@zhangz89  建议更新到v1.2.0，新增队列机制，彻底解决Fragment多点触控、极端事务问题，提高稳定性，见[更新日志](https://github.com/YoKeyword/Fragmentation/wiki)
