### ISSUE TITLE
点击悬浮球闪退

### ISSUE THREAD

**Issue by liulilei** [YoKeyword/Fragmentation#727]
01-04 10:50:01.840 12642-12642/com.mvp.bjsc E/RongLog: [ RongExceptionHandler ] uncaughtException
                                                       android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                           at android.content.res.Resources.getValue(Resources.java:2598)
                                                           at android.content.res.Resources.loadXmlResourceParser(Resources.java:4431)
                                                           at android.content.res.Resources.getLayout(Resources.java:2412)
                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                           at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
                                                           at android.support.v7.app.AlertController.installContent(AlertController.java:225)
                                                           at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:257)
                                                           at android.app.Dialog.dispatchOnCreate(Dialog.java:733)
                                                           at android.app.Dialog.show(Dialog.java:469)
                                                           at me.yokeyword.fragmentation.debug.DebugStackDelegate.showFragmentStackHierarchyView(DebugStackDelegate.java:109)
                                                           at me.yokeyword.fragmentation.debug.DebugStackDelegate$1.onClick(DebugStackDelegate.java:68)
                                                           at android.view.View.performClick(View.java:5721)
                                                           at me.yokeyword.fragmentation.debug.DebugStackDelegate$StackViewTouchListener.onTouch(DebugStackDelegate.java:257)
                                                           at android.view.View.dispatchTouchEvent(View.java:10012)
                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2876)
                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                           at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2869)
                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1861)
                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                           at me.yokeyword.fragmentation.SupportActivity.dispatchTouchEvent(SupportActivity.java:59)
                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                           at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2830)
                                                           at android.view.View.dispatchPointerEvent(View.java:10253)
                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5527)
                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5363)
                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4861)
                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4827)
                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4968)
                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4835)
                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5025)
                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4861)
                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4827)
                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4835)
                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7529)
                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7397)
                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7358)
                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7639)
                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       	at android.os.Mess

**Comment by liulilei** [comment]
compile 'me.yokeyword:fragmentation:1.1.10'
compile 'com.android.support:support-v4:25.1.0'
if (BuildConfig.DEBUG) {
            Fragmentation.builder()
                    // 显示悬浮球 ; 其他Mode:SHAKE: 摇一摇唤出   NONE：隐藏
                    .stackViewMode(Fragmentation.BUBBLE)
                    .debug(BuildConfig.DEBUG)
                    .install();
        }
点击悬浮球闪退

**Comment by YoKeyword** [comment]
````java
01-04 10:50:01.840 12642-12642/com.mvp.bjsc E/RongLog: [ RongExceptionHandler ] uncaughtException
android.content.res.Resources$NotFoundException: Resource ID #0x0
````
看Log好像和Fragmentation无关， 资源找不到，并且抛出融云的Exception

可以下载v1.1.10对应的[Demo APK](https://www.pgyer.com/80def26b61357b04d51d713cba8a1cda)看下Demo是否正常

**Comment by liulilei** [comment]
如果不点击悬浮球一切正常，但是点击悬浮球就闪退，是不是因为资源冲突导致的呢？还是说和融云有冲突?

**Comment by liulilei** [comment]
现在还有一个问题就是请教下，一个fragment里面有一个tab（两个按钮）+ 一个fragment用loadroot加载两个fragmentA、fragmentB，tab有两个按钮  第一个按钮对应第一个fragmentA，第二个按钮点击弹起一个菜单选择，里面有很多个菜单，点击任意一个显示不同的fragment去替换fragmentB，使用replace吗？  如果用replace的话，fragmentA 也没了，这种场景下，有什么好的解决办法吗？

**Comment by YoKeyword** [comment]
异常很奇怪id为0的资源找不到：`android.content.res.Resources$NotFoundException: Resource ID #0x0`  

可以使用摇一摇模式，这个问题后续再观察，之前还没有小伙伴遇到该问题

替换问题的话，你应该用的`loadMultipleRootFragment()`加载的吧，这个API加载的Fragment没有加入回退栈，所以可以用`replace/remove`等方法， `replace`是移除容器内所有Fragments，所以不符合你的场景， 使用`remove`+`add`即可：
````java
  fragmentManager.beginTransaction()
              .remove(fragmentB)
              .add(R.id.container, newFragment)
              .commitAllowingStateLoss();
````

**Comment by liulilei** [comment]
好的 谢谢啦，我先去试下。
