### ISSUE TITLE
关于pop（）回到上一个fragment的问题 报错FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by cuizzy** [YoKeyword/Fragmentation#729]
java.lang.IllegalStateException: FragmentManager is already executing transactions
                                                                            at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2007)
                                                                            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
                                                                            at me.yokeyword.fragmentation.TransactionDelegate.supportCommit(TransactionDelegate.java:254)
                                                                            at me.yokeyword.fragmentation.TransactionDelegate.start(TransactionDelegate.java:213)
                                                                            at me.yokeyword.fragmentation.TransactionDelegate.dispatchStartTransaction(TransactionDelegate.java:138)
                                                                            at me.yokeyword.fragmentation.SupportFragmentDelegate.start(SupportFragmentDelegate.java:404)
                                                                            at me.yokeyword.fragmentation.SupportFragmentDelegate.start(SupportFragmentDelegate.java:397)
                                                                            at com.flj.latte.ec.main.sort.goodslist.GoodsListDelegate.onFocusChange(GoodsListDelegate.java:262)

**Comment by cuizzy** [comment]
找到原因了 是因为上一个fragment 中的EditText 有焦点。这里需要处理。
