### ISSUE TITLE
息屏状态下调试启动app报错

### ISSUE THREAD

**Issue by a316789966** [YoKeyword/Fragmentation#736]
FATAL EXCEPTION: main
                                                           Process: ******, PID: 2348
                                                           java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                               at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2054)
                                                               at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2077)
                                                               at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
                                                               at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
                                                               at me.yokeyword.fragmentation.TransactionDelegate.supportCommit(TransactionDelegate.java:285)
                                                               at me.yokeyword.fragmentation.TransactionDelegate.start(TransactionDelegate.java:221)
                                                               at me.yokeyword.fragmentation.TransactionDelegate.loadRootTransaction(TransactionDelegate.java:73)
                                                               at me.yokeyword.fragmentation.SupportFragmentDelegate.loadRootFragment(SupportFragmentDelegate.java:379)
                                                               at me.yokeyword.fragmentation.SupportFragmentDelegate.loadRootFragment(SupportFragmentDelegate.java:375)
                                                               at me.yokeyword.fragmentation.SupportFragment.loadRootFragment(SupportFragment.java:276)
                                                               at *******.fragment.home.BaseHomeFragment.onLazyInitView(BaseHomeFragment.java:48)
                                                               at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.dispatchSupportVisible(VisibleDelegate.java:175)
                                                               at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.access$000(VisibleDelegate.java:19)
                                                               at me.yokeyword.fragmentation.helper.internal.VisibleDelegate$1.run(VisibleDelegate.java:139)
                                                               at android.os.Handler.handleCallback(Handler.java:733)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:136)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by LonelyMushroom** [comment]
更新到最新的版本,1.2.4解决了这个问题

**Comment by a316789966** [comment]
好的 谢谢
