### ISSUE TITLE
v1.1.10升级到v1.2.4后，Activity has been destroyed

### ISSUE THREAD

**Issue by StrangerFriend** [YoKeyword/Fragmentation#741]
v1.1.10升级到v1.2.4出现问题，升级前的版本正常
[2018-01-17 14:03:25:510][E][main:CrashHandler]java.lang.IllegalStateException: Activity has been destroyed
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1864)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
	at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:614)
	at me.yokeyword.fragmentation.TransactionDelegate.supportCommit(TransactionDelegate.java:444)
	at me.yokeyword.fragmentation.TransactionDelegate.doShowHideFragment(TransactionDelegate.java:425)
	at me.yokeyword.fragmentation.TransactionDelegate.access$500(TransactionDelegate.java:33)
	at me.yokeyword.fragmentation.TransactionDelegate$5.run(TransactionDelegate.java:144)
	at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:46)
	at me.yokeyword.fragmentation.queue.ActionQueue.access$200(ActionQueue.java:16)
	at me.yokeyword.fragmentation.queue.ActionQueue$2.run(ActionQueue.java:63)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by StrangerFriend** [comment]
应该是1.2里增加队列机制的问题，之前我在这里切换fragment即使用了fragmentManager原生方法又使用了fragmentaction的封装方法，现在看应该是使用fragmentManager不能操作到fragmentaction里的队列。我全部换成使用fragmentaction里的方法就没有问题啦。

**Comment by YoKeyword** [comment]
也可以通过 post()方法，把原生方法丢到队列里  :)

**Comment by ywp0919** [comment]
我从1.1.0升级1.3.3之后 也出现这样的问题了，但是我没有使用fragmentManager的原生方法来操作fragment，不知道要怎么修改代码才能正常使用1.3.3版本？

**Comment by ywp0919** [comment]
start的fragment，不管是返回键返回还是右滑返回还是pop都会崩溃，
 java.lang.IllegalStateException: Activity has been destroyed
    ║ 	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2075)
    ║ 	at android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:788)
    ║ 	at android.support.v4.app.FragmentationMagician$1.run(FragmentationMagician.java:87)
    ║ 	at android.support.v4.app.FragmentationMagician.hookStateSaved(FragmentationMagician.java:183)
    ║ 	at android.support.v4.app.FragmentationMagician.popBackStackAllowingStateLoss(FragmentationMagician.java:84)
    ║ 	at me.yokeyword.fragmentation.TransactionDelegate$8.run(TransactionDelegate.java:213)
    ║ 	at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:46)
