### ISSUE TITLE
偶现popTo接口发生空指针异常

### ISSUE THREAD

**Issue by naitiynil** [YoKeyword/Fragmentation#745]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version:V1.2.4
* Support-v4 version:25.3.1
* Logs:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4212)
	at android.view.ViewGroup.removeViewAt(ViewGroup.java:4170)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1540)
	at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
	at android.support.v4.app.FragmentationMagician$4.run(FragmentationMagician.java:126)
	at android.support.v4.app.FragmentationMagician.hookStateSaved(FragmentationMagician.java:186)
	at android.support.v4.app.FragmentationMagician.executePendingTransactionsAllowingStateLoss(FragmentationMagician.java:123)
	at me.yokeyword.fragmentation.TransactionDelegate.popToFix(TransactionDelegate.java:551)
	at me.yokeyword.fragmentation.TransactionDelegate.access$1300(TransactionDelegate.java:33)
	at me.yokeyword.fragmentation.TransactionDelegate$15.call(TransactionDelegate.java:537)
	at me.yokeyword.fragmentation.TransactionDelegate.handleMock(TransactionDelegate.java:641)
	at me.yokeyword.fragmentation.TransactionDelegate.mockPopAnim(TransactionDelegate.java:633)
	at me.yokeyword.fragmentation.TransactionDelegate.doPopTo(TransactionDelegate.java:534)
	at me.yokeyword.fragmentation.TransactionDelegate.access$1100(TransactionDelegate.java:33)
	at me.yokeyword.fragmentation.TransactionDelegate$10.run(TransactionDelegate.java:240)
	at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:46)
	at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:38)
	at me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:16)
	at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:30)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5271)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by naitiynil** [comment]
补充说明：
fragmentA>fragmentB>fragmentC, 在C页面popTo(A)，发生这个异常。请问是为什么？

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/696
你看下里面有没有能帮助到你的

**Comment by YoKeyword** [comment]
`popTo()`之前的栈视图截图提供下

**Comment by clunyes** [comment]
1.2.5碰到这个问题了，用延时popTo暂时解决了

**Comment by YoKeyword** [comment]
@clunyes Log贴一下看看
