### ISSUE TITLE
Get an error while coming from background

### ISSUE THREAD

**Issue by fvermeulen** [YoKeyword/Fragmentation#752]
Hey I get an app-crash when coming from background and want to reactivate the app

Have one Activity, with multiple fragments

* Library version 1.16, but happens as well on 1.2.5
* Support-v4 version : 27.0.2

> java.lang.RuntimeException: Unable to start activity ComponentInfo{de.xyz.android/de.xyz.android.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                          at android.app.ActivityThread.-wrap11(Unknown Source:0)
                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                          at android.os.Handler.dispatchMessage(Handler.java:106)
                          at android.os.Looper.loop(Looper.java:164)
                          at android.app.ActivityThread.main(ActivityThread.java:6494)
                          at java.lang.reflect.Method.invoke(Native Method)
                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
                          at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
                          at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
                          at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
                          at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:117)
                          at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)
                          at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                          at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                          at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                          at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3176)
                          at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:181)
                          at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:331)
                          at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                          at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
                          at de.xyz.android.MainActivity.onCreate(MainActivity.kt:115)
                          at android.app.Activity.performCreate(Activity.java:6999)
                          at android.app.Activity.performCreate(Activity.java:6990)
                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)

**Comment by YoKeyword** [comment]
> me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
at 

So  when you leave Activity, mFragmentAnimator is already Null.

**Comment by fvermeulen** [comment]
we are not resetting it in our code, only setting it to the DefaultFragmentAnimator in most cases

but what do you suggest, where should it handled then?

**Comment by YoKeyword** [comment]
@fvermeulen @rdoubleui  
Sorry for the late replay.

[SupportFragmentDelegate:](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/SupportFragmentDelegate.java#L105)：
```java
       if (savedInstanceState == null) {
            getFragmentAnimator();
        } else {
            mFragmentAnimator = savedInstanceState.getParcelable(TransactionDelegate.FRAGMENTATION_STATE_SAVE_ANIMATOR);
            ....
        }

    public void onSaveInstanceState(Bundle outState) {
        outState.putParcelable(TransactionDelegate.FRAGMENTATION_STATE_SAVE_ANIMATOR, mFragmentAnimator);
        ...
    }
````

You can see that the Fragmentation has been restored for the `FragmentAnimator`, and Demo can not reproduce the exception.
