### ISSUE TITLE
调用start(ISupportFragment) 时报错

### ISSUE THREAD

**Issue by ZhangHowie** [YoKeyword/Fragmentation#753]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
compile 'me.yokeyword:fragmentation:1.2.4'
* Support-v4 version
implementation 'com.android.support:support-v4:27.0.2'
* Logs
```shell
01-25 14:00:49.216 W/System.err(19500): java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
01-25 14:00:49.216 W/System.err(19500):         at android.view.ViewGroup.addViewInner(ViewGroup.java:3937)
01-25 14:00:49.217 W/System.err(19500):         at android.view.ViewGroup.addView(ViewGroup.java:3787)
01-25 14:00:49.217 W/System.err(19500):         at android.view.ViewGroup.addView(ViewGroup.java:3728)
01-25 14:00:49.217 W/System.err(19500):         at android.view.ViewGroup.addView(ViewGroup.java:3701)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
01-25 14:00:49.217 W/System.err(19500):         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
01-25 14:00:49.217 W/System.err(19500):         at android.os.Handler.handleCallback(Handler.java:739)
01-25 14:00:49.217 W/System.err(19500):         at android.os.Handler.dispatchMessage(Handler.java:95)
01-25 14:00:49.217 W/System.err(19500):         at android.os.Looper.loop(Looper.java:135)
01-25 14:00:49.217 W/System.err(19500):         at android.app.ActivityThread.main(ActivityThread.java:5262)
01-25 14:00:49.217 W/System.err(19500):         at java.lang.reflect.Method.invoke(Native Method)
01-25 14:00:49.217 W/System.err(19500):         at java.lang.reflect.Method.invoke(Method.java:372)
01-25 14:00:49.217 W/System.err(19500):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
01-25 14:00:49.217 W/System.err(19500):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```
* Screenshots
![image](https://user-images.githubusercontent.com/18179774/35373288-de49df02-01d8-11e8-87c6-fa937aea4d9f.png)

**Comment by ZhangHowie** [comment]
Sorry, 这是我同事的坑
