### ISSUE TITLE
Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference

### ISSUE THREAD

**Issue by dyfan** [YoKeyword/Fragmentation#771]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.2.6
* Support-v4 version 27.0.2
* Logs
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference
                                                                           at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4745)
                                                                           at android.view.ViewGroup.removeViewAt(ViewGroup.java:4704)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1762)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3195)
                                                                           at android.support.v4.app.Fragment.performPause(Fragment.java:2445)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1476)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3195)
                                                                           at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:225)
                                                                           at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:420)
                                                                           at net.aachina.common.base.activity.BaseActivity.onPause(BaseActivity.java:95)
                                                                           at net.aachina.aarsaboss.base.HjMvpActivity.onPause(HjMvpActivity.java:39)
                                                                           at android.app.Activity.performPause(Activity.java:6996)
                                                                           at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1323)
                                                                           at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3771)
                                                                           at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3748) 
                                                                           at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3722) 
                                                                           at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3696) 
                                                                           at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1518) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:163) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6237) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by dyfan** [comment]
首页的tab是homefragment和minefragment，
homefragment使用了viewpager+recycleviewlistfragment结构，然后来回滑动viewpager，在点击recycleview就会报这个错误。

**Comment by dyfan** [comment]
我在点击事件做的是startActivity操作

**Comment by dyfan** [comment]
查询了一下历史lssues，发现是pagaadapter的原因，已经修复。多谢作者的开源。
