### ISSUE TITLE
FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by cuizzy** [YoKeyword/Fragmentation#798]
FragmentManager is already executing transactions
这个是错误日志 
场景是 #317 处理方法是按照  三楼 的处理的 但是在runnable执行跳转操作时 出现这个错误

**Comment by YoKeyword** [comment]
先提供下v4包版本，以及Fragmentation版本

> # Issues Guideline

> Following information can help us to resolve the issue faster.

> * Library version
> * Support-v4 version
> * Logs
> * Screenshots

**Comment by cuizzy** [comment]
错误日志：
IllegalStateException: FragmentManager is already executing transactions
                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3394)
                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                 Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
                                                                    at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2007)
                                                                    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:816)
                                                                    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
                                                                    at me.yokeyword.fragmentation.TransactionDelegate.debouncePop(TransactionDelegate.java:397)
                                                                    at me.yokeyword.fragmentation.TransactionDelegate.back(TransactionDelegate.java:379)
                                                                    at me.yokeyword.fragmentation.SupportFragmentDelegate.pop(SupportFragmentDelegate.java:446)

Fragmentation版本：
compile 'me.yokeyword:fragmentation:1.0.3'
compile 'me.yokeyword:fragmentation-swipeback:1.0.3'

**Comment by LonelyMushroom** [comment]
哥们 要不升级下版本试试 现在是 `compile 'me.yokeyword:fragmentation:1.3.1`

**Comment by cuizzy** [comment]
应该是新版本优化了这个问题。
更新了版本 没有问题了。
谢谢。
是要紧跟步伐才行啊。
