### ISSUE TITLE
SwipeBackActivity系统兼容性问题

### ISSUE THREAD

**Issue by jeffer0323** [YoKeyword/Fragmentation#80]
小米4.4系统，继承SwipeBackActivity后运行报错，华为6.0系统，运行正常，望大神赐教

**Comment by YoKeyword** [comment]
@jeffer0323  小米的系统都测试过，Fragment和Activity是官方兼容包里的，应该没什么兼容方面的问题；

麻烦上一下报错日志，support包的版本~

**Comment by jeffer0323** [comment]
已解决，主题原因。  还是多谢了

**Comment by YoKeyword** [comment]
:)

**Comment by jeffer0323** [comment]
大神，模拟器上面挂了，类型转换异常
 Caused by: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
                                                     at me.yokeyword.fragmentation.SwipeBackLayout.attachToActivity(SwipeBackLayout.java:290)
                                                     at me.yokeyword.fragmentation_swipeback.SwipeBackActivity.onPostCreate(SwipeBackActivity.java:31)

**Comment by YoKeyword** [comment]
@jeffer0323  使用SwipeBack特性时，Activity／Fragment的根布局不可为View，应该是个ViewGroup

**Comment by jeffer0323** [comment]
6.0系统不会出现这种问题，很尴尬

**Comment by YoKeyword** [comment]
@jeffer0323 Demo模拟不会出现任何问题 安卓5.0 4.4都不会，刚试过～

**Comment by jeffer0323** [comment]
我APP中设置了透明状态栏，和这个有关系？

**Comment by YoKeyword** [comment]
要看你这个状态栏是什么方式实现的了，科学的方式是不会有问题的...

**Comment by Saqrag** [comment]
我在小米4c android5.1系统上试过，正常。但是在红米2 android4.4系统上测试，从一个Activity推出到上一个Activity，右滑时下面看到手机桌面，右滑结束回到上一个activity。这个怎么解决？ 感谢
