### ISSUE TITLE
 Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference

### ISSUE THREAD

**Issue by timmy008** [YoKeyword/Fragmentation#818]
viewpage 使用FragmentStatePagerAdapter，点击position-1出现

`
java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
                                                               at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
                                                               at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
                                                               at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
                                                               at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:117)
                                                               at xxx.BaseFragment.onCreate(BaseFragment.java:69)
                                                               at xxx.ChannelFragment.onCreate(ChannelFragment.java:80)
                                                               at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                               at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1187)
                                                               at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1070)
                                                               at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
                                                               at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2374)
                                                               at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                               at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
                                                               at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                                                               at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                                                               at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                                                               at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:663)
                                                               at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
                                                               at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:606)
                                                               at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2170)
                                                               at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1165)
                                                               at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1158)
                                                               at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1128)
                                                               at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1427)
                                                               at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1537)
                                                               at android.view.View$PerformClick.run(View.java:23645)
                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
`

**Comment by YoKeyword** [comment]
点击postion   1 还是 -1?  

提供下v4版本以及Fragmentation版本

**Comment by timmy008** [comment]
必现问题，我的布局是TabLayout加ViewPager，数据是从接口获取动态添加的
比如说我的FragmentStatePagerAdapter有10条数据，我现在点击到第十个，然在点击前面的任意一个就会出现
me.yokeyword:fragmentation:1.3.3
v4应该是27.3.1

**Comment by YoKeyword** [comment]
@timmy008 动态添加的代码以及'FragmentStatePagerAdapter'的代码贴下看看哈

**Comment by timmy008** [comment]
`
       mPagerAdapter = new MyPagerAdapter(mActivity.getSupportFragmentManager());
        viewPager.setAdapter(mPagerAdapter);
        tabLayout.setTabMode(TabLayout.MODE_SCROLLABLE);
        tabLayout.setupWithViewPager(viewPager);

        mWebApi.channels(MyRequestBody.create("com.xiaopeng.index.channels"))
                        .subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .doOnSubscribe(() -> mStatusLayout.showLoading())
                        .subscribe(this::onSuccess, error -> mStatusLayout.showRetry(), () -> 
                        mStatusLayout.showContent()));

     private void setData(List<ChannelsInfo.ColumnListBean> columnList){
                 mPagerAdapter.setNewData(columnList);
    }
`

`
   public class MyPagerAdapter extends FragmentPagerAdapter {

    private List<ChannelsInfo.ColumnListBean> mTitles = new ArrayList<>();

    public MyPagerAdapter(FragmentManager fm) {
        super(fm);
    }

    @Override
    public Fragment getItem(int position) {
        if (position == 0) {
            return HomeRecommendFragment.newInstance();
        } else {
            return ChannelFragment.getInstance(position);
        }
    }

    @Override
    public CharSequence getPageTitle(int position) {
        return mTitles.get(position).getContent();
    }

    @Override
    public int getCount() {
        return mTitles == null ? 0 : mTitles.size();
    }


    public void setNewData(List<ChannelsInfo.ColumnListBean> titleList) {
        mTitles.clear();
        mTitles = new ArrayList<>(titleList);
        notifyDataSetChanged();
    }
}
`

大致逻辑是这样的

**Comment by timmy008** [comment]
问题找到了，我自己的代码问题，我起实现ISupportFragment这个接口，Fragment生命周期方法没有去重写，只重写了你这个接口里面的方法
