### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference

### ISSUE THREAD

**Issue by nicai1900** [YoKeyword/Fragmentation#825]
#问题出现概率：**必现**

# 复现方法

APP启动后，到系统权限设置界面去关闭APP的某个权限，会导致APP进程退出，重新打开APP，就会崩溃

#手机系统：6.0以上

* Lib 1.3.3
* Support Lib 27.1.0
* Log

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:117)`

* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
@nicai1900  进程被杀后会做恢复操作，[恢复代码在这里](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/SupportFragmentDelegate.java#L108)


1、复现的机型是？
2、Demo不更改任何代码是否可以复现？

**Comment by nicai1900** [comment]
@YoKeyword 

1、复现的机型是？ 与机型无关，6.0以上需要动态权限就会

2、和哪个Demo无关，问题是必现的。动态改变权限后，进程被干掉，重新打开APP时，savedInstanceState 不为空，但是从savedInstanceState反序列化回来的mFragmentAnimator是空的

因此崩溃了。

`java
        // 
        if (savedInstanceState == null) {
            getFragmentAnimator();
        } else {
            mSaveInstanceState = savedInstanceState;
            mFragmentAnimator = savedInstanceState.getParcelable(TransactionDelegate.FRAGMENTATION_STATE_SAVE_ANIMATOR);
            mIsHidden = savedInstanceState.getBoolean(TransactionDelegate.FRAGMENTATION_STATE_SAVE_IS_HIDDEN);
            mContainerId = savedInstanceState.getInt(TransactionDelegate.FRAGMENTATION_ARG_CONTAINER);

            // RootFragment
            if (mRootStatus != STATUS_UN_ROOT) {
                FragmentationMagician.reorderIndices(mFragment.getFragmentManager());
            }
        }
`

**Comment by nicai1900** [comment]
@YoKeyword 我的微信号 zhengjie1900

**Comment by nicai1900** [comment]
@YoKeyword 问题解决了，我自己的错

自己实现了ISupportFragment 接口，但是生命周期里没有

复写

`kotlin

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        delegate.onSaveInstanceState(outState)
    }
`

**Comment by z1060932884** [comment]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim (AnimatorHelper.java:63)
me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged (AnimatorHelper.java:29)
me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init> (AnimatorHelper.java:24)
me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate (SupportFragmentDelegate.java:120)
com.pinyou.bingobuy.base.PresenterFragment.onCreate (PresenterFragment.java:89)
android.support.v4.app.Fragment.performCreate (Fragment.java:2068)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1055)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1290)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1272)
android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:2144)
android.support.v4.app.Fragment.restoreChildFragmentState (Fragment.java:1284)
android.support.v4.app.Fragment.onCreate (Fragment.java:1255)
com.pinyou.bingobuy.base.PresenterFragment.onCreate (PresenterFragment.java:88)
android.support.v4.app.Fragment.performCreate (Fragment.java:2068)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1055)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1290)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1272)
android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:2144)
android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java:190)
android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:351)
android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:85)
com.pinyou.bingobuy.base.Activity.onCreate (Activity.java:49)
android.app.Activity.performCreate (Activity.java:6303)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1108)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2376)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2483)
android.app.ActivityThread.access$900 (ActivityThread.java:153)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1349)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5438)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:738)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:628)
```
我也在实现ISupportFragment 的接口中重写了那个onSaveInstanceState（）方法，我自己怎么测都不会出现这个bug，但是bug收集工具收集了很多这个崩溃信息，  根据用户反馈就是长时间后台再进入就会出现这个问题。

**Comment by foolchen** [comment]
@z1060932884 是应用切换到后台，内存不足被杀死，再切换到前台重建Framgent时挂掉了。
我上个版本更新v4包到27.1.0之后出现了这个问题，然后再更新到27.1.1这个崩溃就没了。
不要问我排查问题的过程...一言难尽...

**Comment by foolchen** [comment]
@z1060932884 v4包更新到27.1.1试试。

**Comment by YoKeyword** [comment]
@z1060932884  楼上2位同学一个同学是忘记在Fragment里`delegate.onSaveInstanceState(outState)`，一个同学是移除了Activity里的`super.onSaveInstanceState()`

所有检查Activity和Fragment的`onSaveInstanceState()`，看是否有复写或者忘记委托，  具体复现方式，可以按 @foolchen 提供的方式复现

**Comment by z1060932884** [comment]
@YoKeyword 
``` 
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
                                                                       at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
                                                                       at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
                                                                       at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
                                                                       at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:120)
                                                                       at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)
                                                                       at com.pinyou.bingobuy.base.PresenterFragment.onCreate(PresenterFragment.java:88)
                                                                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2328)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1379)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3200)
                                                                       at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1442)
                                                                       at android.support.v4.app.Fragment.onCreate(Fragment.java:1413)
                                                                       at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:47)
                                                                       at com.pinyou.bingobuy.base.PresenterFragment.onCreate(PresenterFragment.java:88)
                                                                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2328)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1379)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3200)
                                                                       at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:184)
                                                                       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:355)
                                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                                                                       at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
                                                                       at com.pinyou.bingobuy.base.Activity.onCreate(Activity.java:50)
                                                                       at android.app.Activity.performCreate(Activity.java:6268)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
```
我继承的是  SupportFragment和SupportFragment ，在切换权限的是否还是会出现这个问题，打开权限时，不会有问题，关闭权限时 就出现问题了  ，我用你的demo测试没有问题

**Comment by z1060932884** [comment]
@YoKeyword  @foolchen 

  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
                                                                         at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
                                                                         at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
                                                                         at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
                                                                         at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:120)
                                                                         at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)
                                                                         at com.pinyou.bingobuy.base.PresenterFragment.onCreate(PresenterFragment.java:88)
                                                                         at android.support.v4.app.Fragment.performCreate(Fragment.java:2328)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1379)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3200)
                                                                         at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1442)
                                                                         at android.support.v4.app.Fragment.onCreate(Fragment.java:1413)
                                                                         at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:47)
                                                                         at com.pinyou.bingobuy.base.PresenterFragment.onCreate(PresenterFragment.java:88)
                                                                         at android.support.v4.app.Fragment.performCreate(Fragment.java:2328)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1379)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3200)
                                                                         at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:184)
                                                                         at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:355)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                                                                         at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
                                                                         at com.pinyou.bingobuy.base.Activity.onCreate(Activity.java:50)
                                                                         at android.app.Activity.performCreate(Activity.java:6268)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477) 
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 

我的Activity和Fragment继承了你的，还是崩溃   ，切换v4包27.1.1也不行
Activity的代码
```

public abstract class Activity<Presenter extends BaseContract.Presenter> extends SupportActivity
        implements BaseContract.View<Presenter> {
    private static final String NAVIGATIONBAR_IS_MIN = "navigationbar_is_min";
    protected String TAG;
    protected Presenter mPresenter;
    //状态栏管理
    protected ImmersionBar mImmersionBar;
    protected Context mContext;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TAG = getClass().getSimpleName();
        mContext = this;
        // 在界面未初始化之前调用的初始化窗口
        initWidows();
        ViseLog.e("5555555555555555555555555555");
        if (initArgs(getIntent().getExtras())) {
            ViseLog.e("asssssssssssssssssssssss");
            // 得到界面Id并设置到Activity界面中
            int layId = getContentLayoutId();
            setContentView(layId);
            initPresenter();
            initBefore();
            initWidget();
            initData();
            if (isRegisterEvent()) {
                BusManager.getBus().register(this);
            }
//            AppManager.getAppManager().addActivity(this);
        } else {
            finish();
        }
    }


    /**
     * 初始化控件调用之前
     */
    protected void initBefore() {

    }

    /**
     * 初始化窗口
     */
    protected void initWidows() {
        //透明状态栏
        if (isStatuBarTranslucent()) {
            Tools.statuBar(this);
        }
        //初始化沉浸式
        if (isImmersionBarEnabled()) {
            initImmersionBar();
        }

        //解决华为emui3.0与3.1手机手动隐藏底部导航栏时，导航栏背景色未被隐藏的问题
        if (OSUtils.isEMUI3_1()) {
            //第一种
            getContentResolver().registerContentObserver(Settings.System.getUriFor
                    (NAVIGATIONBAR_IS_MIN), true, mNavigationStatusObserver);
            //第二种,禁止对导航栏的设置
            //mImmersionBar.navigationBarEnable(false).init();
        }
    }

    /**
     * 初始化相关参数
     *
     * @param bundle 参数Bundle
     * @return 如果参数正确返回True，错误返回False
     */
    protected boolean initArgs(Bundle bundle) {
        return true;
    }

    /**
     * 得到当前界面的资源文件Id
     *
     * @return 资源文件Id
     */
    protected abstract int getContentLayoutId();

    /**
     * 初始化Presenter
     *
     * @return Presenter
     */
    protected abstract Presenter initPresenter();

    /**
     * 初始化控件
     */
    protected void initWidget() {
        ButterKnife.bind(this);
    }

    /**
     * 初始化数据
     */
    protected void initData() {

    }

    @Override
    public void setPresenter(Presenter presenter) {
        // View中赋值Presenter
        mPresenter = presenter;
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (mImmersionBar != null) {
            mImmersionBar.destroy();  //在BaseActivity里销毁
        }
        // 界面关闭时进行销毁的操作
        if (mPresenter != null) {
            mPresenter.destroy();
        }
        if (isRegisterEvent()) {
            BusManager.getBus().unregister(this);
        }
//        AppManager.getAppManager().finishActivity(this);
        if(mContext!=null){
            //取消glide加载
            Glide.with(App.getInstance().getApplicationContext()).pauseRequests();
        }
    }

    @Override
    public boolean onSupportNavigateUp() {
        // 当点击界面导航返回时，Finish当前界面
        finish();
        return super.onSupportNavigateUp();
    }

    private ContentObserver mNavigationStatusObserver = new ContentObserver(new Handler()) {
        @Override
        public void onChange(boolean selfChange) {
            int navigationBarIsMin = Settings.System.getInt(getContentResolver(),
                    NAVIGATIONBAR_IS_MIN, 0);
            if (navigationBarIsMin == 1) {
                //导航键隐藏了
                mImmersionBar.transparentNavigationBar().init();
            } else {
                //导航键显示了
                mImmersionBar.navigationBarColor(android.R.color.black) //隐藏前导航栏的颜色
                        .fullScreen(false)
                        .init();
            }
        }
    };

    protected void initImmersionBar() {
        //在BaseActivity里初始化
        mImmersionBar = ImmersionBar.with(this);
        mImmersionBar.init();
    }

    /**
     * 是否可以使用沉浸式
     * Is immersion bar enabled boolean.
     *
     * @return the boolean
     */
    protected boolean isImmersionBarEnabled() {
        return false;
    }

    protected boolean isRegisterEvent() {
        return false;
    }

    /**
     * 是否开启透明状态栏
     *
     * @return
     */
    protected boolean isStatuBarTranslucent() {
        return false;
    }
//    @Override
//    public void onBackPressed() {
//        // 得到当前Activity下的所有Fragment
//        @SuppressLint("RestrictedApi")
//        List<Fragment> fragments = getSupportFragmentManager().getFragments();
//        // 判断是否为空
//        if (fragments != null && fragments.size() > 0) {
//            for (Fragment fragment : fragments) {
//                // 判断是否为我们能够处理的Fragment类型
//                if (fragment instanceof Fragment) {
//                    // 判断是否拦截了返回按钮
//                    if (((Fragment) fragment).onBackPressed()) {
//                        // 如果有直接Return
//                        return;
//                    }
//                }
//            }
//        }
//
//        super.onBackPressed();
//        finish();
//    }







    /**
     * Set all fragments animation.
     * 构建Fragment转场动画
     * <p/>
     * 如果是在Activity内实现,则构建的是Activity内所有Fragment的转场动画,
     * 如果是在Fragment内实现,则构建的是该Fragment的转场动画,此时优先级 > Activity的onCreateFragmentAnimator()
     *
     * @return FragmentAnimator对象
     */
    @Override
    public FragmentAnimator onCreateFragmentAnimator() {
        // 设置横向(和安卓4.x动画相同)
        return new DefaultHorizontalAnimator();
    }

}
```
Fragment里的代码：
```
public abstract class PresenterFragment<Presenter extends BaseContract.Presenter> extends SupportFragment
        implements BaseContract.View<Presenter> {

    protected Presenter mPresenter;
    protected Activity mActivity;
    protected PresenterFragment.OnBackToFirstListener _mBackToFirstListener;


    protected static String TAG = "";
    protected View mRoot;
    protected Unbinder mRootUnBinder;
    // 标示是否第一次初始化数据
    protected boolean mIsFirstInitData = true;

    protected OnFragmentOpenDrawerListener mOpenDraweListener;



    @Override
    public void onAttach(android.app.Activity activity) {
        super.onAttach(activity);
        TAG = this.getClass().getSimpleName();
        // 初始化参数
        initArgs(getArguments());
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        mActivity = (Activity) context;
        if (context instanceof PresenterFragment.OnBackToFirstListener) {
            _mBackToFirstListener = (PresenterFragment.OnBackToFirstListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnBackToFirstListener");
        }

        if (context instanceof OnFragmentOpenDrawerListener) {
            mOpenDraweListener = (OnFragmentOpenDrawerListener) context;
        } else {
//            throw new RuntimeException(context.toString()
//                    + " must implement OnFragmentOpenDrawerListener");
        }
        // 在界面onAttach之后就触发初始化Presenter
        initPresenter();
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);

    }



    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        if (mRoot == null) {
            int layId = getContentLayoutId();
            // 初始化当前的跟布局，但是不在创建时就添加到container里边
            View root = inflater.inflate(layId, container, false);
            initWidget(root);
            BusManager.getBus().register(this);
            mRoot = root;
        } else {
            if (mRoot.getParent() != null) {
                // 把当前Root从其父控件中移除
                ((ViewGroup) mRoot.getParent()).removeView(mRoot);
            }
        }

        return mRoot;
    }

    /**
     * 初始化Presenter
     *
     * @return Presenter
     */
    protected abstract Presenter initPresenter();

    @Override
    public void showError(String str) {
    }

    @Override
    public void showLoading() {

    }

    @Override
    public void setPresenter(Presenter presenter) {
        // View中赋值Presenter
        mPresenter = presenter;
    }


    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        if (mIsFirstInitData) {
            // 触发一次以后就不会触发
            mIsFirstInitData = false;
            // 触发
            onFirstInit();
        }

        // 当View创建完成后初始化数据
        initData();
    }

    /**
     * 初始化相关参数
     */
    protected void initArgs(Bundle bundle) {

    }

    /**
     * 得到当前界面的资源文件Id
     *
     * @return 资源文件Id
     */
    @LayoutRes
    protected abstract int getContentLayoutId();
    /**
     * 初始化控件
     */
    protected void initWidget(View root) {
        mRootUnBinder = ButterKnife.bind(this, root);
    }

    /**
     * 初始化数据
     */
    protected void initData() {

    }

    /**
     * 当首次初始化数据的时候会调用的方法
     */
    protected void onFirstInit() {

    }

//    /**
//     * 返回按键触发时调用
//     *
//     * @return 返回True代表我已处理返回逻辑，Activity不用自己finish。
//     * 返回False代表我没有处理逻辑，Activity自己走自己的逻辑
//     */
//    public boolean onBackPressed() {
//        return false;
//    }

    @Override
    public void onDetach() {
        super.onDetach();
        //侧滑开关
        mOpenDraweListener = null;

        _mBackToFirstListener = null;
    }


    @Override
    public void onDestroy() {
        super.onDestroy();
        if (mPresenter != null)
            mPresenter.destroy();
        BusManager.getBus().register(this);
    }



    @Override
    public FragmentAnimator onCreateFragmentAnimator() {
        // 设置横向(和安卓4.x动画相同)
        return new DefaultHorizontalAnimator();
    }


    /**
     * 按返回键触发,前提是SupportActivity的onBackPressed()方法能被调用
     *
     * @return false则继续向上传递, true则消费掉该事件
     */
    @Override
    public boolean onBackPressedSupport() {
        //安返回键处理输入法
       if(_mActivity!=null){
           if (_mActivity.getWindow().getAttributes().softInputMode == WindowManager.LayoutParams.SOFT_INPUT_STATE_UNSPECIFIED) {
               _mActivity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN);
           }
       }
//        if (getChildFragmentManager().getBackStackEntryCount() > 1) {
//            popChild();
//        }
////        else {
////            if (this instanceof ZhihuFirstFragment) {   // 如果是 第一个Fragment 则退出app
////                _mActivity.finish();
////            } else {                                    // 如果不是,则回到第一个Fragment
////                _mBackToFirstListener.onBackToFirstFragment();
////            }
////        }
        return false;
    }

    public interface OnBackToFirstListener {
        void onBackToFirstFragment();
    }

    /**
     * 是否返回
     *
     * @param isback
     * @param toolbar
     */
    protected void initToolbarNav(boolean isback, Toolbar toolbar, AppCompatTextView toolbar_title, String title) {
        setHasOptionsMenu(true);//fragment中创建toolbar右侧图标
        mActivity.setSupportActionBar(toolbar);
        if (isback) {

            toolbar.setTitle(title);
            toolbar.setNavigationIcon(R.drawable.ic_back);
            toolbar.setTitleTextColor(App.getInstance().getResources().getColor(R.color.colorPrimary));
            toolbar.setNavigationOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    _mActivity.onBackPressed();
                }
            });
        } else {
            mActivity.getSupportActionBar().setTitle("");
            toolbar_title.setText(title);
            toolbar.setNavigationIcon(R.drawable.ic_navmenu);
            toolbar.setNavigationOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (mOpenDraweListener != null) {
                        mOpenDraweListener.onOpenDrawer();
                    }
                }
            });
        }
        toolbar.setBackgroundColor(getResources().getColor(R.color.white));

    }


    public interface OnFragmentOpenDrawerListener {
        void onOpenDrawer();
    }
}
```

**Comment by z1060932884** [comment]
找到原因了 ，进程杀死时onSaveInstanceState方法在执行次数比onCreate方法执行次数少，然后查看自己写的代码，去掉了一个Fragment加载Fragment的界面就好了。 @YoKeyword  @foolchen
