### ISSUE TITLE
线上包 NullPointerException

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#846]
- 版本：1.3.3
- Exception：NullPointerException
- 描述：线上bugly 捕捉到 bug，只发生在 android 8.0 系统。
- exception 详情：
```
#1 main

java.lang.NullPointerException

Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
```
- log（混淆）：
```
1 android.view.ViewGroup.removeViewInternal(ViewGroup.java:5270)
2 android.view.ViewGroup.removeViewAt(ViewGroup.java:5233)
3 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:61)
4 android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:47)
5 android.support.v4.app.BackStackRecord.executeOps(Unknown Source:170)
6 android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source:41)
7 android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:103)
8 android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:98)
9 android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source:21)
10 android.support.v4.app.FragmentManagerImpl.executePendingTransactions(Unknown Source:0)
11 android.support.v4.app.FragmentationMagician$4.run(Unknown Source:2)
12 android.support.v4.app.FragmentationMagician.hookStateSaved(Unknown Source:24)
13 android.support.v4.app.FragmentationMagician.executePendingTransactionsAllowingStateLoss(Unknown Source:5)
14 me.yokeyword.fragmentation.k.a(Unknown Source:45)
15 me.yokeyword.fragmentation.k.a(Unknown Source:36)
16 me.yokeyword.fragmentation.k.a(Unknown Source:70)
17 me.yokeyword.fragmentation.k.a(Unknown Source:0)
18 me.yokeyword.fragmentation.k$3.a(Unknown Source:10)
19 me.yokeyword.fragmentation.b.b.a(Unknown Source:17)
20 me.yokeyword.fragmentation.b.b.b(Unknown Source:14)
21 me.yokeyword.fragmentation.b.b.a(Unknown Source:0)
22 me.yokeyword.fragmentation.b.b$1.run(Unknown Source:4)
23 android.os.Handler.handleCallback(Handler.java:808)
24 android.os.Handler.dispatchMessage(Handler.java:101)
25 android.os.Looper.loop(Looper.java:166)
26 android.app.ActivityThread.main(ActivityThread.java:7425)
27 java.lang.reflect.Method.invoke(Native Method)
28 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
29 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
- log(mapping 解释混淆后)：
```

1 android.view.ViewGroup.removeViewInternal(ViewGroup.java:5270)
2 android.view.ViewGroup.removeViewAt(ViewGroup.java:5233)
3 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:61)
4 android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source:47)
5 android.support.v4.app.BackStackRecord.executeOps(Unknown Source:170)
6 android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source:41)
7 android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:103)
8 android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:98)
9 android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source:21)
10 android.support.v4.app.FragmentManagerImpl.executePendingTransactions(Unknown Source:0)
11 android.support.v4.app.FragmentationMagician$4.run(Unknown Source:2)
12 android.support.v4.app.FragmentationMagician.hookStateSaved(Unknown Source:24)
13 android.support.v4.app.FragmentationMagician.executePendingTransactionsAllowingStateLoss(Unknown Source:5)
14 me.yokeyword.fragmentation.TransactionDelegate.a(Unknown Source:45)
15 me.yokeyword.fragmentation.TransactionDelegate.a(Unknown Source:36)
16 me.yokeyword.fragmentation.TransactionDelegate.a(Unknown Source:70)
17 me.yokeyword.fragmentation.TransactionDelegate.void post(java.lang.Runnable)(Unknown Source:0)
18 ##_parent_##40##_parent_##
19 ##_child_## void loadRootTransaction(android.support.v4.app.FragmentManager,int,me.yokeyword.fragmentation.ISupportFragment,boolean,boolean)##_child_##
20 ##_child_## void loadMultipleRootTransaction(android.support.v4.app.FragmentManager,int,int,me.yokeyword.fragmentation.ISupportFragment[])##_child_##
21 ##_child_## void dispatchStartTransaction(android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,int,int,int)##_child_##
22 ##_child_## void showHideFragment(android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment)##_child_##
23 ##_child_## void startWithPopTo(android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,java.lang.String,boolean)##_child_##
24 ##_child_## void remove(android.support.v4.app.FragmentManager,android.support.v4.app.Fragment,boolean)##_child_##
25 ##_child_## void pop(android.support.v4.app.FragmentManager)##_child_##
26 ##_child_## void popTo(java.lang.String,boolean,java.lang.Runnable,android.support.v4.app.FragmentManager,int)##_child_##
27 ##_child_## boolean dispatchBackPressedEvent(me.yokeyword.fragmentation.ISupportFragment)##_child_##
28 ##_child_## void handleResultRecord(android.support.v4.app.Fragment)##_child_##
29 ##_child_## void enqueue(android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.queue.Action)##_child_##
30 ##_child_## me.yokeyword.fragmentation.ISupportFragment getTopFragmentForStart(me.yokeyword.fragmentation.ISupportFragment,android.support.v4.app.FragmentManager)##_child_##
31 ##_child_## void start(android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,java.lang.String,boolean,java.util.ArrayList,boolean,int)##_child_##
32 ##_child_## void bindContainerId(int,me.yokeyword.fragmentation.ISupportFragment)##_child_##
33 ##_child_## void supportCommit(android.support.v4.app.FragmentManager,android.support.v4.app.FragmentTransaction)##_child_##
34 ##_child_## boolean handleLaunchMode(android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,java.lang.String,int)##_child_##
35 ##_child_## void handleNewBundle(me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment)##_child_##
36 ##_child_## void saveRequestCode(android.support.v4.app.FragmentManager,android.support.v4.app.Fragment,android.support.v4.app.Fragment,int)##_child_##
37 ##_child_## void doPopTo(java.lang.String,boolean,android.support.v4.app.FragmentManager,int)##_child_##
38 ##_child_## void safePopTo(java.lang.String,android.support.v4.app.FragmentManager,int,java.util.List)##_child_##
39 ##_child_## void mockPopToAnim(android.support.v4.app.Fragment,java.lang.String,android.support.v4.app.FragmentManager,int,java.util.List,int)##_child_##
40 ##_child_## void mockStartWithPopAnim(me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,android.view.animation.Animation)##_child_##
41 ##_child_## android.view.ViewGroup addMockView(android.view.View,android.view.ViewGroup)##_child_##
42 ##_child_## android.view.ViewGroup findContainerById(android.support.v4.app.Fragment,int)##_child_##
43 ##_child_## void checkNotNull(java.lang.Object,java.lang.String)##_child_##
44 ##_child_## void handleAfterSaveInStateTransactionException(android.support.v4.app.FragmentManager,java.lang.String)##_child_##
45 ##_child_## void access$000(me.yokeyword.fragmentation.TransactionDelegate,int,me.yokeyword.fragmentation.ISupportFragment)##_child_##
46 ##_child_## void access$100(me.yokeyword.fragmentation.TransactionDelegate,android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,java.lang.String,boolean,java.util.ArrayList,boolean,int)##_child_##
47 ##_child_## android.os.Bundle access$200(me.yokeyword.fragmentation.TransactionDelegate,android.support.v4.app.Fragment)##_child_##
48 ##_child_## void access$300(me.yokeyword.fragmentation.TransactionDelegate,android.support.v4.app.FragmentManager,android.support.v4.app.FragmentTransaction)##_child_##
49 ##_child_## void access$400(me.yokeyword.fragmentation.TransactionDelegate,android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,int,int,int)##_child_##
50 ##_child_## void access$500(me.yokeyword.fragmentation.TransactionDelegate,android.support.v4.app.FragmentManager,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment)##_child_##
51 ##_child_## me.yokeyword.fragmentation.ISupportFragment access$600(me.yokeyword.fragmentation.TransactionDelegate,me.yokeyword.fragmentation.ISupportFragment,android.support.v4.app.FragmentManager)##_child_##
52 ##_child_## void access$700(me.yokeyword.fragmentation.TransactionDelegate,android.support.v4.app.FragmentManager,java.lang.String)##_child_##
53 ##_child_## void access$800(me.yokeyword.fragmentation.TransactionDelegate,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment,android.view.animation.Animation)##_child_##
54 ##_child_## void access$900(me.yokeyword.fragmentation.TransactionDelegate,android.support.v4.app.FragmentManager)##_child_##
55 ##_child_## android.os.Handler access$1000(me.yokeyword.fragmentation.TransactionDelegate)##_child_##
56 ##_child_## void access$1100(me.yokeyword.fragmentation.TransactionDelegate,java.lang.String,android.support.v4.app.FragmentManager,int,java.util.List)##_child_##
57 ##_child_## void access$1300(me.yokeyword.fragmentation.TransactionDelegate,java.lang.String,boolean,android.support.v4.app.FragmentManager,int)##_child_##
58 ##_child_## void access$1400(me.yokeyword.fragmentation.TransactionDelegate,me.yokeyword.fragmentation.ISupportFragment,me.yokeyword.fragmentation.ISupportFragment)##_child_##
59 me.yokeyword.fragmentation.TransactionDelegate$11.a(Unknown Source:10)
60 me.yokeyword.fragmentation.queue.ActionQueue.void access$000(me.yokeyword.fragmentation.queue.ActionQueue,me.yokeyword.fragmentation.queue.Action)(Unknown Source:17)
61 ##_parent_##1##_parent_##
62 ##_child_## java.util.Queue access$100(me.yokeyword.fragmentation.queue.ActionQueue)##_child_##
63 me.yokeyword.fragmentation.queue.ActionQueue.b(Unknown Source:14)
64 me.yokeyword.fragmentation.queue.ActionQueue.void enqueue(me.yokeyword.fragmentation.queue.Action)(Unknown Source:0)
65 ##_parent_##3##_parent_##
66 ##_child_## void handleAction()##_child_##
67 ##_child_## void access$000(me.yokeyword.fragmentation.queue.ActionQueue,me.yokeyword.fragmentation.queue.Action)##_child_##
68 ##_child_## java.util.Queue access$100(me.yokeyword.fragmentation.queue.ActionQueue)##_child_##
69 me.yokeyword.fragmentation.queue.ActionQueue$1.run(Unknown Source:4)
70 android.os.Handler.handleCallback(Handler.java:808)
71 android.os.Handler.dispatchMessage(Handler.java:101)
72 android.os.Looper.loop(Looper.java:166)
73 android.app.ActivityThread.main(ActivityThread.java:7425)
74 java.lang.reflect.Method.invoke(Native Method)
75 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
76 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)


```

**Comment by Gundam0079** [comment]
我有时候会遇到这个问题  发现时在Fragment中 弹dialogFragment时候会出现

**Comment by VankaIn** [comment]
可以看到第30行```getTopFragmentForStart```调用到，而看到你提交代码git版本```11ae2f7697c74c682a9093b20197847dd8e723d8```是有对这个方法进行了修改，不知道有没有关系？ @YoKeyword

**Comment by YoKeyword** [comment]
11ae2f7697c74c682a9093b20197847dd8e723d8 这个commit是跳过无UI的Fragment （比如Glide的`RequestSupportManagerFragment`）

现在是否还会出现该问题？

**Comment by zhijianz** [comment]
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
> 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4629)
> 	at android.view.ViewGroup.removeViewAt(ViewGroup.java:4591)
> 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1764)
> 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
> 	at android.support.v4.app.BackStackRecord.f(BackStackRecord.java:797)
> 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
> 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
> 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
> 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
> 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:783)
> 	at android.support.v4.app.FragmentationMagician$4.run(FragmentationMagician.java:126)
> 	at android.support.v4.app.FragmentationMagician.a(FragmentationMagician.java:186)
> 	at android.support.v4.app.FragmentationMagician.d(FragmentationMagician.java:123)
> 	at me.yokeyword.fragmentation.g.a(TransactionDelegate.java:580)
> 	at me.yokeyword.fragmentation.g.a(TransactionDelegate.java:609)
> 	at me.yokeyword.fragmentation.g.a(TransactionDelegate.java:566)
> 	at me.yokeyword.fragmentation.g.a(TransactionDelegate.java:32)
> 	at me.yokeyword.fragmentation.g$2.a(TransactionDelegate.java:289)
> 	at me.yokeyword.fragmentation.a.b.a(ActionQueue.java:53)
> 	at me.yokeyword.fragmentation.a.b.b(ActionQueue.java:45)
> 	at me.yokeyword.fragmentation.a.b.a(ActionQueue.java:17)
> 	at me.yokeyword.fragmentation.a.b$1.run(ActionQueue.java:37)
> 	at android.os.Handler.handleCallback(Handler.java:739)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:179)
> 	at android.app.ActivityThread.main(ActivityThread.java:5769)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)

线上遇到一样的问题，出现版本不限于Android8，现在使用是的版本1.3.3，现在有什么头绪吗

**Comment by SilenceDut** [comment]
遇到同样问题

**Comment by wzxx** [comment]
遇到同样问题 版本：1.3.3
不仅在8.0系统上存在

**Comment by YoKeyword** [comment]
@zhijianz 提供下support包的版本， 该异常是栈内Fragment的顺序发生了异常

**Comment by YoKeyword** [comment]
@zhijianz 是否可以稳定复现？  可以的话，观察下栈内顺序情况，看是否有异常操作，看不出来的话描述下复现步骤

**Comment by javalong** [comment]
必现情况：
start(FragmentUtils.getInstance().getFragment(this, ReturnFragment::class.java), ISupportFragment.SINGLETASK)

dialog = AlertDialog.Builder()
                    .type(TYPE_FULL_POWER)
                    .onAlertCallback(object : AlertDialog.OnAlertCallbak {
                        override fun onOkClick() {
                            popToRoot()
                        }
                    })
                    .build()
dialog?.show(activity?.supportFragmentManager, null)


就是跳转Fragment之后，马上调用DialogFragment.show(),然后再pop的时候就报错了。
暂时我的解决办法：
添加了一个延时 调用DialogFragment.show()

**Comment by YoKeyword** [comment]
@javalong  `show()`的代码放到SupportActivity/Fragment的`post()`队列中即可， 或者在DialogFragment中[这样处理](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_wechat/ui/fragment/second/DemoDialogFragment.java#L49)
