### ISSUE TITLE
更改运用权限,导致运用重启,栈视图会增加一份并且某些fragment缺失

### ISSUE THREAD

**Issue by skythinking** [YoKeyword/Fragmentation#877]
# Issues Guideline

Following information can help us to resolve the issue faster.
1.当我们在华为手机(系统版本:8.0.0)或在一加手机(系统版本:7.1.1)上打开一个应用，将应用退至后台进程中。 
2.打开 “设置”去更改该应用的权限（比如将“定位”权限由授权状态改为非授权状态）。 
3.再将该应用重新切换到前台，会发现应用进行了重新启动,栈视图中增加了一份,而且fragment包裹的子fragment消失了. 
* Library version  1.3.4
* Support-v4 version 27.1.1
* Logs
* Screenshots
<img width="252" alt="image" src="https://user-images.githubusercontent.com/7401507/40415614-decf4c3c-5ead-11e8-982d-596e7fe071b4.png">

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
这个需要排查加载该Fragment的代码， 另外一种简单的复现方式： 开发者模式 -> 不保留活动 打开，回桌面再进App即可复现

排查下被杀之前以及恢复后，做了什么可以操作，  如果不好排查，建议去除干扰因素（其他子Fragment等）来排查

**Comment by skythinking** [comment]
有一种做法是让app重启,这样返回栈就不会乱了.

**Comment by Jiiiiiin** [comment]
@YoKeyword 一样出现了这个问题(退出后台去修改权限（关闭某个权限时候出现，root fragment栈中的子fragment就乱了）)，目前解决就是让应用重启：

```java
 @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (null != savedInstanceState) {
            _restart();
        } else {
            _initVPAgain();
...

 <activity
            android:name=".MainActivity"
            **android:launchMode="standard"**
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

**Comment by YoKeyword** [comment]
@Jiiiiiin  重启不是一个好的解决方式，  开发者选项 `不保留活动` 能否复现？ 
另外，更严谨的方式：`if (null != findFragment(YourFragment.class)) `替换`if (null != savedInstanceState) `

**Comment by Jiiiiiin** [comment]
@YoKeyword 嗯 下载我试试

**Comment by Jiiiiiin** [comment]
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fs8oyjucsnj30z01md0wc.jpg)

只要在应用运行时，去修改权限就会出现，比如关闭一个定位授权，如果不重启，有什么更好的解决方案呢？

@YoKeyword

**Comment by Jiiiiiin** [comment]
```java
 @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (null != findFragment(BottomDelegate.class)) {
            LoggerProxy.e("main activity 应用重启 %s", savedInstanceState);
            // 关注：https://github.com/YoKeyword/Fragmentation/issues/877#event-1665429707
            _restart();
        } else {
            // !将3.04sp中缓存的用户信息转换到hawk中
            SignUserManager.getInstance().initOrUpdateLoginUser(SignInUtil.getSPCacheUserOrNullll());
            LoggerProxy.d("应用启动，读取缓存用户信息 %s", SignUserManager.getInstance().getLoginUser());

            _initVPAgain();
            _initWebViewCache();
            _hideActionBar();
            _initStyle();
```

目前这种方式到时解决了这个问题

**Comment by Jiiiiiin** [comment]
修改成下面这样就出现了一下问题：

```java
java.lang.NullPointerException: There is no Fragment in the FragmentManager, maybe you need to call loadRootFragment() first!
	at me.yokeyword.fragmentation.TransactionDelegate$6.run(TransactionDelegate.java:158)
	at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
	at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
	at me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:17)
	at me.yokeyword.fragmentation.queue.ActionQueue.access$100(ActionQueue.java:17)
	at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6334)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)




    private void initContainer(@Nullable Bundle savedInstanceState) {
        @SuppressLint("RestrictedApi") final ContentFrameLayout container = new ContentFrameLayout(this);
        container.setBackgroundColor(getResources().getColor(R.color.fragment_bgc));
        container.setId(R.id.delegate_container);
        setContentView(container);
        BaseDelegate fragment = findFragment(getRootDelegateClazz());
修改之前是判断savedInstanceState是否为空
        if (fragment == null) {
            // 初次加载主入口activity的时候设置根Delegate
            loadRootFragment(R.id.delegate_container, setRootDelegate());
        }
    }
```

**Comment by YoKeyword** [comment]
@Jiiiiiin 断点看下出现原因，  测试方式同样是 `不保留活动` 打开

**Comment by YoKeyword** [comment]
@Jiiiiiin  断点调试下原因，测试方法同样是 `不保留活动` 打开

**Comment by wuxiaojun123** [comment]
大佬，这个问题有优雅的解决方案么？我现在activity也会重启。

**Comment by YoKeyword** [comment]
@wuxiaojun123  不保留活动打开，调试下；  这种问题不保留活动打开复现，很容易解决；  一般是重复加载了的原因

**Comment by Dwan-xie** [comment]
这个基本不是APP代码写的导致的问题，因为去后台修改权限后，系统会强制被修改的APP重新创建当前activity，类似于横竖屏切换的。activity的configuration这个方法里有没有监控这种情况，目前大厂的做法也是重启整个app，例如微信(可测试)
