### ISSUE TITLE
APP退到后台，设置不保留活动，进入再进入时报错问题

### ISSUE THREAD

**Issue by hegaojian** [YoKeyword/Fragmentation#881]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twukj.wlb_wls/com.twukj.wlb_wls.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@3cb4e59: Unmarshalling unknown type code 2131755705 at offset 840
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2836)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2911)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@3cb4e59: Unmarshalling unknown type code 2131755705 at offset 840
	at android.os.Parcel.readValue(Parcel.java:2754)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3123)
	at android.os.Parcel.readSparseArray(Parcel.java:2337)
	at android.os.Parcel.readValue(Parcel.java:2732)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3042)
	at android.os.BaseBundle.unparcel(BaseBundle.java:257)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:958)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1208)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
	at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
	at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
	at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
	at com.twukj.wlb_wls.ui.MainRxDetailFragmentActivity.onCreate(MainRxDetailFragmentActivity.java:45)
	at com.twukj.wlb_wls.MainActivity.onCreate(MainActivity.java:130)
	at android.app.Activity.performCreate(Activity.java:7057)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2789)
	... 9 more

**Comment by hegaojian** [comment]
已解决，问题出在了BottomBar中，读写完position释放以后就好了，但是用作者你的demo却没有问题，感觉有种蛋蛋的忧伤.......代码如下：
 static class SavedState extends BaseSavedState {
        private int position;

        public SavedState(Parcel source) {
            super(source);
            try {
                position = source.readInt();
            }finally {
                source.recycle();//读写完最后释放
            }

        }

        public SavedState(Parcelable superState, int position) {
            super(superState);
            this.position = position;
        }

        @Override
        public void writeToParcel(Parcel out, int flags) {
            super.writeToParcel(out, flags);
            try{
                out.writeInt(position);//读写完最后释放
            }finally {
                out.recycle();
            }

        }

        public static final Creator<SavedState> CREATOR = new Creator<SavedState>() {
            public SavedState createFromParcel(Parcel in) {
                return new SavedState(in);
            }

            public SavedState[] newArray(int size) {
                return new SavedState[size];
            }
        };
    }

**Comment by hegaojian** [comment]
已解决，不是作者的库的问题，是我其他的自定义view恢复状态时导致的
