### ISSUE TITLE
after onSavenInstanceState()异常

### ISSUE THREAD

**Issue by Blizzard-liu** [YoKeyword/Fragmentation#891]
用您封装的eventbus库 还是崩啊  应用退到后台，接收到服务器发来的消息，然后跳转到下一个fragment，就崩了。我只有一个mainactivity，其余都是fragment写的

06-05 13:44:07.759 2366-2366/com.winsky.winto.wintopassenger W/Fragmentation: Warning: Perform this commit() action after onSaveInstanceState!
06-05 13:44:07.865 2366-2366/com.winsky.winto.wintopassenger W/Fragmentation: Warning: Perform this popTo() action after onSaveInstanceState!
06-05 13:44:07.877 2366-2366/com.winsky.winto.wintopassenger E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.winsky.winto.wintopassenger, PID: 2366
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
        at android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:791)
        at android.support.v4.app.FragmentationMagician$1.run(FragmentationMagician.java:87)
        at android.support.v4.app.FragmentationMagician.hookStateSaved(FragmentationMagician.java:183)
        at android.support.v4.app.FragmentationMagician.popBackStackAllowingStateLoss(FragmentationMagician.java:84)
        at me.yokeyword.fragmentation.TransactionDelegate$6.run(TransactionDelegate.java:171)
        at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
        at me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
        at me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:17)
        at me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by Blizzard-liu** [comment]
大神 在线等回复啊

**Comment by superlinxiao** [comment]
我也遇到了这个问题，我的解决办法是使用27.0.2的support包，也就是和框架中的support包保持一致。
经过查阅框架代码，发现项目中在检查state的时候，只修改了fragmentManager中的mStateSaved字段，而在我当前使用的27.1.1的support中，会检查mStateSaved || mStopped这两个字段。下面是部分源码：
27.1.1 FragmentManagerImpl 
` private void checkStateLoss() {
        if (isStateSaved()) {
            throw new IllegalStateException(
                    "Can not perform this action after onSaveInstanceState");
        }
        if (mNoTransactionsBecause != null) {
            throw new IllegalStateException(
                    "Can not perform this action inside of " + mNoTransactionsBecause);
        }
    }

    @Override
    public boolean isStateSaved() {
        // See saveAllState() for the explanation of this.  We do this for
        // all platform versions, to keep our behavior more consistent between
        // them.
        return mStateSaved || mStopped;
    }`
27.0.2 FragmentManagerImpl

` private void checkStateLoss() {
        if (mStateSaved) {
            throw new IllegalStateException(
                    "Can not perform this action after onSaveInstanceState");
        }
        if (mNoTransactionsBecause != null) {
            throw new IllegalStateException(
                    "Can not perform this action inside of " + mNoTransactionsBecause);
        }
    }`
fragmentation中检查state

` private static void hookStateSaved(FragmentManager fragmentManager, Runnable runnable) {
        if (!(fragmentManager instanceof FragmentManagerImpl)) return;

        FragmentManagerImpl fragmentManagerImpl = (FragmentManagerImpl) fragmentManager;
        if (isStateSaved(fragmentManager)) {
            fragmentManagerImpl.mStateSaved = false;
            runnable.run();
            fragmentManagerImpl.mStateSaved = true;
        } else {
            runnable.run();
        }
    }`

仅供参考。

**Comment by Blizzard-liu** [comment]
大神啊  我是应用在后台，接收消息跳转发生异常的 ，我的解决办法是判断应用回到前台在进行跳转

**Comment by YoKeyword** [comment]
@Blizzard-liu 是用了v27.1.1吧， Fragmentation升级到v1.3.4， 兼容了它的新检测机制

 support v27.1.1 检查StateLoss的机制变了

````java
    @Override
    public boolean isStateSaved() {
        return mStateSaved || mStopped; // 在27.1.1之前，只检查mStateSaved
    }
````

在Fragmentation `FragmentationMagician`中
````java
    private static void hookStateSaved(FragmentManager fragmentManager, Runnable runnable) {
        ...
        if (isStateSaved(fragmentManager)) {
            fragmentManagerImpl.mStateSaved = false; // 在之前版本中hack了该参数，让其绕过检查
            runnable.run();
            fragmentManagerImpl.mStateSaved = true;
        } else {
            runnable.run();
        }
    }
````
