### ISSUE TITLE
继承SupportActivity，使用默认配置，有时候会出现FragmentAnimator.getEnter()  空指针

### ISSUE THREAD

**Issue by tyzero** [YoKeyword/Fragmentation#894]
#继承SupportActivity， FragmentAnimator.getEnter() 有时候会 空指针

我BaseActivity，BaseFragment 并没有什么逻辑代码，只是打印一些Log。这个crash很难重现。

`
java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference</br>	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)</br>	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)</br>	at android.app.ActivityThread.-wrap11(Unknown Source:0)</br>	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)</br>	at android.os.Handler.dispatchMessage(Handler.java:106)</br>	at android.os.Looper.loop(Looper.java:164)</br>	at android.app.ActivityThread.main(ActivityThread.java:6494)</br>	at java.lang.reflect.Method.invoke(Native Method)</br>	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)</br>	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)</br>Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference</br>	at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)</br>	at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)</br>	at me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)</br>	at me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:120)</br>	at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:48)</br>	at cococ.widget.xx.CBaseFragment.onCreate(CBaseFragment.kt:42)</br>	at com.xx.BaseFragment.onCreate(BaseFragment.kt:42)</br>	at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)</br>	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)</br>	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)</br>	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)</br>	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)</br>	at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3194)</br>	at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:184)</br>	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:355)</br>	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)</br>	at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)</br>	at 
`

 
* Library version   me.yokeyword:fragmentation:1.3.3
* Support-v4 version com.android.support:support-v4:27.1.1

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/825

**Comment by tyzero** [comment]
@LonelyMushroom 感谢，修复了🤝

**Comment by tyzero** [comment]
我觉得可以像onBackSupportPressed 那样，把SupportFragment 里的 onSaveInstanceState方法重写成final的。哈哈

**Comment by Lemon-666-byte** [comment]
> @LonelyMushroom 感谢，修复了

具体修复代码 能贴出来吗 ？谢谢了
