### ISSUE TITLE
matisse 使用会再次重复创建fragment栈

### ISSUE THREAD

**Issue by stoneLee81** [YoKeyword/Fragmentation#902]
我打开了不保留活动，在fragment使用matisse时，返回发现fragment为空，然后会出发再次创建逻辑，但原来的又没有销毁

**Comment by stoneLee81** [comment]
仿照微信的demo里写的
@Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        SupportFragment firstFragment = findFragment(PaletteFragment.class);

        if (firstFragment == null) {
            mFragments[FIRST] = PaletteFragment.newInstance(wrapped1);
            mFragments[SECOND] = DayPlanFragment.newInstance(wrapped2);
            mFragments[THIRD] = ProfileTestFragment.newInstance(wrapped3);

            loadMultipleRootFragment(R.id.fl_tab_container, FIRST,
                mFragments[FIRST],
                mFragments[SECOND],
                mFragments[THIRD]);
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题

            // 这里我们需要拿到mFragments的引用
            mFragments[FIRST] = firstFragment;
            mFragments[SECOND] = findFragment(DayPlanFragment.class);
            mFragments[THIRD] = findFragment(ProfileTestFragment.class);
        }
    }
在ProfileTestFragment还有3个fragment,如果重加载原来的fragment还在，会重复

**Comment by stoneLee81** [comment]
![240b3f8b27128cca4db5e64cf875b11b](https://user-images.githubusercontent.com/18001708/41508530-f1fe736c-7278-11e8-9ec5-7f01a0cd23e7.jpg)

**Comment by stoneLee81** [comment]
<img width="316" alt="3e2b6645-f22d-42d4-b76d-85c3af9b2a1a" src="https://user-images.githubusercontent.com/18001708/41508535-1037a6fa-7279-11e8-9b60-66ffdcafbae8.png">

**Comment by YoKeyword** [comment]
> SupportFragment firstFragment = findFragment(PaletteFragment.class);

改为`findChildFragment()`， 是孩子关系，所以用findChild

**Comment by stoneLee81** [comment]
多谢，确实是不会重复了，但会报这个错误
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.setNextAnim(int)' on a null object reference
                                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:771)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                                  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                                                                  at android.os.Handler.handleCallback(Handler.java:790)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6753)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-19 11:11:25.828 21045-21045/trip.com.tomato E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by YoKeyword** [comment]
> mFragments[SECOND] = findFragment(DayPlanFragment.class);
> mFragments[THIRD] = findFragment(ProfileTestFragment.class);

这里同样改成 `findChildFragment()`
