### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference

### ISSUE THREAD

**Issue by AKitTop** [YoKeyword/Fragmentation#905]
# Issues Guideline
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference
	at android.view.ViewGroup.resetCancelNextUpFlag(ViewGroup.java:2436)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:467)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1840)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3200)
	at me.yokeyword.fragmentation.SupportActivity.dispatchTouchEvent(SupportActivity.java:59)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:422)
	at android.view.View.dispatchPointerEvent(View.java:10286)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4524)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4380)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3893)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3963)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3921)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4063)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3929)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4120)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3893)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3963)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3921)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3929)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3893)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6370)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6344)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6299)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6480)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:180)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6451)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6503)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:908)
	at android.view.Choreographer.doCallbacks(Choreographer.java:720)
	at android.view.Choreographer.doFrame(Choreographer.java:649)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:894)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6211)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

Following information can help us to resolve the issue faster.

* Library version  1.3.4
* Support-v4 version 25.3.1
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by XiaoDon** [comment]
请问你这个问题解决了吗?
