### ISSUE TITLE
fragment 跳转到拨电话返回后程序崩溃 

### ISSUE THREAD

**Issue by 624205157** [YoKeyword/Fragmentation#922]
# Issues Guideline

Following information can help us to resolve the issue faster.

* me.yokeyword:fragmentation:1.3.5
* com.android.support:support-v4:26.1.0
* E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.gongzhuling.pcust, PID: 13941
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gongzhuling.pcust/com.gongzhuling.pcust.activity.MainActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.gongzhuling.pcust.fragment.home.HomeOneFragment: could not find Fragment constructor
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
                                                       at android.app.ActivityThread.-wrap18(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                    Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.gongzhuling.pcust.fragment.home.HomeOneFragment: could not find Fragment constructor
                                                       at android.support.v4.app.Fragment.instantiate(Fragment.java:478)
                                                       at android.support.v4.app.FragmentContainer.instantiate(FragmentContainer.java:33)
                                                       at android.support.v4.app.Fragment$2.instantiate(Fragment.java:2328)
                                                       at android.support.v4.app.FragmentState.instantiate(Fragment.java:115)
                                                       at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3055)
                                                       at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1446)
                                                       at android.support.v4.app.Fragment.onCreate(Fragment.java:1419)
                                                       at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:47)
                                                       at com.gongzhuling.tool.ui.fragment.BaseFragment.onCreate(BaseFragment.java:49)
                                                       at com.gongzhuling.pcust.fragment.home.HomeLevelOneFragment.onCreate(HomeLevelOneFragment.java:490)
                                                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3166)
                                                       at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1448)
                                                       at android.support.v4.app.Fragment.onCreate(Fragment.java:1419)
                                                       at me.yokeyword.fragmentation.SupportFragment.onCreate(SupportFragment.java:47)
                                                       at com.gongzhuling.tool.ui.fragment.BaseFragment.onCreate(BaseFragment.java:49)
                                                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3166)
                                                       at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:181)
                                                       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:319)
                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                                                       at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
                                                       at com.gongzhuling.tool.ui.activity.BaseActivity.onCreate(BaseActivity.java:48)
                                                       at android.app.Activity.performCreate(Activity.java:6999)
                                                       at android.app.Activity.performCreate(Activity.java:6990)
07-01 14:51:37.729 13941-13941/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                       	... 10 more
                                                    Caused by: java.lang.NoSuchMethodException: <init> []
                                                       at java.lang.Class.getConstructor0(Class.java:2320)
                                                       at java.lang.Class.getConstructor(Class.java:1725)
                                                       at android.support.v4.app.Fragment.instantiate(Fragment.java:459)
* Screenshots

在Bugly抓到好多，我自已也是碰巧连续触发崩溃如题的操作，但是Bugly抓到的是其他不固定操作造成的

**Comment by LonelyMushroom** [comment]
哥们你参考下这个不
https://stackoverflow.com/questions/10450348/do-fragments-really-need-an-empty-constructor

**Comment by 624205157** [comment]
谢啦，明白了
