### ISSUE TITLE
想请问一下是不是跟butterknife不太兼容。

### ISSUE THREAD

**Issue by edzjx** [YoKeyword/Fragmentation#941]
# Issues Guideline

直接在作者的demo上修改的代码
在WechatFirstTabFragment 里添加实验butterknife8.8.1，发现了一个问题，还是需要在initView()对butterknife注解的View控件显示的通过FindViewById来指定，否则App会直接崩溃。

添加引用的butterknife的办法是采取官方的方式，没有在项目Build.gradle你添加引用，而是在demo model的build.gradle添加的引用
添加的办法
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile "com.android.support:appcompat-v7:$rootProject.v4Version"
    compile "com.android.support:design:$rootProject.v4Version"
    compile "com.android.support:cardview-v7:$rootProject.v4Version"
    compile "com.android.support:recyclerview-v7:$rootProject.v4Version"
    compile project(':fragmentation')
    compile project(':fragmentation_swipeback')
    // EventBus
    compile project(':eventbus_activity_scope')
    compile 'org.greenrobot:eventbus:3.0.0'
    //    apt 'org.greenrobot:eventbus-annotation-processor:3.0.1'

    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}
```

然后在WechatFirstTabFragment中尝试使用butterknife注解，就方式开始说的情况
具体是这样的，在WechatFirstTabFragment注解View成员。
```
/**
     * BindView时，控件变量无法用private修饰
     * 作者原话：Because the generated code needs to be able to assign the values.
     */
    @BindView(R.id.toolbar)
     Toolbar mToolbar;
    @BindView(R.id.refresh_layout)
     SwipeRefreshLayout mRefreshLayout;
    @BindView(R.id.recy)
     RecyclerView mRecy;
```
然后在onCreateView（）和onDestroyView（）里分别绑定注解和解绑注解
```
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        //wechat_fragment_tab_first 主要放置个SwipeRefreshLayout里面嵌入一个RecyclerView
        View view = inflater.inflate(R.layout.wechat_fragment_tab_first, container, false);
        initView(view);
        unbinder = ButterKnife.bind(this, view);
        return view;
    }
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        EventBusActivityScope.getDefault(_mActivity).unregister(this);
        unbinder.unbind();
    }
```
   ```
 /**
     * 初始化视图
     * 此项目，作者喜欢用这个方法封装UI控件的加载的一些代码
     *
     * @param view
     */
    private void initView(View view) {
        //ButterKnife.findById就是调用的view.findviewbyid，一样的自动转换类型
        //ButterKnife 第一次使用失败了，如果没有初始化下面的这些控件，程序会崩溃
        mToolbar = ButterKnife.findById(view,R.id.toolbar);//include重复控件，引用toolbar.xml就是一个android.support.v7.widget.Toolbar
        mRefreshLayout =  view.findViewById(R.id.refresh_layout);//wechat_fragment_tab_first里的SwipeRefreshLayout刷新控件
        mRecy = view.findViewById(R.id.recy);//android.support.v7.widget.RecyclerView
        //EventBus是基于Java订阅者/被订阅者模式的消息通信第三方框架具体讲解可看“https://blog.csdn.net/u011240877/article/details/73015939
        EventBusActivityScope.getDefault(_mActivity).register(this);//注册EventBus

        mToolbar.setTitle(R.string.home);
    }

```
然后尝试注释掉initView（）中关于View成员的显示绑定，但是程序会崩溃。

**Comment by YoKeyword** [comment]
应该不存在兼容问题，Fragmentation只会对Fragment内部做了一些封装，对View级别无任何干涉

Butterknife并不需要`mToolbar = ButterKnife.findById(view,R.id.toolbar);`， 只需
````java
@BindView(R.id.toolbar)
Toolbar mToolbar;
````
即可使用；  

如果使用崩溃的话，看下Log，猜测是其他问题导致，比如在`onDestroyView()`之后又操作了View

**Comment by thetazhou** [comment]
在继承了BaseMainFragment的自定义fragment类中的onCreateView方法里面，出错行的代码：
View view = inflater.inflate(R.layout.fragment_aaa, container, false);

日志：
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.yokeyword.sample/ajiang.app.android.MainActivity}: java.lang.RuntimeException: Failed to resolve attribute at index 6
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
     Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 6
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:603)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6678)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6846)
        at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2120)
        at android.support.design.widget.AppBarLayout$LayoutParams.<init>(AppBarLayout.java:681)
        at android.support.design.widget.AppBarLayout.generateLayoutParams(AppBarLayout.java:336)
        at android.support.design.widget.AppBarLayout.generateLayoutParams(AppBarLayout.java:106)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at ajiang.app.android.fragment.second.ChooseFragment.onCreateView(ChooseFragment.java:35)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2361)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
  
请问大概是什么原因？
