### ISSUE TITLE
 java.lang.RuntimeException: Parcel android.os.Parcel@b27e703: Unmarshalling unknown type code 

### ISSUE THREAD

**Issue by jiegege10** [YoKeyword/Fragmentation#987]
# Issues Guideline
What is the problem?

Following information can help us to resolve the issue faster.

* Library version 1.16
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

java.lang.RuntimeException: Parcel android.os.Parcel@b27e703: Unmarshalling unknown type code 1176255488 at offset 3092
	at android.os.Parcel.readValue(Parcel.java:2444)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
	at android.os.Parcel.readSparseArray(Parcel.java:2068)
	at android.os.Parcel.readValue(Parcel.java:2422)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
	at android.os.BaseBundle.unparcel(BaseBundle.java:271)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1325)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
	at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3176)
	at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:181)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:331)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
	at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:38)
	at wanqi.rental.com.base.activity.BaseCompat2Activity.onCreate(BaseCompat2Activity.java:54)
	at android.app.Activity.performCreate(Activity.java:6865)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2694)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by qigithub** [comment]
我也遇到同样的问题
